### ISSUE TITLE
Issues with setup_r5()

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#10]
I noticed that after the creation of R5 core some new files were created in `inst/extdata` (when running it with the sample data). These are: `network.dat`, `poa_osm.pbf.mapdb` and `poa_osm.pbf.mapdb.p`. Any ideas what that might be?

Also, when running `setup_r5` with a .pbf file but no gtfs an error arises (I just copied the pbf file to ~ in this example):
```
> setup_r5("~")
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0.jar
12 [main] INFO com.conveyal.r5.transit.TransportNetwork - File '~\build-config.json' is not present. Using default configuration.
 Error in rJava::.jnew("com.conveyal.r5.R5RCore", data_path) : 
  java.lang.NullPointerException 
```

Edit: Actually, I tried creating a `test` folder inside `~` with the exact same files as `inst/extdata"` and run `setup_r5("~/test")` and I get the same error message as above.

**Comment by dhersz** [comment]
The `network.dat` is the graph, I suppose, right? But not sure what the others are.

**Comment by rafapereirabr** [comment]
I' not entirely sure why R5 create these other `.pbf.mapdb.p`, though this seems to be a data base that R5 uses internally. In any case, I don't see why this should be a concern for the moment, right?

Regarding the other questions, update the lastest version of `r5r` and let me know if the problem persists. Rigth now, the `setup_r5` function should be able to build a network if only a OSM.pbf file is provided with no GTFS. So, the GTFS file is optional so to speak, but it cannot create a network without an OSM.pbf file.

**Comment by mvpsaraiva** [comment]
Apparently, the pbf.mapdb and pbf.mapdb.p files are required by R5. I tried deleting them, but R5 created them again the next time I ran setup. I've added them to .gitignore.

**Comment by dhersz** [comment]
The problem persists. Here's a reproducible code, can you check if you get the same error?

```r
dir.create("~/test_r5r")

files_path <- system.file("extdata", package = "r5r")

file.copy(
  from = paste0(files_path, "/", list.files(files_path)), 
  to = "~/test_r5r"
)

setup_r5("~/test_r5r")
```

**Comment by mvpsaraiva** [comment]
In my test, "~/test_r5r" is not recognised as a correct path. I don't know if this is an R or Java issue. Changing the path to "/home/marcus/test_r5r" worked.

I've found the function path.expand() that does what we need.

**Comment by mvpsaraiva** [comment]
I believe it's working now. 
ce42bdb

**Comment by dhersz** [comment]
Works alright for me now!
