### ISSUE TITLE
automatic message to check Java version

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#101]
It would be good to include a quick automatic check of the Java version. This below is a piece of code suggested by Simon Urbanek, one of the core authors of rJava. I think we could included it as a first check within the `setup_r5` function. If the person does not have the necessary jdk installed, then the function should throw a clear error with the reason.

```
library(r5r)
library(rJava)

# get installed version of Java
.jinit()
ver <- .jcall("java.lang.System","S","getProperty","java.version")
ver

# check version >= 11
ver <- as.numeric(gsub("\\..*","",ver))
if (ver < 11) error("This package requires Java 11 or higher. Please update your Java installation.")
```

**Comment by mvpsaraiva** [comment]
Instead of testing:

`if (ver < 11) error("This package requires Java 11 or higher. Please update your Java installation.")`

Shouldn't we test `if (ver != 11)`? We don't know if R5R works with newer versions of Java. That's something we need to test, actually.

**Comment by rafapereirabr** [comment]
Fair enough. I'll run some tests with jdk 13.02 and 14.02. I couldn't find jdk 12 though

**Comment by rafapereirabr** [comment]
The package works well with both jdk 13.02 and 14.02.

**Comment by mvpsaraiva** [comment]
That's good to know! In Java, it's not always guaranteed that any software will run on newer versions of the JVM than it was designed for.
