### ISSUE TITLE
build package website with pkgdown

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#103]
As we move forward with `r5r`, I think we could build the [pkgdown](https://pkgdown.r-lib.org/) website of the package.

**Comment by rafapereirabr** [comment]
We should do this after the package is published on CRAN.

**Comment by dhersz** [comment]
The website is now up and running in https://ipeagit.github.io/r5r/.

Some work to do (anyone is welcome to add something to the list as ideas -and problems 😆 - come up):
- [ ] Change homepage
- [ ] Fix broken images in the vignette (probably through hosting them in the web?)

**Comment by rafapereirabr** [comment]
I think I know how to fix the broken images.

**Comment by dhersz** [comment]
Thanks! Website updated too.

**Comment by rafapereirabr** [comment]
Good. I just realized I had to fix the hexsticker on the readme as well.

**Comment by rafapereirabr** [comment]
I think we can close this now. right?

**Comment by dhersz** [comment]
Finally fixed the references page in https://github.com/ipeaGIT/r5r/commit/d4da4dd448873d8faddade00d4e26afb227cdd50. Closing this now.
