### ISSUE TITLE
Missing documentation install commands and typo

### ISSUE THREAD

**Issue by RenatoArbex** [ipeaGIT/r5r#107]
Running the example snippet with a fresh install results in errors, please consider adding the required installation lines as trying to replicate the commands as now won't work for a fresh install of R.

install.packages("devtools")
install.packages("tidyverse")

There is also a typo in the example snippet, there is a missing colon when specifying the date.

**Comment by dhersz** [comment]
Hi Renato, thanks for the catch. I have removed the `lubridate` dependency and ajusted the README example accordingly in https://github.com/ipeaGIT/r5r/commit/3923d8fb686b45d187c3c470d709d4d864499b7a, which should fix the errors.

Regarding the addition of `install.packages("devtools")`, I feel like it may not be a good practice to include a package installation command (which affects the user's computer and environment) in the example snippet, but I'd like to hear what you and others think about this.

Cheers!

**Comment by rafapereirabr** [comment]
Hi Renato. Thanks for the heads up. Daniel's last commit have fixed the typo and removed the 'tidyverse' dependecy. Regarding the `devtools` package, our instructions in the `README.md` and i the vignette read as follows.

`devtools::install_github("ipeaGIT/r5r", subdir = "r-package")`

This is the `R` syntax to say `package::function()`, similar to how one would do in Python `gpd.GeoDataFrame()`, so it makes explicit that the devtools package needs to be installed.

**Comment by RenatoArbex** [comment]
Great, thanks for the quick corrections! I'd then just suggest to mention
how to install the package in the readme, as users unfamiliar with R might
have some difficulties trying to figure out why it does not work after a
clean install, as I did. The package is great.

Best

Em qua, 2 de set de 2020 19:58, Rafael H M Pereira <notifications@github.com>
escreveu:

**Comment by rafapereirabr** [comment]
Thank you, Renato!
