### ISSUE TITLE
hex sticker

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#11]
First things first. `r5` should have a cool sticker :) .  I've added a script that creates a very simple sticker base we can use as a starting point. [Please have a look at it here](https://github.com/ipeaGIT/r5r/tree/master/r-package/man/figures).

**Comment by mvpsaraiva** [comment]
Now, my productivity is gone... I'll spend two months procrastinating on a logo 😆

**Comment by rafapereirabr** [comment]
This is a rough idea with a shortest path tree as the "root" of `r5r`.

<img width="293" alt="Capture" src="https://user-images.githubusercontent.com/7448421/90389102-51604500-e05f-11ea-9f65-008a1217feaf.PNG">

**Comment by rafapereirabr** [comment]
Ok, this is my first result using the sample data we have in the package.

![r5r_test_b](https://user-images.githubusercontent.com/7448421/90701996-8091d480-e260-11ea-800f-1cad29aa400a.png)

**Comment by rafapereirabr** [comment]
I believe we can close this now. Thanks @mvpsaraiva !
