### ISSUE TITLE
Vignette issues

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#111]
I was checking the vignette on CRAN and realized that when we list the sample files that come with the package the `network.dat` and `.mapdb`s are also shown:

![image](https://user-images.githubusercontent.com/1557047/93602571-2be59480-f999-11ea-8329-8b1567aff440.png)

This leaves me confused, since these files should not exist without running `setup_r5`. So either `setup_r5` is running somewhere during CRAN build or CRAN is cloning our repo with these files already created (not sure how CRAN submission and build works though, just a guess).

**Comment by rafapereirabr** [comment]
Yep, this is puzzling. Specially considering that we do not run any java dependent function on CRAN.

**Comment by dhersz** [comment]
From Hadley's [R Packages book](https://r-pkgs.org/vignettes.html#vignette-cran):

> Note that since you build vignettes locally, CRAN only receives the html/pdf and the source code. However, CRAN does not re-build the vignette. It only checks that the code is runnable (by running it).

We should fix it locally.

**Comment by dhersz** [comment]
https://github.com/ipeaGIT/r5r/commit/196b042a613970b1595a4e2d681d5b90d409d2b9 should fix it.
