### ISSUE TITLE
jdx dependency

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#113]
Ou [latest CRAN](https://cran.r-project.org/web/checks/check_results_r5r.html) check returns the following error message:

> using R version 4.0.2 Patched (2020-09-17 r79226)
> using platform: i386-pc-solaris2.10 (32-bit)
> using session charset: UTF-8
> using option ‘--no-stop-on-test-error’
> checking for file ‘r5r/DESCRIPTION’ ... OK
> checking extension type ... Package
> this is package ‘r5r’ version ‘0.1.0’
> package encoding: UTF-8
> checking package namespace information ... OK
> **checking package dependencies ... ERROR**
> **Package required but not available: ‘jdx’**
> 
> See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
> manual.
> DONE
> Status: 1 ERROR

I couldn't find a way to address this error, so I would appreciate some help here :) Perhaps @floidgilbert could shed some light here, please?

This is how our depencies look like in our `DESCRIPTION` file.

```
Suggests:
    covr,
    ggplot2 (>= 3.3.1),
    knitr,
    mapview,
    rmarkdown,
    testthat
Imports:
    checkmate,
    data.table,
    methods,
    jdx (>= 0.1.4),
    rJava (>= 0.9-13),
    sf (>= 0.9-3),
    sfheaders,
    utils
```

**Comment by floidgilbert** [comment]
I haven't encountered that error. A quick Google search shows that it is a common error on CRAN and there appears to be many possible causes. I suggest contacting the folks @ CRAN for suggestions. It's interesting that it fails only on Solaris.

**Comment by rafapereirabr** [comment]
Uwe confirmed to me that the Solaris server does not have Java Runtime Environment (>= 8). I asked whether this error on Solaris alone should be a problem to keep the package on CRAN. Here is his response:

```
On 25.09.2020

Ideally move the jdx dependency to "Suggests" if that nmakes sense and
you have funtionality that does not strictly depend on jdx in order to
make your package available on more platforms. If you need it strictly,
that's OK, too.

Best,
Uwe Ligges
```

Our package does depend on `jdx` so we are keeping it under `Imports`. I guess this shouldn't be a big issue. Closing this issue for now.
