### ISSUE TITLE
Document that detailed_itineraries uses a different algorithm from travel_time_matrix

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#114]
If I'm understanding the code correctly, I believe `detailed_itineraries` uses `PointToPointRouter` in R5, which I think uses a McRaptor-based algorithm under the hood to find paths that are optimal or less than `suboptimalMinutes` worse, with some heuristics around multiple access modes, riding the same patterns, etc. `travel_time_matrix` uses regular RAPTOR. It should probably be documented that the algorithms used are different (and at some point it would be worth documenting/writing a paper about the suboptimal path routing algorithm - I think that's fairly unique and not well documented).

**Comment by rafapereirabr** [comment]
Thank you for the suggestions, Matt. I agree we should add this info to the function documentation. Do you know any specific publication or patent on the `McRaptor` and `RAPTOR` algorithms we could refer to in out documentation?

**Comment by mattwigway** [comment]
The base RAPTOR and McRAPTOR algorithms are described in [this paper](https://pubsonline.informs.org/doi/abs/10.1287/trsc.2014.0534?casa_token=30a5KQr3SCwAAAAA%3AogDP8cY4fDXmWsVW-rHXLSr4SKefhpbynEWEt3K7WP7AOEVPZGNTzbhN7MMYbtouLO9lH8rBEw&) and the R5-specific extensions to RAPTOR in [this one](http://hdl.handle.net/2286/R.A.218654). In R5, McRAPTOR also uses a [constrained random walk sample of the possible departure times](https://www.jtlu.org/index.php/jtlu/article/view/1379), rather than all possible departure times; this is controlled by the monteCarloDraws parameter, and setting it to a high number will sap performance (for fare-based McRAPTOR routing, we usually set it to ~40, you might be able to go higher with the suboptimal-path routing as there should be fewer codominant paths). RAPTOR uses a systematic sample of one departure per minute over the time window. The specific extensions to McRAPTOR to do suboptimal path routing are not documented afaik - might be a good publication to work on at some point.

**Comment by rafapereirabr** [comment]
Hi Matt. thanks for the clarification. I have drafted below some information we could add to the documenation of both functions. It should be short though informative enough and and direct users to the references with full detailed info. Please feel free to add other details I missed and you think are crucial. Feel free to send us your suggestions in a pull request or, if you prefer, you could paste your suggestions in a comment below and I will add them to the package.

**travel_time_matrix**:
```
#' @details The travel_time_matrix function uses an R5-specific extension to the
#'          RAPTOR routing algorithm (see Conway et al., 2017). This RAPTOR 
#'          extension uses a systematic sample of one departure per minute over
#'          the time window set by the user in the 'time_window' parameter'. A
#'          detailed description of base RAPTOR can be found in Delling et al (2015).
#'          - Conway, M. W., Byrd, A., & van der Linden, M. (2017). Evidence-based
#'            transit and land use sketch planning using interactive accessibility
#'            methods on combined schedule and headway-based networks. 
#'            Transportation Research Record, 2653(1), 45-53.
#'          - Delling, D., Pajor, T., & Werneck, R. F. (2015). Round-based public
#'            transit routing. Transportation Science, 49(3), 591-604.
```


**detailed_itineraries:**
```
#' @details The detailed_itineraries function uses an R5-specific extension to
#'          the McRAPTOR routing algorithm to find paths that are optimal or less
#'          than optimal, with some heuristics around multiple access modes, 
#'          riding the same patterns, etc. The specific extension to McRAPTOR to
#'          do suboptimal path routing are not documented yet, but a detailed 
#'          description of base McRAPTOR can be found in Delling et al (2015).
#'          - Delling, D., Pajor, T., & Werneck, R. F. (2015). Round-based public
#'            transit routing. Transportation Science, 49(3), 591-604.
```

**Comment by rafapereirabr** [comment]
I've updated the package documentation with the info above. Closing this issue for now, but we're very open for suggestions
