### ISSUE TITLE
Arquivos Porto Algre

### ISSUE THREAD

**Issue by fagnersutel** [ipeaGIT/r5r#115]
ONde encontro os arquivos de Porto Alegre para dar uma olhada?

**Comment by mvpsaraiva** [comment]
Oi @fagnersutel. 

Podes obter a rede viária da cidade em [https://export.hotosm.org/en/v3/](https://export.hotosm.org/en/v3/). Basta selecionar a área desejada e baixar em formato pbf.
Os dados de GTFS estão disponíveis em [http://datapoa.com.br/dataset/gtfs](http://datapoa.com.br/dataset/gtfs).

Se tiveres algum feedback, nos escreva.
Obrigado por usar nosso pacote.
