### ISSUE TITLE
Add sample of frequency-based GTFS

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#116]
It would be good to include in the r5r package a sample of a frequency-based GTFS to test/illustrate the coming functionality of `time_window` in the `travel_time_matrix`.  Unfortunately, the data of Porto Alegre is not frequency-based.

We have a sample of the São Paulo GTFS feed stored in the `gtfs2gps` package. The file is 1.6MB, so we could use a sample of that file. This would also require a set of points and a `OSM.pbf` sample for Sao Paulo.

**Comment by mvpsaraiva** [comment]
The OpenTripPlanner R package has a function `otp_dl_demo()` do download sample data. Perhaps we could do something similar? This would make it easier to add more sample datasets in the future.

**Comment by rafapereirabr** [comment]
> The OpenTripPlanner R package has a function `otp_dl_demo()` do download sample data. Perhaps we could do something similar? This would make it easier to add more sample datasets in the future. This is a good idea but I think we sould only use it a last resort. Ideally, the sample data sets used in the package should be stored within the package to avoid issues with internet connection and downloading time when we run tests/examples.

**Comment by rafapereirabr** [comment]
Could @mvpsaraiva or @dhersz add a small `.pbf` of the city center of Sao Paulo?

**Comment by rafapereirabr** [comment]
Fixed the description of the  `percentiles` parameter. The description above was wrong.

```
#' @param percentiles numeric vector. Defaults to '50', returning the median
#'                    travel time for a given time_window. If a numeric vector is passed,
#'                    for example c(25, 50, 75), the function will return
#'                    additional columns with the travel times within percentiles
#'                    of trips. For example, if the 25 percentile of trips between
#'                    A and B is 15 minutes, this means that 25% of all trips
#'                    taken between A and B within the set time window are shorter
#'                    than 15 minutes.
```

**Comment by rafapereirabr** [comment]
Marchus has added the files, which can be accessed like this:

```
data_path <- system.file("extdata/spo", package = "r5r")
list.files(data_path)

points <- fread(system.file("extdata/spo/spo_hexgrid.csv", package = "r5r"))
head(points)

r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)

```

**Comment by rafapereirabr** [comment]
I've moved the Porto Alegre files to the directory `system.file("extdata/poa", package = "r5r")` and updated the scripts in all examples and tests and vignette. I guess we can close this issue now. I'll close it in my next push with these updates.
