### ISSUE TITLE
build intro vignette

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#12]
1st (incomplete) draft [here](https://github.com/ipeaGIT/r5r/blob/master/r-package/vignettes/intro_to_r5r.Rmd)

**Comment by rafapereirabr** [comment]
Hi all. I've finished the intro vignette. I'm closing this issue for now, but please feel free to reopen it if you have any suggestions

**Comment by dhersz** [comment]
I have made some tweaks in https://github.com/ipeaGIT/r5r/commit/03f475664e443c5e32ca62826096d54b73411fdd.

Notably:
- Stressed the importance of allocating memory before attaching `r5r`.
- Changed a `max_walk_dist` argument from 5 to 5000 (in the travel time matrix, if I'm not mistaken).
