### ISSUE TITLE
annoying error from java

### ISSUE THREAD

**Issue by xtimbeau** [ipeaGIT/r5r#121]
I got the following error from r5r when using r5r::travel_time_matrix

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, : java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Recursive load of: (com.conveyal.r5.analyst.FreeFormPointSet@16d1b660, StreetLayer(base), WALK)

It will be difficult to setup a reproductible test because it happens when calling time_travel_matrix for large numbers of destination (around 5000) and origins (around 20, so it should send back a 100 000 rows data.table maximum, around 2000 in fact because of the tmax limit) times 30 000 packets of such destinations and origins (as I am calculating the ttm over a grid). 

Stranger even, when I send again (after stopping in the debugger when the error occurs) it seems to work the second time.

Any hints ?

XT

**Comment by xtimbeau** [comment]
A complement to my previous comment. 
When I detect the error, I run a gc() and try again the same request is sufficient for it to work. Apparently, over the request I send the second one is always working as expected. I have not found any pattern in the failing request and I suppose it is linked to the number of requests between two failures.

**Comment by mvpsaraiva** [comment]
Hi @xtimbeau. 
Just checking if I understood the problem correctly... Each individual call of `travel_time_matrix` has 20 origins and 5.000 destinations, and you do 30.000 of such calls? Also, each call has different sets of origins and destinations?

**Comment by xtimbeau** [comment]
yes exactly

Le dim. 11 oct. 2020 à 18:57, Marcus Saraiva <notifications@github.com> a
écrit :

**Comment by mvpsaraiva** [comment]
Ok. A final question: the error mentions something about concurrency (`java.util.concurrent.ExecutionException`). Do you do all `travel_time_matrix` calls sequentially or do you do some manual parallelisation within R?

**Comment by xtimbeau** [comment]
no sequentially using map from purrr
I think r5r is doing all the parallelization

Le dim. 11 oct. 2020 à 19:04, Marcus Saraiva <notifications@github.com> a
écrit :

**Comment by mvpsaraiva** [comment]
Indeed, r5r does all the parallelisation. 
Thanks for your feedback, I have an idea of what the problem might be. I'll get back to you once we have a fix.

**Comment by xtimbeau** [comment]
👍
Le dim. 11 oct. 2020 à 19:08, Marcus Saraiva <notifications@github.com> a
écrit :

**Comment by xtimbeau** [comment]
When increasing the memory allocation to Java, the probability of an error from the java core seems to diminish.

**Comment by rafapereirabr** [comment]
Hi @xtimbeau . Have tried using the latested version of r5r? I'm wodering if the problem you were facing has been solved with the new version

**Comment by xtimbeau** [comment]
Intensively and I have not encountered any errors so far with r5
seems the issue is solved! thanks a lot.
Please find attached an example of an accessibility index form Ile de
France calculated with r5r. It is the time in muntes needed to reach 100k
jobs using transit (on a time window of 1 hour, taking the 5% best time
over a hundred to model optimisation by user of the schedule possibility).
The resolution is 50mx50m.
I managed to use azure clusters to compute the whole thing in less than 15
hours (there are around 2G pair timing to be computed), so I would say it
has proven to be quite robust.
All the best,

**Comment by rafapereirabr** [comment]
Thank you for your feedback, @xtimbeau ! And thanks @mvpsaraiva for solving this issue.
