### ISSUE TITLE
back on CRAN

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#122]
The messsage I received from the CRAN team. 

```
This still does not set timeout as reported.

The results are fine now, but the code will faill again if it runs into
timeouts [on the ATLAS server], if we read it correctly.

Please fix and resubmit.

Best,
Uwe Ligges
```

Apparently, the package is taking too long to install and check. I suspect this is because the `download_r5` function can take a long time due low-speed internet connection.  If this is the problem, perhaps replacing `@examples \donttest{}`  with `@examples \dontrun{}` should do the trick.

**Comment by mvpsaraiva** [comment]
This timeout probably is caused by `download_r5`, because `setup_r5` doesn't take too long in the sample data provided.
There are softwares called 'obfuscators' or 'optimizers', that compress Java bytecode and can make the Jar file up to 90% smaller. We can try to use one of those.

**Comment by rafapereirabr** [comment]
That could be one line action but only if it does not require any additional software from the user.

In any case, I'm finding this whole *timeout* issue a bit strange.  It takes me only about 4 minutes to run a full CMD check locally including all tests.

```
tictoc::tic()
devtools::check(pkg = ".",  cran = FALSE, env_vars = c(NOT_CRAN = "true"))
tictoc::toc()

> 200.06 sec elapsed
```

**Comment by rafapereirabr** [comment]
I've replaced`@examples \donttest{} `  with  `@examples \dontrun{}` in the functions `stop_r5()`, setup_r5 and `download_r5`. This change reduced the time of CMD check from 219.34 secs to 175.84 sec in my windows machine. Package resubmitted. Fingers crossed. Commit #60344f4
