### ISSUE TITLE
error with set setup_r5

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#125]
I get this stranger error in the `setup_r5()` function after the the last JAR update (`r5r_v4.9.0_20201030.jar`).

It works fine when I run it for the Porto Alegre sample data.
```
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path, verbose = FALSE)
```
However, it throws this error when I use it in the sample data for Sao Paulo.
``` 
data_path <- system.file("extdata/spo", package = "r5r")
r5r_core <- setup_r5(data_path, verbose = FALSE)

> Error in rJava::.jnew("org.ipea.r5r.R5RCore", data_path, verbose) : 
  java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.  
```

**Comment by mvpsaraiva** [comment]
That is quite strange.
I have tested it on my computer and it worked. It looks like your network.dat file is corrupted. 
Can you delete it and try again? If it works, perhaps we could add a parameter `rebuild_network` in `setup_r5()` for those cases.

**Comment by rafapereirabr** [comment]
I deleted the `spo_osm.pbf.mapdb.p` and `spo_osm.pbf.mapdb` files created by `r5r` and then it worked. Not sure what caused this, but I guess we can close this issue for now. Thanks, Marcus !
