### ISSUE TITLE
Multiple paths

### ISSUE THREAD

**Issue by mortewle** [ipeaGIT/r5r#126]
Hi, are there plans to make the detailed_itineraries option shortest_path=FALSE work for all transport modes, not just transit? Like a Dijkstra/labeling/link elimination algorithm, where you can choose your desired number of paths for each OD pair.

**Comment by rafapereirabr** [comment]
@mvpsaraiva , is this something that would be possible to do changing R5 Java code?

**Comment by mvpsaraiva** [comment]
Hi @mortewle and @rafapereirabr. Sorry I've missed this. r5r only passes through to the user any results R5 produces, and currently R5 returns only one path for walk, bicycle, and car modes. If people at Conveyal add this feature to R5 in the future, we can update the package to include it. I think this change is too big, and too deep into R5's codebase, for us to implement on our side.

**Comment by rafapereirabr** [comment]
Thank you for clarifying, Marcus. @mortewle, perhaps you would consider opening this issue on the R5 github. I'll be closing this issue for now but we can open it again latter once R5 includes this option.
