### ISSUE TITLE
Add columns with population and number of schools in sample data set

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#128]
Add 2 columns to sample data set of points: population and number of schools in sample data set. This will allow us to use the sample data in the package to demonstrate how to calculate accessibility estimates in vignettes, examples, etc

**Comment by mvpsaraiva** [comment]
I thought it would be good to include this in v0.3-0. I have added population and schools data from 2019.

Population:
![image](https://user-images.githubusercontent.com/7387691/100885668-acdd0400-3491-11eb-834f-c7ac741d87ec.png)

Schools:
![image](https://user-images.githubusercontent.com/7387691/100885762-c67e4b80-3491-11eb-859b-a562c887a346.png)

**Comment by rafapereirabr** [comment]
this is great. Thanks  Marcus!
