### ISSUE TITLE
migration from Travis CI to CMD Check Github Actions

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#133]
I started the migration from Travis CI to using CMD Check from Github Actions using [these simple steps](https://deanattali.com/blog/migrating-travis-to-github/). It worked fine for the [gtfs2gps](https://github.com/ipeaGIT/gtfs2gps) package, but it's no working in r5r. This seems to be occur because we our R package in located in a sub-directory.

ps. The [xgboost](https://github.com/dmlc/xgboost/tree/master/.github/workflows) github repo has a similar structure so this give us a hint on what to do.

**Comment by dhersz** [comment]
The subdir related errors are gone. Now we have some rJava and sf related errors. I call it progress.

**Comment by dhersz** [comment]
Closed via https://github.com/ipeaGIT/r5r/commit/ce6547ee6d1198a42c19ba4c3b716e99640283b4

**Comment by rafapereirabr** [comment]
Thanks, Daniel !
