### ISSUE TITLE
Unable to replicate vignette example

### ISSUE THREAD

**Issue by vronizor** [ipeaGIT/r5r#146]
Hi,

I have tried to replicate the [Detailed Itineraries](https://ipeagit.github.io/r5r/articles/intro_to_r5r.html#detailed-itineraries) example from the vignette but I get an error from `rJava`. I am very unfamiliar with `rJava`, so not sure what is going on. Any suggestions welcome.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
library(data.table)
#> 
#> Attaching package: 'data.table'
#> The following objects are masked from 'package:dplyr':
#> 
#>     between, first, last
#> The following object is masked from 'package:purrr':
#> 
#>     transpose
library(tmap)
options(java.parameters = '-Xmx2G')
library(r5r)
#> Loading required namespace: rJava
#> Please make sure you have already allocated some memory to Java by running:
#>   options(java.parameters = '-Xmx2G')

data_path <- system.file("extdata/poa", package = "r5r")
list.files(data_path)
#> [1] "network.dat"                "poa_hexgrid.csv"           
#> [3] "poa_osm.pbf"                "poa_osm.pbf.mapdb"         
#> [5] "poa_osm.pbf.mapdb.p"        "poa_points_of_interest.csv"
#> [7] "poa.zip"

poi <- fread(file.path(data_path, "poa_points_of_interest.csv"))
head(poi)
#>                     id       lat       lon
#> 1:       public_market -30.02756 -51.22781
#> 2: bus_central_station -30.02329 -51.21886
#> 3:    gasometer_museum -30.03404 -51.24095
#> 4: santa_casa_hospital -30.03043 -51.22240
#> 5:            townhall -30.02800 -51.22865
#> 6:     piratini_palace -30.03363 -51.23068

points <- fread(file.path(data_path, "poa_hexgrid.csv"))
points <- points[ c(sample(1:nrow(points), 10, replace=TRUE)), ]
head(points)
#>                 id       lon       lat population schools
#> 1: 89a9012859bffff -51.21737 -30.08625        649       0
#> 2: 89a9012a06bffff -51.21220 -30.10886        473       0
#> 3: 89a90128277ffff -51.17358 -30.05670          0       0
#> 4: 89a90128503ffff -51.21703 -30.07796        738       0
#> 5: 89a90128623ffff -51.18042 -30.07553        928       0
#> 6: 89a901286cfffff -51.16863 -30.08486        271       0

r5r_core <- setup_r5(data_path = data_path, verbose = FALSE)
#> Using cached version from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/r5r/jar/r5-v6.0.1-2-gf44e585-all.jar
#> 
#> Using cached network.dat from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/r5r/extdata/poa/network.dat

origins <- poi[10,]
destinations <- poi[12,]
mode <- c("WALK", "TRANSIT")
max_walk_dist <- 10000
departure_datetime <- as.POSIXct("13-05-2019 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

# calculate detailed itineraries
dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = origins,
                            destinations = destinations,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = FALSE,
                            verbose = FALSE)
#> Error in rJava::.jcall(jdx.j2r, "I", "initialize", rJava::.jcast(value, : java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror

head(dit)
#> Error in head(dit): object 'dit' not found
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by rafapereirabr** [comment]
Hi @vronizor . Quick comments:

1. Please make sure all packages are updated. Close R, and then try it again from a fresh session.
2. Are you able to reproduce the example of the `travel_time_matrix()` function?
3. What output do you get when you run `rJava::.jcall("java.lang.System","S","getProperty","java.version")` ?

**Comment by vronizor** [comment]
Hi @rafapereirabr, thank you for the comments, see my answers below.

1. Did a fresh update of R and all packages this morning, rebooted my machine too.
2. Running `travel_time_matrix()` gives me the exact same error.
3. I have version 15.0.1.

**Comment by vronizor** [comment]
Checked the vignette again and saw that `r5r` requires Java SE Development Kit **11.0.8**. On top of 15.0.1, I have OpenJDK 11.0.9 installed as well: does it have to be (1) 11.08 exactly? (2) the Oracle version? Do I have to make R point to the 11.0.9 version? How could I do that?

**Comment by rafapereirabr** [comment]
Ok, so it seems the problem is the Java installation, not the `r5r` package. We've tested `r5r` with other versions of JDK higher than 11.0.8 and it worked fine, so I'm not sure what could be causing this. Perhaps @mvpsaraiva migh have an idea, as he is our Java expert.

**Comment by mvpsaraiva** [comment]
Hi @vronizor. As @rafapereirabr said, it all points to a problem with Java and/or rJava. 
Before we try something else, can you check which R version you are using? rJava is known for having some issues with R 4.0.0, and updating R to 4.0.2 usually fixes it.

**Comment by vronizor** [comment]
Thanks @rafapereirabr. Hi @mvpsaraiva, I'm running R version 4.0.4 (2021-02-15), just updated it this morning along with all the packages.

**Comment by mvpsaraiva** [comment]
I've just installed Java 15 on my computer, and the example didn't work. So, it looks like R5 only works with some versions of Java higher than 11, but not all. 
Changing the active java version depends on your OS. Which one are you using?
An alternative, if you're not using Java 15 for anything else, is just uninstall it and leave Java 11 as default.

**Comment by vronizor** [comment]
Thanks a lot @mvpsaraiva, removing Java 15 did the trick. I don't remember precisely why I had Java, but for future reference, are you aware if there is a way to point `rJava` to a different version than latest? Thanks again!

**Comment by mvpsaraiva** [comment]
I'm glad it worked, @vronizor. Thanks for bringing our attention to this issue. We'll run some more tests using different versions of Java.

On macOS, you can follow this guide to change the active Java version:
[Switching Java (JDK) Versions on MacOS](https://medium.com/@devkosal/switching-java-jdk-versions-on-macos-80bc868e686a)
