### ISSUE TITLE
Max transfers vs max rides

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#148]
Right here it looks like maxRides gets set to maxTransfers: https://github.com/ipeaGIT/r5r/blob/master/java-r5rcore/src/org/ipea/r5r/R5RCore.java#L742

maxRides should actually be one more than max transfers (4 rides have three transfers between them).

**Comment by mattwigway** [comment]
I think this actually does not affect results, because the same error in the other direction is here and they cancel each other out: https://github.com/ipeaGIT/r5r/blob/master/r-package/R/utils.R

**Comment by mvpsaraiva** [comment]
Thanks for pointing this out. This is actually a naming mistake in our Java class. R5 takes a maxRides parameter, and r5r has a max_rides parameter that's passed through  Only our Java R5RCore class, in the middle, that calls it maxTransfers.

I plan to do some refactoring soon, to fix these kinds of mistakes and add some proper documentation to the code as well.
