### ISSUE TITLE
Document why travel_time_matrix might not always return the expected number of values

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#149]
I've noticed that travel_time_matrix returns a data frame with less than the expected number of rows (for instance, for a 5x3956 matrix, I'm only ending up with 1335 rows). I'm assuming this is because of origins/destinations that were beyond the maximum travel time, and/or origins that were far from the street network (I'm likely to have a good number of both of these in my dataset). If this is in fact the reason, it should be documented in `?travel_time_matrix`.

**Comment by rafapereirabr** [comment]
Thanks for the suggestion, Matt. I've added this info to the function documentation.
