### ISSUE TITLE
Java memory allocation

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#15]
By default, R allocates only 512MB of memory for Java processes, which is not enough for large queries using r5r.

To increase available memory to 10GB, for example, we need to set the java.parameters option as follows:

`options(java.parameters = "-Xmx10G")`

Ideally, memory size should be passed as a parameter to the setup_r5 function, so it can be passed along to the .jinit function. However, this does not seem to work, at least in RStudio. It also does not work in RStudio markdown documents. In my tests, it only worked when set as the very first line in an R script, and running on a fresh R session.

For now, the only solution I can think of is letting people know in the package's readme file that they need to set the -Xmx parameter at the beginning of their scripts.

**Comment by rafapereirabr** [comment]
I've added this info to the README and intro Vignette.
