### ISSUE TITLE
Test r5r on different versions of Java Virtual Machine

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#152]
R5 is build on Java 11, so it doesn't work on older versions of the Java Virtual Machine. We need to carry out more tests on newer versions of the JVM to check the package's compatibility. For example, recently we found out the package doesn't work with JVM version 15 (issue #146).

**Comment by rafapereirabr** [comment]
I believe we could simply things and simply require JDK 11. No other versions

**Comment by mvpsaraiva** [comment]
> I believe we could simply things and simply require JDK 11. No other versions

I agree. I'm closing this issue now.
