### ISSUE TITLE
r5r always uses first column as id

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#154]
I have an sf POINT object with an `id` column, but the returned travel time matrix from r5r has `fromId` and `toId` columns which have values taken from the first column of my sf POINT object, which happens to be land area in my case.

**Comment by rafapereirabr** [comment]
Thanks for the heads up, @mattwigway. I've included a line of code fixing this. See #b85eebeff7b7352a81edbc636a609d8be8fd7d84

**Comment by rafapereirabr** [comment]
@mattwigway , just so you know. I wanted to fix this quickly because we are planning to get the a new update of `r5r` or CRAN by the time our paper comes out published.
