### ISSUE TITLE
pkgdown website not reading the updated README file

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#156]
@dhersz , could you pleave have a look into this? No hurry.

**Comment by dhersz** [comment]
You gotta update `index.md` inside the `r-package` folder.

**Comment by rafapereirabr** [comment]
If I update the `index.md`, will the `README` file be automatically updated? Or should I manually update both?

**Comment by dhersz** [comment]
> If I update the `index.md`, will the `README` file be automatically updated? Or should I manually update both?

It won't. I can think of two alternatives here. We either add a pre-commit hook to make sure that `r-package/index.md` has been modified more recently than `README.md`, or create a GitHub Action to update `r-package/index.md` upon `README.md` modifications.

**Comment by rafapereirabr** [comment]
The second option sounds better, but not sure if it's easier to implement

**Comment by LStrachan** [comment]
Would you be able to share that workflow file to see how to implement this GitHub action to update the index file?

**Comment by dhersz** [comment]
Sure, here it is: https://github.com/ipeaGIT/r5r/blob/e271645244270813dd53b2529d9f3930dbb16181/.github/workflows/pkgdown.yaml#L61-L65

I've linked to the most relevant steps, as the rest is pretty similar to an usual pkgdown workflow.

**Comment by LStrachan** [comment]
Amazing! Thanks so much!
