### ISSUE TITLE
Test with openjdk on Windows

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#157]
# Test using [openjdk v15.0.2](https://jdk.java.net/15/).

This is the ERROR message I got.

>  Error in rJava::.jcall(jdx.j2r, "I", "initialize", rJava::.jcast(value,  : 
>   java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror 

### Reprex
```R
library(r5r)

# set up
data_path <- system.file("extdata/spo", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)

# input
points <- read.csv(file.path(data_path, "spo_hexgrid.csv"))[1:5,]
departure_datetime <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")

#' # estimate travel time matrix
ttm <- travel_time_matrix(r5r_core,
                   origins = points,
                   destinations = points,
                   mode = c("WALK", "TRANSIT"),
                   departure_datetime = departure_datetime,
                   max_walk_dist = Inf,
                   max_trip_duration = 120L)

```

**Comment by rafapereirabr** [comment]
# Test using [openjdk v11](https://jdk.java.net/java-se-ri/11).

It works like a charm.

**Comment by mvpsaraiva** [comment]
I believe it doesn't work on JDK 15, as in issue #146
Also, I haven't found JDK's 12 to 14 to download, so I believe we'll have to bind r5r to JDK 11.

**Comment by rafapereirabr** [comment]
I'm changing the `r5r` message. Does it look Ok ?

```
   if (ver < 11){stop("This package requires the Java SE Development Kit 11.
                        Please update your Java installation. The jdk 11 can be
                        downloaded from either:
                         - openjdk: https://jdk.java.net/java-se-ri/11
                         - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html")}
```

**Comment by mvpsaraiva** [comment]
I think it's much better now. But, I believe we should test `if (ver != 11)`, instead of `<`

**Comment by dhersz** [comment]
I suggest changing it to this format (otherwise it will get formatted pretty strangely on the console, copy and paste the bit above to see):

```r
if (ver < 11){
  stop(
       "This package requires the Java SE Development Kit 11.\n",
       "Please update your Java installation. The jdk 11 can be downloaded from either:\n",
       "  - openjdk: https://jdk.java.net/java-se-ri/11\n",
       "  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html"
   )
}
```

**Comment by rafapereirabr** [comment]
> I suggest changing it to this format (otherwise it will get formatted pretty strangely on the console, copy and paste the bit above to see):
> 
> ```r
> if (ver < 11){
>   stop(
>        "This package requires the Java SE Development Kit 11.\n",
>        "Please update your Java installation. The jdk 11 can be downloaded from either:\n",
>        "  - openjdk: https://jdk.java.net/java-se-ri/11\n",
>        "  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html"
>    )
> }
> ```

Oops. I had not seen this when I pushed to the repo. I'll update the the format suggested.

**Comment by rafapereirabr** [comment]
done
