### ISSUE TITLE
Fatal error when executing setup_r5

### ISSUE THREAD

**Issue by gerzhoy** [ipeaGIT/r5r#159]
When running setup_r5, I've consistently gotten the following error:

```
Error in rJava::.jnew("org.ipea.r5r.R5RCore", data_path, verbose) : 
  java.lang.NullPointerException: Cannot read field "transitLayer" because "this.transportNetwork" is null
```

To confirm that there was nothing wrong with the .pbf file I was using, I tried to replicate the code in the vignette. Even just running the following lines results in the error above:

```
path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path = path, verbose = FALSE)
```

I'm running MacOs 11.2 on an M1 MacBook Air. I installed the Java SE Development Kit 16, and I started the code by running:

`options(java.parameters = "-Xmx2G")
`

Any help troubleshooting would be appreciated!

**Comment by rafapereirabr** [comment]
Hi @gerzhoy. Thank you for opening this issue. I suspect this is related to your Java version. We know for sure `r5r`works with Java SE Development Kit 11. I would suggest you install jdk 11 and check if the problem persists. The jdk 11 is freely available from the options below:
- [OpenJDK](http://jdk.java.net/java-se-ri/11)
- [Oracle](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html)

**Comment by gerzhoy** [comment]
That solved it, thank you!
