### ISSUE TITLE
Update v0.4.0 on CRAN

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#161]
Package on its way to CRAN

**Comment by rafapereirabr** [comment]
1st feedback just came in:

> Thanks,
> 
> Please add \value to .Rd files regarding exported methods and explain
> the functions results in the documentation. Please write about the
> structure of the output (class) and also what the output means. (If a
> function does not return a value, please document that too, e.g.
> \value{No return value, called for side effects} or similar)
> Missing Rd-tags:
>       download_metadata.Rd:  \value
>       select_mode.Rd: \value
>       set_max_lts.Rd: \value
>       set_max_rides.Rd: \value
>       set_max_street_time.Rd: \value
>       set_n_threads.Rd: \value
>       set_speed.Rd: \value
>       set_suboptimal_minutes.Rd: \value
>       set_verbose.Rd: \value
>       stop_r5.Rd: \value
> 
> 
> Please use either \dontrun{} or if(interactive){} to wrap example but
> not both.
> 
> When creating the examples please keep in mind that the structure
> would be desirable:
> \examples{
>     examples for users and checks:
>     executable in < 5 sec
>     \dontshow{
>         examples for checks:
>         executable in < 5 sec together with the examples above
>         not shown to users
>     }
>     \donttest{
>         further examples for users; not used for checks
>         (e.g. data loading examples, or time consuming functions )
>     }
>     \dontrun{
>      not used by checks, not used by example()
>      adds the comment ("# Not run:") as a warning for the user.
>      cannot run (e.g. because of missing additional software,
>      missing API keys, ...)
>     }
>     if(interactive()){
>         functions not intended for use in scripts,
>         or are supposed to only run interactively
>         (e.g. shiny)
>     }
> }
> 
> Additionally:
> Have the issues why your package was archived been fixed?
> Please explain this in the submission comments.
> 
> Please fix and resubmit.
> 
> Best,
> Julia Haider

**Comment by rafapereirabr** [comment]
Things to do:

- [ ] Do not export functions in `utils.R`
- [ ] Explain that we use both  `\dontrun{}` AND `if(interactive){}` because these functions depend on local installation of a Java version that is not available on all CRAN machines
- [ ] Explain that we have solved previous issues: fixing issue with LazyData and internet connection checks.

**Comment by mvpsaraiva** [comment]
I think we can remove the `\dontrun{}` from the examples, since the `if(interactive){}` alone should fix the issue. I can do this now. @

**Comment by rafapereirabr** [comment]
Ok. Package resubmitted

**Comment by rafapereirabr** [comment]
We're back on [CRAN](https://cran.r-project.org/web/packages/r5r/index.html) with 0.4.0
