### ISSUE TITLE
detailed_itineraries function total_duration

### ISSUE THREAD

**Issue by franciscopasqual** [ipeaGIT/r5r#162]
When using the detailed_itineraires function, the outputs at the total_duration columns are different of the travel times obtained with the travel_time_matrix function. I'm calculating only for mode='car', so just interested in the shortest path.

mode <- c("WALK", "TRANSIT", "CAR")
max_walk_dist <- 5000
max_trip_duration <- 120
departure_datetime <- as.POSIXct("05-04-2021 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

ttm_car <- travel_time_matrix(r5r_core = r5r_core,
                              origins = udh,
                              destinations = universidades,
                              mode = "car",
                              departure_datetime = departure_datetime,
                              max_walk_dist = max_walk_dist,
                              max_trip_duration = max_trip_duration,
                              verbose = FALSE)

origins <- udh[158,]
destinations <- universidades[3,]

# calculate detailed itineraries
dit_2021 <- detailed_itineraries(r5r_core = r5r_core,
                            origins = origins,
                            destinations = destinations,
                            mode = "car",
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = FALSE,
                            verbose = FALSE)

For the same OD pair, I get travel_time = 7 (travel_time_matrix) and total_duration = 9.6 (detailed_itineraires) and so on...

**Comment by rafapereirabr** [comment]
Franciso, the two functions use different routing algorithms (see functions documentation for details), so some differences are expected to happen.

If you could calculate the difference between the results and run a `summary()`, we would be able to see how large are those differences

**Comment by rafapereirabr** [comment]
@franciscopasqual , have you had a chance of looking into this?

**Comment by franciscopasqual** [comment]
Hi @rafapereirabr yes, I did. I didn't run the summary function but decided to proceed using only the ttm function that already works well for my needs. Thanks for your support!
