### ISSUE TITLE
Error when running `setup_r5` without internet connection

### ISSUE THREAD

**Issue by jamaps** [ipeaGIT/r5r#163]
Hi there!  Great work overall on this library. It's been super helpful for some of my own work.

I'm currently trying to setup R5R on a server without internet for the first time (in order to link with individual level data) and I'm running into the following error:

```
> r5r_core <- setup_r5(data_path = "data", verbose = FALSE)
Error in curl::curl_fetch_memory(url, handle = handle) :
  Failed to connect to www.ipea.gov.br port 443: Bad access
```

Is there a way to bypass this connection check. I don't think I should need to connect to anything since I already have all my input data stored locally. But I might be misunderstanding what this connection is for.

Thanks!

**Comment by mvpsaraiva** [comment]
Hi @jamaps. 

The first time you run `setup_r5`, it downloads R5's Jar file from our server. Since that file has 46MB, it can't be included directly in the package on CRAN. Technically, you can manually copy the `r5-v6.2-all_20210408.jar` file from a working installation of `r5r` to the `jar` folder in your server.

**Comment by jamaps** [comment]
Super, thanks! I'll give that a try.

**Comment by mvpsaraiva** [comment]
Hi @jamaps. Checking into this issue, we found out that `setup_r5` still tried to download a metadata file from our server, and didn't work when no internet connection was available. I've added the required file to the repository so there is a backup version to use when running offline.

If you install the latest development version from GitHub, it should work offline. You still need to manually copy the main R5 jar (`r5-v6.2-all_20210408.jar`).

**Comment by jamaps** [comment]
Thanks @mvpsaraiva! got it working by manually copying in the R5 jar file as suggested.

**Comment by mvpsaraiva** [comment]
I'm glad it works! 
Thanks for using our package.

**Comment by hasanglr** [comment]
Hello, I couldn't find the jar file on the repository. Where can I access it?

**Comment by hasanglr** [comment]
It is 1.1.0

**Comment by rafapereirabr** [comment]
Ok, this version of r5r v1.1.0 uses R5 V6.9. Here's the link to the JAR file. [https://github.com/conveyal/r5/releases/download/v6.9/r5-v6.9-all.jar](https://github.com/conveyal/r5/releases/download/v6.9/r5-v6.9-all.jar)

**Comment by hasanglr** [comment]
Many thanks - that solved the issue.
