### ISSUE TITLE
calculate distance

### ISSUE THREAD

**Issue by alf-ken** [ipeaGIT/r5r#165]
Hallo,

is it possible to calculate travel distances? If not, it would be a nice feature for future releases!

Thx

Chris

**Comment by mvpsaraiva** [comment]
Hi @alf-ken 

Thanks for your feedback. The `detailed_itineraries()` function provides the travel distance per trip segment. However, R5 optimizes for travel time and not distance, so a faster trip may actually follow a longer path. Also, `detailed_itineraries()` only works on a one-to-one origin-destination basis. 
If you need a matrix of travel distances along the street network, there are better options available, such as [dodgr](https://github.com/atfutures/dodgr).

Best,
Marcus

**Comment by alf-ken** [comment]
Dear Marcus,

thank you wer much! I will try it.

Chris
