### ISSUE TITLE
setup_r5 should be able to load an existing network.dat

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#17]
`setup_r5` should be able to load to memory a `network.dat` if it already exists in the directory. @mvpsaraiva, what is function can we use to load a `network.dat` to memory?

**Comment by mvpsaraiva** [comment]
The r5r_core object loads the network.dat file in memory when it is created, in this line:
`r5r_core <- rJava::.jnew("com.conveyal.r5.R5RCore", data_path)`

The way I designed it, the r5r_core object cannot exist without being associated to a network. 
Did I understand your question correctly?

**Comment by rafapereirabr** [comment]
That's excatly what I needed to know. I'll work on this issue next

**Comment by rafapereirabr** [comment]
Done. Now `setup_r5` detects wheter there is a network.dat and loads it to memory
