### ISSUE TITLE
ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.

### ISSUE THREAD

**Issue by temospena** [ipeaGIT/r5r#170]
Hi,
This is an awesome package! It is saving me days of work when looking for time and distance for thousands of OD points. Great job! 👍 

I am using a r5r_core with only OSM.pfb, and **no** transit layers. It runs fine for walking and bike modes.
I run it for a couple thousand OD pais, but I want to do it for a 1.4 million different points, and not necessarily both ways or all to all - a matrix do not give me the distance, only time. So I thought putting it into a routine and track the progress over some hours (or few minutes :).
But although I am aware of that, the `detailed_itineraries()` insistis telling me that _TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT_.

I am having an annoying error message every time I compute `detailed_itineraries()` - **2** per OD -, and I wonder if there is a way to shut up this error messages... ? Maybe providing another option in `verbose = ...`

Here is an example:
``` r
setwd("D:/GIS/R5R")

library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
library(r5r)
#> Loading required namespace: rJava
#> Please make sure you have already allocated some memory to Java by running:
#>   options(java.parameters = '-Xmx2G').
#> Currently, Java memory is set to -Xmx512m
options(java.parameters = '-Xmx5G') #memory 5GB

r5r_core = setup_r5(data_path = "data/")
#> Using cached version from C:/Users/Utilizador/Documents/R/win-library/4.0/r5r/jar/r5-v6.2-all_20210408.jar
#> 
#> Using cached network.dat from data//network.dat

ORIGENS_porviagem = readRDS("ORIGENS_porviagem.Rds") #1407380 points
DESTINOS_porviagem = readRDS("DESTINOS_porviagem.Rds")

departure_datetime <- as.POSIXct("19-05-2021 08:45:00", format = "%d-%m-%Y %H:%M:%S")
departure_datetime = lubridate::force_tz(departure_datetime, "WET") #make it western european time

dit = data.frame(matrix(nrow = nrow(ORIGENS_porviagem), ncol = 14))
names(dit) = c("fromId", "fromLat", "fromLon", "toId", "toLat", "toLon", "option", 
               "segment", "mode", "total_duration", "segment_duration", "wait", 
               "distance", "route")

for (i in 1:3){ #running only for the first 3 OD pairs
  dit[i,] <- detailed_itineraries(r5r_core = r5r_core,
                                  origins = ORIGENS_porviagem[i,],
                                  destinations = DESTINOS_porviagem[i,],
                                  mode = "WALK",
                                  departure_datetime = departure_datetime,
                                  max_walk_dist = Inf,
                                  max_trip_duration = 500,
                                  shortest_path = TRUE,
                                  drop_geometry = TRUE,
                                  verbose = FALSE)
  # pb$tick()
  # Sys.sleep(1 / 100)
}
```
[console]
18:21:12.553 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
18:21:12.553 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
18:21:12.747 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
18:21:12.747 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
18:21:12.883 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
18:21:12.883 [main] ERROR c.c.r5.transit.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.

<sup>Created on 2021-05-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.4 (2021-02-15)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Portuguese_Portugal.1252    
#>  ctype    Portuguese_Portugal.1252    
#>  tz       Europe/London               
#>  date     2021-05-16                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source                       
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)               
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.0.3)               
#>  checkmate     2.0.0   2020-02-06 [1] CRAN (R 4.0.3)               
#>  class         7.3-18  2021-01-24 [2] CRAN (R 4.0.4)               
#>  classInt      0.4-3   2020-04-07 [1] CRAN (R 4.0.3)               
#>  cli           2.5.0   2021-04-26 [1] CRAN (R 4.0.5)               
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.4)               
#>  curl          4.3.1   2021-04-30 [1] CRAN (R 4.0.4)               
#>  data.table    1.14.0  2021-02-21 [1] CRAN (R 4.0.4)               
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.3)               
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)               
#>  dplyr         1.0.5   2021-03-05 [1] CRAN (R 4.0.4)               
#>  e1071         1.7-6   2021-03-18 [1] CRAN (R 4.0.4)               
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.4)               
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.3)               
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.3)               
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)               
#>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.3)               
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)               
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.0.5)               
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)               
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.3)               
#>  jdx           0.1.4   2020-06-04 [1] CRAN (R 4.0.4)               
#>  KernSmooth    2.23-18 2020-10-29 [2] CRAN (R 4.0.4)               
#>  knitr         1.33    2021-04-24 [1] CRAN (R 4.0.5)               
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)               
#>  lubridate     1.7.10  2021-02-26 [1] CRAN (R 4.0.4)               
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)               
#>  pillar        1.6.0   2021-04-13 [1] CRAN (R 4.0.5)               
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)               
#>  proxy         0.4-25  2021-03-05 [1] CRAN (R 4.0.4)               
#>  ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.4)               
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)               
#>  r5r         * 0.4.0   2021-05-14 [1] Github (ipeaGIT/r5r@0afa612) 
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)               
#>  Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.3)               
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.0.5)               
#>  rJava         1.0-4   2021-04-29 [1] CRAN (R 4.0.4)               
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)               
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.4)               
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)               
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)               
#>  sf          * 0.9-9   2021-03-30 [1] Github (r-spatial/sf@b0e733d)
#>  sfheaders     0.4.0   2020-12-01 [1] CRAN (R 4.0.3)               
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.3)               
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.3)               
#>  tibble        3.1.1   2021-04-18 [1] CRAN (R 4.0.5)               
#>  tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.0.4)               
#>  units         0.7-1   2021-03-16 [1] CRAN (R 4.0.4)               
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.4)               
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.0.4)               
#>  withr         2.4.2   2021-04-18 [1] CRAN (R 4.0.5)               
#>  xfun          0.22    2021-03-11 [1] CRAN (R 4.0.4)               
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)               
#> 
#> [1] C:/Users/Utilizador/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.4/library
```

</details>

**Comment by mvpsaraiva** [comment]
Hi @temospena. Thanks for the feedback!

I've looked into this and found this is an issue upstream in R5 and I cannot fix it from our side in r5r. I can remove one of the error messages, but the second one is too deep into R5's codebase. It's a very simple fix, so I'll be making a pull request to Conveyal. Obviously, it can take a long time until they are able to check the pull request and release a new version of R5 with that change, if they accept it. We'll also think about the suggestion to improve the `verbose` parameter, but we rather keep it as a simple `TRUE/FALSE` input for now.

Meanwhile, I've found a workaround. You can put any gtfs file inside the folder with the pbf, even if it's from another city, and that message will disappear. It shouldn't affect your results, since you're not searching for transit routes. I've did some tests here, and it all worked. Just remember to delete the network.dat file from the folder before calling `setup_r5()` again, so the network can be rebuilt with the "fake" gtfs inside.

Now, just a few tips for your code. First, you have the line `options(java.parameters = '-Xmx5G')` after the `library(r5r)` call, but it should be the other way around. Always set the memory limit before loading the library, or that setting will have no effect. I've also seen that you've put the `detailed_itineraries()` call inside a for loop, in order to track it's progress. I guess this is the only way to do this for now, before we can implement some sort of progress bar directly into r5r, but be aware that this is way slower than passing the entire set of OD points to r5r so it can run the queries in parallel.

I hope this helps.

**Comment by temospena** [comment]
Hi @mvpsaraiva, thank you for your suggestions!

> You can put any gtfs file inside the folder with the pbf, even if it's from another city, and that message will disappear.
That is a good workaround 😸 

> Always set the memory limit before loading the library, or that setting will have no effect.
I didn't know that, thanks!

**Comment by rafapereirabr** [comment]
This problem is already in [Conveyal's to do list](https://github.com/conveyal/r5/issues/607). However, it make take a while for them to fix this. One alternative would be to have something like a 'null island' GTFS that r5r can use in cases when the user points to a directory with no GTFS.zip file.

**Comment by rafapereirabr** [comment]
this problem has been fixed. One can use r5r simply with OSM data (without any GTFS feed). R5 will print messages indicating it did not find any GTFS, but it won't stop users from running anlysis by walking, cycling and car

**Comment by caldeiraga** [comment]
Hi guys,

I'm trying to estimate travel time matrices for some cities and I'm using r5r, especifically the function _travel_time_matrix_, but I'm having the same problem with the error message output. I'm routing only walking trips. I'm using the last version of r5r (1.1.0). See the code below.

`
rm(list = ls())

options(java.parameters = "-Xmx20G")

# Library
library(tidyverse)
library(r5r)
library(sf)

# define pasta de trabalho 
dir_proj <- here::here()

# pasta de dados
dir_rede <- file.path(dir_proj, "datasets/intermediate/malha_viaria")

# departure time
departure_datetime <- as.POSIXct("05-11-2023 14:00:00", 
                                 format = "%d-%m-%Y %H:%M:%S")

# Function -------
ttm <- function(mode,city,code_muni,max_duration,n_threads,walk_speed) {
  
  mun_short <- unique(centroid$mun_short[centroid$code_muni==code_muni])
  
  r5r_core <- setup_r5(data_path = file.path(dir_rede,'OSM',mun_short),
                       verbose = F,temp_dir = F,overwrite = F)
  
  ttm <- travel_time_matrix(r5r_core = r5r_core,
                            origins = city,
                            destinations = city,
                            mode = mode,
                            max_trip_duration = max_duration,
                            n_threads = n_threads,
                            walk_speed = walk_speed,
                            departure_datetime = departure_datetime,
                            progress = F,
                            verbose = F)
  
  return(ttm)
  
}

# READ DATA -----
centroid <- st_read(dsn = 'datasets/intermediate/hex.centroid.gpkg') %>% 
  mutate(mun_short = str_replace_all(name_muni, " ", "_")) %>% 
  rename(id = h3_address)

code_city = unique(centroid$code_muni)

# A pé ----
matrix.hex <- list()

for (i in seq_len(length.out = length(code_city))) {
  
  matrix.hex[[i]] <- ttm(mode = c('WALK'),
                          city = centroid[centroid$code_muni==code_city[i],],
                          code_mun = code_city[i],
                          max_duration = 15, walk_speed = 3.6,
                          n_threads = 9)
  
}

df_matrix <- do.call(what = rbind.data.frame,args = matrix.hex) %>% 
  rename(tt_ape15=travel_time_p50)

write_rds(x = df_matrix,file = 'datasets/intermediate/ttm/tm_ape.rds')
`

I'm also attaching part of the data so you can reproduce the code. Thank you in advance.

[r5r.zip](https://github.com/ipeaGIT/r5r/files/13309822/r5r.zip)

**Comment by rafapereirabr** [comment]
Hi @caldeiraga. Thansk for sharing your sample data. I was able to run the analysis and get the output travel time matrix without a problem using the code below.

```
options(java.parameters = '-Xmx4G')
library(r5r)

data_path <- '.'
r5r_core <- setup_r5(data_path, verbose = T)

# load origin/destination points
points <- sf::st_read('../centroid_r5r.gpkg')

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

t1 <- travel_time_matrix(
  r5r_core,
  origins = points,
  destinations = points,
  mode = "walk",
  departure_datetime = departure_datetime,
  max_trip_duration = 30
)

head(t1)

```

The thing is, `R5` prints lots of messages with the word `ERROR` in them (see example below) even though these are not errors but simply warnings. Unfortunately, we haven't been able to supress these messages yet. 

> 2023-11-10 11:22:35,476 [ForkJoinPool.commonPool-worker-9] ERROR c.c.r.t.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.
