### ISSUE TITLE
Add new max_bike_dist

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#174]
Our routing and accessibility functions have a `max_walk_dist` parameter. I was wondering whether if would make sense to include also a `max_bike_dist` parameter. What do you think?

**Comment by mvpsaraiva** [comment]
I agree it would be useful for calculating trips that combine bike with public transport. Currently, we set R5's `maxBikeTime` parameter to `max_trip_duration`. The problem with that approach is that we cannot force someone to bike a short distance to a transit station and then catch a train, for example. The traveller will always try to cycle for as long as `max_trip_duration` allows.

**Comment by rafapereirabr** [comment]
> The problem with that approach is that we cannot force someone to bike a short distance to a transit station and then catch a train, for example. The traveller will always try to cycle for as long as max_trip_duration allows.

Even if it would be faster to cycle to the nearest train station and then get to train to the final destiantion (comparted to cycling the whole way) ?

**Comment by mvpsaraiva** [comment]
> Even if it would be faster to cycle to the nearest train station and then get to train to the final destiantion (comparted to cycling the whole way) ?

If it's faster to take the train, then the traveller will take it. What we can't do now is force the traveller to only consider train stations that are a certain distance away from home. 
I think this parameter is quite useful, and I will add it to the `jar` soon.

**Comment by rafapereirabr** [comment]
> > Even if it would be faster to cycle to the nearest train station and then get to train to the final destiantion (comparted to cycling the whole way) ?
> 
> If it's faster to take the train, then the traveller will take it. What we can't do now is force the traveller to only consider train stations that are a certain distance away from home.
> I think this parameter is quite useful, and I will add it to the `jar` soon.

Ok, I understand it. This is exactly how we would expect R5 or other routing enginge to behave fot that matter.

**Comment by rafapereirabr** [comment]
Setting this issue as priority, to be incorporated in the next package release.

**Comment by mvpsaraiva** [comment]
I've added this parameter to the `jar` and updated the `detailed_itineraries()`, `travel_time_matrix()` and `accessibility()` functions accordingly. I think the only thing missing now is to add this parameter to the tests.

**Comment by mvpsaraiva** [comment]
> I think the only thing missing now is to add this parameter to the tests.

I've added the tests now.

**Comment by rafapereirabr** [comment]
This is great. Thanks! I've updated the NEWs file and closed this issue in my last commit.

**Comment by rafapereirabr** [comment]
This issue should be closed once we merge the dev and master branches
