### ISSUE TITLE
pkgdown is not updating

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#177]
this is the error message on github actions:

```
Run R CMD INSTALL .
* installing to library ‘/Users/runner/work/_temp/Library’
ERROR: dependency ‘sf’ is not available for package ‘r5r’
* removing ‘/Users/runner/work/_temp/Library/r5r’
Error: Process completed with exit code 1.
```

@dhersz , anything we can do about this?

**Comment by dhersz** [comment]
I'll change this and the coverage action to run on Ubuntu, instead of macOS. This will probably fix this error for now - Ubuntu actions always install packages from source, so their dependency checks are more thorough.

**Comment by rafapereirabr** [comment]
great !

**Comment by dhersz** [comment]
Done here: https://github.com/ipeaGIT/r5r/commit/73d83303fadb56c3c9c16522cd785e0c78e73b6c
