### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by xtimbeau** [ipeaGIT/r5r#186]
Hi to all, thanks again for this package that gets better and better.
Using the last version, I can't find a way to stop all messages coming from Java, and setting verbose to false displays a counter that is not useful for me. Is there a way to do that ?

**Comment by mvpsaraiva** [comment]
Thanks for your feedback, @xtimbeau. We thought that the counter would be useful to everyone, but we were obviously mistaken :)

We'll add a new `progress` parameter in the next version of the package, so the users can decide what's best for them.

**Comment by mvpsaraiva** [comment]
I have added now a `progress` parameter to `travel_time_matrix()`, `accessibility()`, and `detailed_itineraries()` functions in the current development version of the package (`0.6-0`, available if you install from GitHub). If you call any of those functions with `verbose = FALSE, progress = FALSE`, you will get no console output apart from error messages. 

I hope this helps! Thanks for your feedback.

**Comment by rafapereirabr** [comment]
Thanks @mvpsaraiva ! I think we can close this issue for now.
