### ISSUE TITLE
Error in setup_r5: object 'path' not found

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#19]
Sometimes I get this error below when I test `setup_r5`. 

```
library(r5r)
library(covr)
library(testthat)

covr::function_coverage(fun=r5r::setup_r5, test_file("tests/testthat/test-setup_r5.R"))
```
> -- 1. Error: setup_r5 - expected behavior (@test-setup_r5.R#9)  --------
object 'path' not found
Backtrace:
> 1. testthat::expect_message(setup_r5(data_path = path))
> 6. r5r::setup_r5(data_path = path)
> 7. base::file.path(path, "network.dat")

**Comment by dhersz** [comment]
Should be working now (https://github.com/ipeaGIT/r5r/commit/1b4061b0825e5dd940cc01bcf29e2d7c8a086faa)

**Comment by rafapereirabr** [comment]
thanks!
