### ISSUE TITLE
clarify documentation of max_walking_dist and max_cycling _dist 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#193]

**Comment by rafapereirabr** [comment]
proposed documentation:

- `max_walk_dist` numeric. Maximum walking distance (in meters) to access and egress the transit network, or transfer within the network. The max distance is considered separately for each leg; e.g. if you set `max_walk_dist` to 1000, you could potentially walk up to 1 Km to reach transit, and up to _another_  1 Km to reach the destination after leaving transit. Obs. If you want to set the maximum walking distance considering walking-only trips you have to set the `max_trip_duration` accordingly (e.g. to set a distance of 1 km assuming a walking speed of 3.6 km/h you have to set `max_trip_duration` = 1 / 3.6 * 60

**Comment by dhersz** [comment]
Great work. I made some very small changes here, but I'm happy with any version you prefer:

* `max_walk_dist` numeric. Maximum walking distance (in meters) to access and egress the transit network, or to make transfers within the network. The max distance is considered separately for each leg; e.g. if you set `max_walk_dist` to 1000, you could potentially walk up to 1 km to reach transit, and up to _another_  1 km to reach the destination after leaving transit. Obs: if you want to set the maximum walking distance considering walking-only trips you have to set the `max_trip_duration` accordingly (e.g. to set a distance of 1 km assuming a walking speed of 3.6 km/h you have to set `max_trip_duration = 1 / 3.6 * 60`).

**Comment by rafapereirabr** [comment]
Thanks. I'll use your version.
