### ISSUE TITLE
detailed_itineraries - function missing a timeout limit

### ISSUE THREAD

**Issue by SRN1973** [ipeaGIT/r5r#196]
When I feed a lot ot origin-destination pairs to the detailed_itineraries function I always happen to have some connections to calculate that seem to slow down the overall calculation process quite dramatically (cause the function to run for a few minutes for a few connections out of the data-set). Do you think it would be possible to implement some kind of additional timeout parameter so that if one of the triggered parallel processes takes too long it is terminated automatically, and returns NULL?

**Comment by mvpsaraiva** [comment]
That's a very interesting feature, thanks for the suggestion. I'm not sure we can do this without some upstream changes in R5, but I'll take a look.

**Comment by rafapereirabr** [comment]
Unfortunately, this could only be done upstream in R5. If you like the feature, we'd recommend opening a request on R5 github repo.
