### ISSUE TITLE
Don't catch exceptions when loading network

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#202]
I'm getting the following error when I call `setup_r5`:

```
Using cached network.dat from /Users/mwbc/git/r5r/r-package/inst/extdata/poa/network.dat
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.NullPointerException: Cannot read field "transitLayer" because "this.transportNetwork" is null
```

I'm guessing that an error is being thrown in deserialization and it's getting [caught and silently ignored](https://github.com/ipeaGIT/r5r/blob/master/java-r5rcore/src/org/ipea/r5r/R5Network.java#L64) by this line. We should probably not catch exceptions here, and just let them propagate back to R.

**Comment by mvpsaraiva** [comment]
Thanks! I've changed this to propagate the exceptions when loading networks, instead of catching and ignoring them. I couldn't replicate the error, so please let me know if it's fixed.
