### ISSUE TITLE
Create a situation report function for easier debugging

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#204]
From a recent [rOpensci blog post](https://ropensci.org/blog/2021/09/30/ropensci-news-digest-september-2021/#package-development-corner):

> Have you also considered adding some sort of sitrep (situation report) function? The devtools package has devtools::dev_sitrep() e.g. reports on the package development situation, with clear hints given if something is not quite right. The usethis package has usethis::git_sitrep() (using the gert package under the hood!), blogdown has blogdown::check_site(). Good candidates for checks are common pain points, so finding them might require some sort of external perspective on your package.

`devtools::dev_sitrep()`, for example, reports:

> - If R is up to date
> - If RStudio is up to date
> - If compiler build tools are installed and available for use
> - If devtools and its dependencies are up to date
> - If the package's dependencies are up to date

We could include something similar to r5r, since we ask similar question in basically all our issues:

- Is r5r up to date?
- Is r5r's jar up to date?
- Is R5's jar up to date?

What are other questions we could try to answer with this function?

**Comment by dhersz** [comment]
Jar size as well.

**Comment by dhersz** [comment]
`path` argument could be used to list files inside router directory.

**Comment by rafapereirabr** [comment]
this issue has been fixed with the new `r5r_sitrep()` released in r5r v1.0.0
