### ISSUE TITLE
Timeout was reached: [www.ipea.gov.br] Connection timed out after 10002 milliseconds

### ISSUE THREAD

**Issue by manuelsantanap** [ipeaGIT/r5r#210]
Hi there,

When try to create the network.dat file using:

```
r5r_core <- setup_r5(data_path = nt_path, verbose = FALSE, temp_dir=TRUE)
```

I obtain this error:
>Error in curl::curl_fetch_memory(url, handle = handle) : 
>  Timeout was reached: [www.ipea.gov.br] Connection timed out after 10002 milliseconds

Any ideas what may be triggering it? It started occurring this morning (EST)

**Comment by manuelsantanap** [comment]
Okay, something's odd with calendar.txt I created for the GTFS I'm need to use (which has no calendar.txt, and all is stored in calendar_dates):

https://transitfeeds.com/p/milton-transit/929/20180708

I'll keep working on it.

**Comment by mvpsaraiva** [comment]
Hi @manuelsantanap. 

This seems to be related to a slow internet connection. You can increase the timeout limit using `options(timeout=120)`.
Also, when you use `temp_dir=TRUE` in `setup_r5()`, you're essentially re-downloading R5 each time you restart your R session, so it's better to set it to `FALSE` so your R5 copy is stored permanently into the package's folder.

**Comment by manuelsantanap** [comment]
Thanks
