### ISSUE TITLE
 Error when trying to load network using setup_r5 function

### ISSUE THREAD

**Issue by rafavdz** [ipeaGIT/r5r#211]
Dear R5R community, 

I get an error when I try to read/load the network as following: 

```
options(java.parameters = "-Xmx11G")
library(r5r)
library(sf)
library(data.table)
library(ggplot2)
library(mapview)

# Indicate the path where OSM and GTFS data are stored
r5r_core <- setup_r5(data_path = 'data/otp_test/', verbose = FALSE)
```

Which returns: 

> Error in curl::curl_fetch_memory(url, handle = handle) : Failed to connect to www.ipea.gov.br port 443: Connection refused

Any ideas on this?

**Comment by rafapereirabr** [comment]
Hi @rafavdz . I believe this is a temporary problem on our server. Could you please restart your R session and try it again?

**Comment by rafavdz** [comment]
Hi @rafapereirabr , Thanks for your reply. I restarted the R session. Also, I removed and re-installed `r5r`. However, I still get the same error. Any help would be greatly appreciated.

**Comment by rafapereirabr** [comment]
I've checked our servers and everything seems to be working fine. I suspect your network might be blocking the connection to our server. Could you please try doing this from another internet network? obs. Are you trying to do this connected to eduroam?

**Comment by rafavdz** [comment]
Hi @rafapereirabr . I was connected to an eduroam VPN. I disconnected it and didn't get the error. 

After that, it seems to be working fine even while I'm connected to the VPN. So, the problem is solved.

Many thanks for your help. Great package! :)

**Comment by rafapereirabr** [comment]
I'm glad to hear it worked out! Thanks for the feedback ! Closing the issue for now.
