### ISSUE TITLE
detailed_itineraries classes depend on nrows

### ISSUE THREAD

**Issue by botanize** [ipeaGIT/r5r#212]
When `drop_geometry = FALSE` (default), the class of the returned object (and the class of the geometry column) depends on the number of rows of the `path_options` object. 

If path_options is zero rows then the returned object is a data.table and the geometry field is `character`.

If path_options is one or more rows then the returned object is an sf object and the geometry field is `sfc_LINESTRING`.

This happens because the function returns early on line 333 when nrow == 0. 

To keep the classes of the returned objects and their columns consistent you'd need to do something like: 
```r
if (is.null(path_options)) {
  return(data.table::data.table(path_options))
} else {
  path_options <- java_to_dt(path_options)
  if (!is.data.frame(path_options)) {
    path_options <- data.table::rbindlist(path_options)
    # if (nrow(path_options) == 0) 
    #  return(path_options)
  }
}
if (nrow(path_options) == 0) {
  if (!drop_geometry) {
      path_options[, geometry := sf::st_sfc(sf::st_linestring(), crs = 4326)[0]]
      path_options <- sf::st_sf(path_options, crs = 4326)
  } 
  return(path_options)
}
```

**Comment by botanize** [comment]
I don't really know Java, but it looks like you might be able to do this more simply in the Java code for PathOptionsTable.java on line 95 you could set the default string to "LINESTRING EMPTY" instead of "".

https://github.com/ipeaGIT/r5r/blob/5743d27f71be1be09efed17bd53685f3d27537b3/java-r5rcore/src/org/ipea/r5r/PathOptionsTable.java#L95

**Comment by rafapereirabr** [comment]
> I don't really know Java, but it looks like you might be able to do this more simply in the Java code for PathOptionsTable.java on line 95 you could set the default string to "LINESTRING EMPTY" instead of "".
> 
> https://github.com/ipeaGIT/r5r/blob/5743d27f71be1be09efed17bd53685f3d27537b3/java-r5rcore/src/org/ipea/r5r/PathOptionsTable.java#L95

@mvpsaraiva , if we drop the geometry from within Java, would it reduce the overhead of passing the data from Java to R with `path_options <- java_to_dt(path_options)` ?

**Comment by rafapereirabr** [comment]
> botanize

Thank you @botanize . I've implemented this solution you suggested above. It will come into effect in the next update of r5r on CRAN.
