### ISSUE TITLE
Issue with Java SDK version. 

### ISSUE THREAD

**Issue by FrancyJGLisboa** [ipeaGIT/r5r#213]
r5r_core <- setup_r5(data_path = path, verbose = FALSE)
Error in setup_r5(data_path = path, verbose = FALSE) : 
  This package requires the Java SE Development Kit 11.
Please update your Java installation. The jdk 11 can be downloaded from either:
  - openjdk: https://jdk.java.net/java-se-ri/11
  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html

And I have:

(base) ➜  ~ java --version                  
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

Why the package cannot run on a newer JAVA JDK ?

**Comment by rafapereirabr** [comment]
Hi @FrancyJGLisboa . Thank you for opening this issue. Unfortunately, `r5r` does not work with newer versions of JAVA JDK due to upstream dependencies in R5. So there is not much we can do on `r5r`, unfortunately.
