### ISSUE TITLE
Error in FUN(X[[i]], ...) : java.lang.NullPointerException 

### ISSUE THREAD

**Issue by dellohio** [ipeaGIT/r5r#214]
When running transit accessibility calculation, I am facing this error:
Error in FUN(X[[i]], ...) : java.lang.NullPointerException
In addition: Warning messages:
1: In assert_points_input(origins, "origins") :
  'origins$id' forcefully cast to character.
2: In assert_points_input(destinations, "destinations") :
  'destinations$id' forcefully cast to character.
Before, I did not have this issue because I was able to calculate transit access for the same data files. But now if I run the transit access calculation from same file, I am having this issue. 
But car, bike and walk access calculation runs perfectly fine.
Could you please address this issue?
Thank you!

**Comment by rafapereirabr** [comment]
Hi @dellohio , this kind of error can occur when `departure_datetime` input is outside the period of reference in the GTFS `calendar.txt` file. Could you please check this info?

**Comment by dellohio** [comment]
Thank you! Yes, I checked the dates and it worked. But I have some confusion regarding selection of dates. For instance:

GTFS1: 12/10/2021 to 12/10/2022
GTFS2: 1/5/2021 to 11/10/2021

above are gtfs available for download. Since the date doesn't match if I select "12/10/2021" date then will the code ignore GTFS2? But I need the routes for both gtfs, and I am unable to download GTFS2 that matches date of GTFS1, in such cases what shall I do? Also, selecting weekdays and weekends date does affect access calculation or not?

**Comment by rafapereirabr** [comment]
In this case, you could manually change the calendar period in the GTFS.zip files to match the calendar of both files.
