### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException error for some locations when calling travel_time_matrix

### ISSUE THREAD

**Issue by nick-newstead** [ipeaGIT/r5r#219]
I am trying to calculate a travel time matrix for for a large number of points in Montreal using transit but run into the error: `Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :  java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15`. I've included a subset of points and the files that should reproduce the error.

Input files: 
- OSM PBF: https://download.geofabrik.de/north-america/canada-latest.osm.pbf bounded to the bbox (left=-73.985 bottom=45.39 right=-73.467 top=46.718)
- GTFS zip: https://www.stm.info/sites/default/files/gtfs/gtfs_stm.zip
- Points: [points.csv](https://github.com/ipeaGIT/r5r/files/7914497/points.csv)

The code: 
```
options(java.parameters = "-Xmx10G")

library(here)
library(r5r)
library(data.table)

data_path <- here("data", "montreal")

r5r_core <- setup_r5(data_path = data_path, verbose = TRUE)

points <- fread(file.path(data_path, "points.csv"), colClasses = list(character = "id"))

mode <- c("WALK", "TRANSIT")
max_walk_dist <- 1000
max_trip_duration <- 60
departure_datetime <- as.POSIXct("20-01-2022 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")
time_window <- 120

# calculate a travel time matrix
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = points[1],
                          destinations = points,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          time_window = time_window,
                          max_walk_dist = max_walk_dist,
                          max_trip_duration = max_trip_duration,
                          verbose = TRUE)
```
Verbose output and error:
```
09:54:54.418 [main] INFO  com.conveyal.r5.analyst.LinkageCache - Seeking linkage for (com.conveyal.r5.analyst.FreeFormPointSet@75699e35, StreetLayer(base), WALK) in cache...
09:54:54.420 [main] INFO  com.conveyal.r5.analyst.LinkageCache - Building Linkage for (com.conveyal.r5.analyst.FreeFormPointSet@75699e35, StreetLayer(base), WALK) because it was not found in cache.
09:54:54.420 [main] INFO  c.conveyal.r5.streets.LinkedPointSet - Linking pointset to street network...
09:54:54.428 [main] INFO  c.conveyal.r5.streets.LinkedPointSet - Done. Linked 91 of 91 PointSet points to streets.
09:54:54.428 [main] INFO  c.conveyal.r5.streets.LinkedPointSet -       0 of 91 point linkages were copied directly from a source linkage;
09:54:54.428 [main] INFO  c.conveyal.r5.streets.LinkedPointSet -       the remaining 91 linkages were refreshed, of which 0 changed;
09:54:54.428 [main] INFO  c.conveyal.r5.streets.LinkedPointSet -       of which 0 changed to added edges, 0 to baseline edges, and 0 became unlinked.
09:54:54.429 [main] INFO  c.c.r5.analyst.TravelTimeComputer - Performing street search for mode: WALK
09:54:54.429 [main] DEBUG com.conveyal.r5.streets.StreetRouter - Using time limit of 1020 sec
09:54:54.430 [main] DEBUG com.conveyal.r5.streets.StreetRouter - Routing took 1 msec
09:54:54.431 [main] INFO  com.conveyal.r5.analyst.LinkageCache - Seeking linkage for (com.conveyal.r5.analyst.FreeFormPointSet@75699e35, StreetLayer(base), WALK) in cache...
09:54:54.432 [main] INFO  c.c.r5.profile.FastRaptorWorker - Performing 600 total iterations (5 per minute); boarding MONTE_CARLO; frequencies true
09:54:54.432 [main] DEBUG c.c.r5.profile.FastRaptorWorker -   minute 120
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15
```
No error occurs if I simply use `mode <- "WALK"` but I am unable to deduce what the specific problem with the transit routing is. Any advice would be much appreciated.

Thanks!

**Comment by rafapereirabr** [comment]
Hi @nick-newstead . Your `departure_datetime` input points to the 20th of January 2021. However, the `calendar.txt` in your GTFS only covers services between `20211025` and `20211217`. Please, try fixing you `departure_datetime` input and let me know if it worked. This should do the trick.

**Comment by nick-newstead** [comment]
Hi @rafapereirabr, I see services covered up to `20220306` in the `calendar.txt`, is there something in particular that informs you that only the range of `20211025` and `20211217` is covered? That said, I did try changing the departure date to a date that falls in the range you specified. The travel time matrix is computed successfully for Saturdays in the range `2021105` to `20211218` however it raises the aforementioned error for any other day of the week in that range. Thanks again!

**Comment by rafapereirabr** [comment]
Hi @nick-newstead , I only looked at the first rows of `calendar.txt`, and there are indeed other time ranges. I'm not sure what could be happening. It could possibly be related to calendar exceptions but there must be something else. Perhaps @mvpsaraiva might have a hunch?

**Comment by mvpsaraiva** [comment]
Hi @nick-newstead 
I suspect this is a bug upstream in R5, related to frequencies GTFS. We came across similar errors before, and I will open an issue in R5 repository about this once we can gather more data on it.

Meanwhile, I've downloaded your data and got the same error here, and I was able to fix it by converting the GTFS from frequencies to stop_times using the `gtfs_tools` package. You can check how to do it [here](https://ipeagit.github.io/gtfstools/reference/frequencies_to_stop_times.html).

It's basically three steps:

```R
# read original gtfs
montreal_gtfs <- gtfstools::read_gtfs(here::here("data/montreal", "gtfs_stm.zip"))

# convert to stop times
montreal_gtfs_st <- gtfstools::frequencies_to_stop_times(montreal_gtfs)

# save new gtfs
gtfstools::write_gtfs(montreal_gtfs_st, path = here::here("data/montreal", "gtfs_stm_st.zip"))
```

Just remember to remove the old GTFS and network.dat files from the data folder before calling `setup_r5` again.

**Comment by nick-newstead** [comment]
Thank you, @mvpsaraiva and @rafapereirabr! Converting frequencies to stop times resolved the issue.

**Comment by mvpsaraiva** [comment]
Thats great! Thanks for helping us improve the package. Your input data will help us find the root of this issue.
