### ISSUE TITLE
Add a "quiet" argument to setup_r5

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#22]
`setup_r5()` right now outputs all the network building logs in the console.  This can be a bit overwhelming and in the case of large networks I guess it won't be possible to scroll all the way up to where the log starts because the console has a limit of rows.

The "quiet" argument could be used to, instead of outputting the logs in the console, saving it in a log file in the provided path.

**Comment by rafapereirabr** [comment]
I agree this would be a good addition to the function and we should add this paremeter to the routing functions as well. I've done a quick search on how to supress messages from Java but  couldn't find a way. @mvpsaraiva is the Java expert among us, so hopefully he'll know how to address this

**Comment by mvpsaraiva** [comment]
I'll try to figure this out. I thought it would be easier to suppress logging messages from the R side, but I'll check how to do it directly in Java.

**Comment by dhersz** [comment]
It shouldn't be that hard with `sink()`. I'm having a look at it now.

**Comment by dhersz** [comment]
Well, it really shouldn't be hard, but it's not working, not sure why. With `sink` we can collect either outputs (print, cat, etc) or messages (messages, warnings, errors), but none of these seem to work with `setup_r5`.

Some reproducible code:

```r
data_path <- system.file("extdata", package = "r5r")
logs_path <- file.path(data_path, "setup_logs.txt")
logs      <- file(logs_path, open = "w")

sink(logs, type = "message")

setup_r5(system.file("extdata", package = "r5r"))

sink(NULL, type = "message")
close(logs)
```

Creates a log with the following content:

```
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0.jar

Using cached network.dat from C:/Users/Usuario/Documents/repos/r5r/r-package/inst/extdata/network.dat
```

When setting `type = "output"`:

```
data_path <- system.file("extdata", package = "r5r")
logs_path <- file.path(data_path, "setup_logs.txt")
logs      <- file(logs_path, open = "w")

sink(logs, type = "output")

setup_r5(system.file("extdata", package = "r5r"))

sink(NULL, type = "output")
close(logs)
```

The log:
`[1] "Java-Object{com.conveyal.r5.R5RCore@2dc4be3a}"`

None prevent the log messages from appearing in the console, however...

**Comment by mvpsaraiva** [comment]
I've added a `quiet` argument to the `setup_r5` function. It wasn't a trivial task, and it definitely needs more testing, but I think it is working.

I've also created a set of functions to control how `verbose` R5R core is. Some examples:

```
# Most messages are shown. It is the default now.
r5r_core$verboseMode()

# Only errors are reported.
r5r_core$silentMode()

# Additional function to fine tune the outputs:
# everything
r5r_core$setLogMode("ALL")

# completely silent
r5r_core$setLogMode("OFF")

# somewhere in between
r5r_core$setLogMode("ERROR")
r5r_core$setLogMode("WARN")
r5r_core$setLogMode("INFO")
r5r_core$setLogMode("DEBUG")
r5r_core$setLogMode("TRACE")
```
The new logging mode takes effect after one of those functions is called. Now we need to create the R wrapper functions around those.

**Comment by rafapereirabr** [comment]
I've created a new support function `set_verbose()` (see below). I've implemented it in the `travel_time_matrix` function as a first test and it seems to be working fine. The default behavior is `verbose=TRUE` to show R5 output messages `r5r_core$verboseMode()` but the user can set `verbose=FALSE` to get only ERROR messages, if there are any. 

Let me know if you guys are Ok with this, and then we can proceed to implemented in the other functions.

```
#' Set verbose argument
#'
#' @param verbose logical, passed from function above
#' @export
#' @family support functions
#'
set_verbose <- function(verbose){

  if (verbose == TRUE) {
    r5r_core$verboseMode()

  } else if (verbose == FALSE) {
    # Only errors are reported.
    r5r_core$silentMode()

  } else {
    stop("Parameter 'verbose' must be either TRUE or FALSE")
  }
}

```

**Comment by dhersz** [comment]
Something is still going on. After I set `verbose = FALSE` once all subsequent setups will be verbose, irrespective of what value I'm passing. Check it out (I supressed quite a bit of the log messages for readability):

```r
> data_path <- system.file("extdata", package = "r5r")
> r5r_obj <- setup_r5(data_path, verbose = TRUE)
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0_20200822.jar
10:26:58.209 [main] INFO  c.c.r5.transit.TransportNetwork - File 'C:\Users\Usuario\Documents\repos\r5r\r-package\inst\extdata\build-config.json' is not present. Using default configuration.
10:26:58.248 [main] INFO  c.c.r5.transit.TransportNetwork - Found GTFS file C:\Users\Usuario\Documents\repos\r5r\r-package\inst\extdata\poa.zip
.............
10:27:08.684 [main] INFO  com.conveyal.r5.transit.TransitLayer - Done. Computed distances to street vertices from 212 of 212 transit stops.

Using cached network.dat from C:/Users/Usuario/Documents/repos/r5r/r-package/inst/extdata/network.dat


> r5r_obj <- setup_r5(data_path, verbose = TRUE)
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0_20200822.jar
10:28:19.893 [main] INFO  c.c.r5.transit.TransportNetwork - File 'C:\Users\Usuario\Documents\repos\r5r\r-package\inst\extdata\build-config.json' is not present. Using default configuration.
...................
10:28:24.244 [main] INFO  com.conveyal.r5.transit.TransitLayer - Done. Computed distances to street vertices from 212 of 212 transit stops.

Using cached network.dat from C:/Users/Usuario/Documents/repos/r5r/r-package/inst/extdata/network.dat


> r5r_obj <- setup_r5(data_path, verbose = FALSE)
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0_20200822.jar

Using cached network.dat from C:/Users/Usuario/Documents/repos/r5r/r-package/inst/extdata/network.dat


> r5r_obj <- setup_r5(data_path, verbose = TRUE)
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0_20200822.jar

Using cached network.dat from C:/Users/Usuario/Documents/repos/r5r/r-package/inst/extdata/network.dat
```

**Comment by mvpsaraiva** [comment]
It's a bug. I've found it, and I'll fix for the next jar.
Thanks @dhersz

**Comment by rafapereirabr** [comment]
@mvpsaraiva , Can we close this now ?

**Comment by dhersz** [comment]
Seems to be working alright for me now. I'm closing it now, but we can always open it later if we find something related to it.
