### ISSUE TITLE
Error in running travel time matrix: "Visiting too many spatial index cells"

### ISSUE THREAD

**Issue by Tamarak2** [ipeaGIT/r5r#220]
Hi All, 

Has anyone run into an error when running a travel time matrix that goes:

**[ForkJoinPool.commonPool-worker-15] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.**

This shows up multiple times depending on the number of points in the origin/dest file, and I haven't been able to find any details about it anywhere. 

Thanks!
Tamara

**Comment by mvpsaraiva** [comment]
Hi @Tamarak2. Indeed, I've never seen this error before. Can you give some more information about your inputs? How large is your study area, and how many origin/destination points do you have?

**Comment by Tamarak2** [comment]
Hi!

The area is fairly large but I've run larger ones, about 80km by 40 km. I initially had slightly over 100,000 locations, but I've been trying with a small subset (~2000) and getting the same result, just less of it. Running the ttm for the 100,000 came back with dozens of the "visiting too many spatial index cells", using 2000 comes back with about 3.

**Comment by Tamarak2** [comment]
@mvpsaraiva 

I've also tried with a much smaller area, and fewer points (10 x 20 km, 300 points) and still getting the same issue,

Thanks for any suggestions! Attaching the GTFS, PBF and points. 


[Uploading Medan LITTLE.zip…]()

**Comment by mvpsaraiva** [comment]
I've noticed that your points are in projected UTM coordinates, which must be causing the problem. You must convert the points to geographic coordinates, CRS 4326 - WGS 84. 
Try this and let me know if it works.

**Comment by Tamarak2** [comment]
Yes! Thank you for the catch - shifting the point to WGS84 fixed it!

**Comment by mvpsaraiva** [comment]
I'm glad it's working. I've opened a new issue to remember to check the input coordinates to avoid this error again, and I'm closing this issue now.
