### ISSUE TITLE
Check projection of input origin and destination points

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#222]
When trying to route between points with UTM coordinates, R5 throws the following exception (issue #220):

> [ForkJoinPool.commonPool-worker-15] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.

We need to test the inputs points and make sure they are in WGS 84 - CRS 4326.

**Comment by rafapereirabr** [comment]
I believe this has alread been fixed when @dhersz fixed #201.

**Comment by dhersz** [comment]
We still have to check whether the lat lon values in dataframes (which are not sf) are within reasonable values.

**Comment by rafapereirabr** [comment]
lat : -90 90
long -180 180

**Comment by rafapereirabr** [comment]
We have decided to only accept `sf POINT` objects as inputs for origin and destination points as a way to make sure input is in the correct projection . Closing this issue here and moving the discussion to #253
