### ISSUE TITLE
Timeout Error for IPEA

### ISSUE THREAD

**Issue by abemanian** [ipeaGIT/r5r#225]
For the past day I haven't been able to run a previously working file due to the IPEA website being down. I receive the following message after using the setup_r5() function:

Error in curl::curl_fetch_memory(url, handle = handle) :    Timeout was reached: [www.ipea.gov.br] Resolving timed out after 10000 milliseconds

Additionally when I check on multiple PCs it seems like the website is actually down. Is there any work around or sense of when the website will be back up?

**Comment by mvpsaraiva** [comment]
Hi @abemanian.
Unfortunately, IPEA's servers are offline this weekend for maintenance. The servers should be back up on Monday.
However, if you have a previously working setup, connection to the servers should not be required. `r5r` only accesses the servers to download `R5`'s Jar file once. Which parameters are you passing to `setup_r5`? Perhaps you're using `temp_dir = TRUE`, which can cause `r5r` to redownload the jar at every new session.

**Comment by rafapereirabr** [comment]
The data server is back. Closing this issue for now.
