### ISSUE TITLE
remove rgdal from package suggestions and test

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#233]
### Brief description of the problem:
The `rgdal` package will be retired on Jan 1st 2024 ([seminar by Edzer](https://www.youtube.com/watch?v=cK08bxUJn5A)). We currently use it in [one of our tests](https://github.com/ipeaGIT/r5r/blob/5743d27f71be1be09efed17bd53685f3d27537b3/r-package/tests/testthat/test-elevation_utils.R).

We should probably replace it  with terra or stars.

**Comment by rafapereirabr** [comment]
Since the new version of R5 does the heavy lifting with regards to elevation data, I guess this can be easily fixed now :)

**Comment by mvpsaraiva** [comment]
I've removed all custom elevation features from `r5r` in favour of `R5`'s new native solution. I've also removed `raster` and `rgdal` package dependencies from DESCRIPTION. It's safe now to delete any reference I may have missed.

**Comment by rafapereirabr** [comment]
Great! closing this one.
