### ISSUE TITLE
Only walk mode even the dates are within the calendar range

### ISSUE THREAD

**Issue by yiwenw3** [ipeaGIT/r5r#234]
Hi, I am continuing working on the travel time and the detailed itineraries for King County. I can receive the travel times by different modes for 2020 data. However, when I used dates in 2019, I received the travel times by walking only. I think I have set the `departure_datetime`  within the calendar range of the GTFS feed in the calendar.txt file. The GTFS data I now used for King County Metro is from (https://transitfeeds.com/p/king-county-metro/73/20190107). Can you please tell me what the issue is? I have attached other files I used. Thank you for your response!
[OriginsDestinationsPugetSound.csv](https://github.com/ipeaGIT/r5r/files/8190026/OriginsDestinationsPugetSound.csv)
Network: https://download.geofabrik.de/north-america/us/washington.html

```r
library(r5r)
library(sf)
library(data.table)
               
File_Path = file.path("C:","299", "Updated Data", fsep = .Platform$file.sep)
list.files(File_Path)
poi <- fread(file.path(File_Path, "OriginsDestinationsPugetSound.csv"))
head(poi)

r5r_core <- setup_r5(data_path = File_Path, verbose = TRUE)

mode <- c("WALK","TRANSIT")
max_walk_dist <- 1000 
max_trip_duration <- 120

OriginPoint = poi[1:25,2:4]
DestinationPoint = poi[1:25,5:7]
departure_datetime = as.POSIXct("4/16/2019 10:00", format = "%m/%d/%Y %H:%M")

dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = OriginPoint,
                            destinations = DestinationPoint,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = TRUE,
                            verbose = FALSE)

ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = OriginPoint,
                          destinations = DestinationPoint,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_dist = max_walk_dist,
                          breakdown = FALSE,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)
```
A futher question is that if I want to analyze the trips at different dates for a whole year in one Excel spreadsheet, will the system work with mutiple GTFS.zip files attached? If not, what is an ideal solution for that? Thank you!

**Comment by rafapereirabr** [comment]
Hi @yiwenw3 .

I've run the code of the reproducible example above and both outputs include trips by public transport. Regarding the `detailed_itineraries()` function, please see the `mode` column of the output. Regarding the `travel_time_matrix()` function, trying running this function with mode `c("WALK","TRANSIT")` and `"WALK"` only. You will see the the travel time estimates are quite different. Alternatively, you can set `breakdown = TRUE` and you will see which trips involve public transport.

Regarding your second question. The `setup_r5()` function will build a network will all the GTFS feeds in the data_path, regardless whether they have different calendars.

Please note that this is not really an issue about a bug of feature request for `r5r`. If you have questions about r5r usage, we kindly ask you to ask these questions on [stackoverflow.com](https://stackoverflow.com/) with the `r5r`tag. This way we make sure other members of the community might be able to help and benefit from your question.
