### ISSUE TITLE
Transfers/Missing Transfer file

### ISSUE THREAD

**Issue by kangkandc1** [ipeaGIT/r5r#236]
Hello,

I encountered a possible issue  while dealing with a GTFS feed in which the transfer file is missing. 
The specific feed is here : https://gtfs.de/de/feeds/de_rv/

The Transport agency runs two services: RB and RE. The feed itself does not come with a transfer file.
While checking for the travelling time from station Aachen hbf (id:15638,2732,3775,6074,7644,8029,9368) to Alsdorf (id:7952), the result from the detailed itenary suggests that the options involving a transfer between  RB and RE are not being considered. 

I am attaching the code here  ( I can share the network.dat file if needed)

Thanks and Regards
AACHEN=O[O$id==15638|O$id==2732|O$id==3775|O$id==6074|O$id==7644|O$id==8029|O$id==9368,]
mode <- c("TRANSIT")
max_walk_dist <- 500
max_trip_duration <- 420
departure_datetime <- as.POSIXct("17-03-2022 11:30:00",
                                 format = "%d-%m-%Y %H:%M:%S")

                          
                                 

d1=O[O$id==7952,]
dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = AACHEN,
                            destinations = d1,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = FALSE,
                            verbose = FALSE)

**Comment by mvpsaraiva** [comment]
Hi @kangkandc1.

I'm checking on Google Maps to try to understand your problem. I've found one route via RB20 that takes 26 minutes, and another route via RE1 then RB20 that takes 36 minutes. Also, there's a bus service (51) that takes 48 minutes.

So, maybe RB/RE transfers are not being returned because they are slower than a direct trip via RB? Just to clarify, `detailed_itineraries()` doesn't necessarily return all possible routes between any origin/destination pair.

**Comment by kangkandc1** [comment]
Hello Saraiva,

Thanks for the prompt response. I think I understood the problem. The response from R5R is the same as the shortest route google maps. However, I was looking using the webapp from the Railcompany( DB) in Germany (https://reiseauskunft.bahn.de/).

The results from google maps is not the same as the one from the DB webapp (which are generally shorter). I guess (and a pure guess) is that DB has some propietary data that is not part of the supplied GTFS feed.

One general question: Do you have an best practices on dealing with overlapping GTFS (for the same area) feeds without transfer files?
Thanks and Regards

**Comment by kangkandc1** [comment]
Thanks for your clarification.
