### ISSUE TITLE
Compute accessibility with external travel time data

### ISSUE THREAD

**Issue by Onnene** [ipeaGIT/r5r#239]
Hello,

I meant to ask if r5r can be used for accessibility calculations with OD travel time matrices computed outside r5r. If so, how can this be done?

Thank you!

**Comment by rafapereirabr** [comment]
Hi @Onnene . r5r is not built for this kind of problem you have in hands. If you have already calculated travel-time matrix ,  I would strongly suggest you use the [dodgr](https://github.com/ATFutures/dodgr) R package. It's does what you need and it's super fast and easy to use.
