### ISSUE TITLE
Rounding seems to happen too early with time_window > 1

### ISSUE THREAD

**Issue by cliffmv** [ipeaGIT/r5r#240]
It appears that when you use the `time_window` setting in `travel_time_matrix`, it uses the rounded down travel time of each minute in the time window instead of the actual time, which gives results that are regularly a minute or so too low. As an example, I created three TTMs at noon, 12:01, and 12:02, and then a TTM using a three-minute time window at 12:00 which should return the average of the other three TTMs (if I understand how `time_window` works!).

Focusing on the trip between `fromId=89a901291abffff` and `toId=89a901295b7ffff`, we can see that the rounded travel times are 37, 36, and 40 minutes for the 12:00pm, 12:01pm, and 12:02pm TTMs, respectively, while the actual times (from `combined_time`) are 37.7, 36.7, and 40.7 minutes. The average of the rounded times is 37.67 minutes, which gets rounded down to 37 in the time window TTM. However, the average of the actual times is 38.37. This number is unavailable from the `combined_time` of the time window TTM, since the breakdown is not the average, but the information from the minute whose wait time is closest to the average wait time, in this case the 12:01pm TTM.

Travel time results would be more accurate for TTMs with a `time_window` if results were only rounded once, instead of using the rounded results of each minute in the time window. As a side note, would it be valuable to have an option that returned average values across the time window for the breakdown stats instead of the values from the trip with the most average wait time? It would work for the time results, though probably not for the `routes` column.

Thanks! I've just started using r5r and it's immensely useful!

```r
options(java.parameters = '-Xmx4G')
library(r5r)
library(dplyr)

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path = data_path, temp_dir = TRUE)

# load origin/destination points
points <- read.csv(file.path(data_path, "poa_hexgrid.csv"))


# Calculate 3 TTMs, one for each minute of the TTM with the time_window setting
ttm0 <- travel_time_matrix(r5r_core,
                           origins = points,
                           destinations = points,
                           mode = c("WALK", "TRANSIT"),
                           walk_speed = 4.82803,
                           max_trip_duration = 45,
                           departure_datetime = lubridate::mdy_hm("4/19/19 12:00pm"),
                           verbose = F,
                           breakdown = T)
ttm1 <- travel_time_matrix(r5r_core,
                           origins = points,
                           destinations = points,
                           mode = c("WALK", "TRANSIT"),
                           walk_speed = 4.82803,
                           max_trip_duration = 45,
                           departure_datetime = lubridate::mdy_hm("4/19/19 12:01pm"),
                           verbose = F,
                           breakdown = T)
ttm2 <- travel_time_matrix(r5r_core,
                           origins = points,
                           destinations = points,
                           mode = c("WALK", "TRANSIT"),
                           walk_speed = 4.82803,
                           max_trip_duration = 45,
                           departure_datetime = lubridate::mdy_hm("4/19/19 12:02pm"),
                           verbose = F,
                           breakdown = T)

# Calculate a TTM with time_window 3, which should give the average of the previous three TTMs
r5r_core$setTimeWindowSize(3L)
ttm_window <- travel_time_matrix(r5r_core,
                            origins = points,
                            destinations = points,
                            mode = c("WALK", "TRANSIT"),
                            walk_speed = 4.82803,
                            max_trip_duration = 45,
                            departure_datetime = lubridate::mdy_hm("4/19/19 12:00pm"),
                            verbose = F,
                            breakdown = T,
                            time_window = 3)

# Join together so it's easier to compare the results
ttm_summ <- full_join(ttm0, ttm1, by=c("toId", "fromId"), suffix=c('.0', '.1')) %>%
  full_join(ttm2, by=c("toId", "fromId")) %>%
  full_join(ttm_window, by=c("toId", "fromId"), suffix=c(".2", ".mean"))
```

**Comment by mvpsaraiva** [comment]
Hi @cliffmv. Thanks for using our package.

What you're describing here seems to be actually R5's behaviour, nothing we can change on our side in r5r. But note that the default resulting travel time is the **median** in the `time_window`, and not the mean. Hence the resulting travel time is 37 (median of 37, 36, and 40). You can get other percentiles as well, using the `percentiles` parameter. About the fact that those numbers seem to be rounded down from the original 37.7, 36.7, and 40.7, I can investigate a little more in the coming days. But, if it's something upstream in R5, there's not much we can do.

> As a side note, would it be valuable to have an option that returned average values across the time window for the breakdown stats instead of the values from the trip with the most average wait time? It would work for the time results, though probably not for the `routes` column.

About this, we are working on improving the results when `breakdown = T` in the next version of the package.  We're planning on returning the full results from the travel times breakdown, so the user can choose how to better summarise them according to their own needs.

**Comment by rafapereirabr** [comment]
After a long discussion on #247, we have decided to split `travel_time_matrix()` into two separate functions:
- `travel_time_matrix()`, which will have a `percentiles` parameter but not a `breakdown` parameter.
- `extended_travel_time_matrix()`, which will have a `breakdown` parameter but not a `parameter` parameter. New issue #252

**Comment by cliffmv** [comment]
Thanks, the extended function looks like it will be very useful for my needs! Looking forward to using it when it's published.

**Comment by rafapereirabr** [comment]
Closing in favor of #252
