### ISSUE TITLE
New function to set fare rules

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#242]
New function to set fare rules, which will be used in the new function  `pareto_frontier()` to calculate trade-offs between travel time and monetary costs.

**Comment by rafapereirabr** [comment]
- [ ] Remove the `base_fare` parameter from the `setup_fare_calculator()` function

**Comment by mvpsaraiva** [comment]
> * [ ]  Remove the `base_fare` parameter from the `setup_fare_calculator()` function

Actually, the parameter must stay in `setup_fare_calculator()`. But the value is not stored anymore in the `fare_calculator` list/object.

**Comment by dhersz** [comment]
This has been done in the last few commits.
