### ISSUE TITLE
Behaviour of `travel_time_matrix()` when `breakdown = TRUE`

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#247]
We've included the feature to output extended path information in `travel_time_matrix()`, in r5r 0.6.0, as discussed in issue #194.

The current version of `travel_time_matrix()` on CRAN only returns the first row of information available, as shown below:

|   | fromId          | toId            | travel_time_p025 | travel_time_p050 | travel_time_p075 | access_time | wait_time | ride_time | transfer_time | egress_time | combined_time | routes | n_rides |
|---|-----------------|-----------------|------------------|------------------|------------------|-------------|-----------|-----------|---------------|-------------|---------------|--------|---------|
| 1 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 24.4        | 1.6       | 21.7      | 0             | 6.6         | 54.3          | 617    | 1       |

However, after the package was released I've noticed that R5 produces a lot more path alternatives. Now, the current `dev` version outputs the entire set of alternative paths for each OD pair, as follows:

|    | from_id         | to_id           | travel_time_p025 | travel_time_p050 | travel_time_p075 | access_time | wait_time | ride_time | transfer_time | egress_time | combined_time | routes         | n_rides | n_iterations |
|----|-----------------|-----------------|------------------|------------------|------------------|-------------|-----------|-----------|---------------|-------------|---------------|----------------|---------|--------------|
| 1  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 6.1       | 18.8      | 2             | 5.9         | 49.9          | 731\|B56\|T12  | 3       | 2            |
| 2  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.8        | 3.6       | 16.4      | 0             | 12.1        | 49.9          | 493\|613       | 2       | 2            |
| 3  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.9        | 1.1       | 17.5      | 0             | 15.8        | 57.3          | 611            | 1       | 1            |
| 4  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 24.4        | 2.6       | 21.7      | 0             | 6.6         | 55.3          | 617            | 1       | 2            |
| 5  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.4        | 3.6       | 13        | 0             | 15.8        | 54.7          | 633            | 1       | 5            |
| 6  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.6        | 4.2       | 16.2      | 0             | 5.9         | 48.9          | 613\|T12       | 2       | 1            |
| 7  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 8.4         | 4.9       | 27.7      | 5.6           | 6.3         | 52.9          | C1\|510\|T12   | 3       | 4            |
| 8  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.6        | 2.3       | 15.7      | 0             | 12.1        | 52.9          | 613            | 1       | 2            |
| 9  | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 3.2       | 22.3      | 0             | 6.6         | 49.3          | 494\|617       | 2       | 1            |
| 10 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.4        | 2.8       | 19.9      | 0             | 1.8         | 46.9          | 633\|T2A1      | 2       | 2            |
| 11 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.5        | 3.7       | 22.1      | 2.4           | 6.6         | 52.3          | 495\|617       | 2       | 5            |
| 12 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 8.8       | 18.1      | 0             | 5.9         | 49.9          | 731\|TR62\|T12 | 3       | 2            |
| 13 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.7        | 2.8       | 23.5      | 2.8           | 6.6         | 53.3          | 671\|617       | 2       | 1            |
| 14 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.4        | 2.9       | 21.9      | 4.5           | 6.6         | 53.3          | D73\|617       | 2       | 1            |
| 15 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.9        | 3.3       | 24.2      | 0.7           | 1.8         | 52.9          | 611\|T2A1      | 2       | 4            |
| 16 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 4.1       | 16.5      | 0             | 12.1        | 49.9          | 494\|613       | 2       | 2            |
| 17 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.4        | 2.9       | 14        | 0             | 12.1        | 51.5          | 633\|B56       | 2       | 1            |
| 18 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 8.4       | 15.4      | 0             | 5.9         | 46.9          | 731\|TR62\|T12 | 3       | 4            |
| 19 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 16.9        | 7.5       | 23.6      | 1.6           | 6.3         | 55.9          | R41\|T12       | 2       | 6            |
| 20 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 16.7        | 3.8       | 24.2      | 0             | 6.6         | 51.3          | 510\|617       | 2       | 3            |
| 21 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.6        | 3.6       | 21.5      | 0             | 6.6         | 49.3          | D72\|617       | 2       | 3            |
| 22 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 22.6        | 3.5       | 21.8      | 0             | 1.8         | 49.9          | 613\|T2A1      | 2       | 3            |
| 23 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 17.1        | 5.6       | 15.7      | 0             | 15.8        | 54.1          | 731\|TR60      | 2       | 2            |
| 24 | 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 25.2        | 2.2       | 22.2      | 4.4           | 1.8         | 55.9          | TR62\|T2A1     | 2       | 1            |

The new output also has a new column `n_iterations`, that indicates how many times that particular public transport itinerary produced the fastest travel during the provided time window. If we sum the `n_iterations` column, the result should be the same as the value set in the `time_window` parameter (which is 60, in this example).

I've opened this issue to discuss the best option going forward. I believe that we should return all path options available when `breakdown = T`.

**Comment by mvpsaraiva** [comment]
Reproducible code for the results above:

```R
options(java.parameters = '-Xmx4G')
library(r5r)
library(data.table)

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)

# load origin/destination points
points <- fread(file.path(data_path, "poa_hexgrid.csv"))


# Calculate 3 TTMs, one for each minute of the TTM with the time_window setting
ttm <- travel_time_matrix(r5r_core,
                          origins = points[id == "89a901288c3ffff",],
                          destinations = points[id == "89a90129953ffff",],
                          mode = c("WALK", "TRANSIT"),
                          max_trip_duration = 60,
                          time_window = 60,
                          percentiles = c(25, 50, 75),
                          departure_datetime = lubridate::mdy_hm("4/19/19 12:00pm"),
                          verbose = F,
                          breakdown = T)
```

Running this code in `r5r` 0.7.0 (from CRAN) produces the first table of results in the previous comment, while running it on the `dev` branch on GitHub produces the second.

**Comment by dhersz** [comment]
Great!!! We have to adjust all the documentation regarding the `breakdown` parameter.

**Comment by mvpsaraiva** [comment]
Some more news about this feature: it turns out we can get even more information from R5. I've managed to extract the full travel time matrix, minute by minute, which looks like this:

| from_id         | to_id           | travel_time_p025 | travel_time_p050 | travel_time_p075 | departure_time | access_time | wait_time | ride_time | transfer_time | egress_time | combined_time | routes         | n_rides |
|-----------------|-----------------|------------------|------------------|------------------|----------------|-------------|-----------|-----------|---------------|-------------|---------------|----------------|---------|
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:00:00       | 17.1        | 7         | 18.8      | 2             | 5.9         | 50.8          | 731\|B56\|T12  | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:01:00       | 17.1        | 6         | 18.8      | 2             | 5.9         | 49.8          | 731\|B56\|T12  | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:02:00       | 25.2        | 2.3       | 22.1      | 4.4           | 1.8         | 55.8          | TR62\|T2A1     | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:03:00       | 22.9        | 5.3       | 24.1      | 0.7           | 1.8         | 54.8          | 611\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:04:00       | 22.9        | 4.3       | 24.1      | 0.7           | 1.8         | 53.8          | 611\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:05:00       | 22.9        | 3.3       | 24.1      | 0.7           | 1.8         | 52.8          | 611\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:06:00       | 22.9        | 2.3       | 24.1      | 0.7           | 1.8         | 51.8          | 611\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:07:00       | 22.6        | 4.6       | 21.8      | 0             | 1.8         | 50.8          | 613\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:08:00       | 22.6        | 3.6       | 21.8      | 0             | 1.8         | 49.8          | 613\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:09:00       | 22.6        | 2.6       | 21.8      | 0             | 1.8         | 48.8          | 613\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:10:00       | 22.4        | 3.8       | 19.9      | 0             | 1.8         | 47.9          | 633\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:11:00       | 22.4        | 2.8       | 19.9      | 0             | 1.8         | 46.9          | 633\|T2A1      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:12:00       | 16.9        | 5.5       | 23.6      | 1.6           | 6.3         | 53.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:13:00       | 16.9        | 4.5       | 23.6      | 1.6           | 6.3         | 52.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:14:00       | 24.4        | 2.6       | 21.7      | 0             | 6.6         | 55.3          | 617            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:15:00       | 24.4        | 1.6       | 21.7      | 0             | 6.6         | 54.3          | 617            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:16:00       | 17.7        | 2.8       | 23.5      | 2.8           | 6.6         | 53.4          | 671\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:17:00       | 16.7        | 4.8       | 24.2      | 0             | 6.6         | 52.3          | 510\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:18:00       | 16.7        | 3.8       | 24.2      | 0             | 6.6         | 51.3          | 510\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:19:00       | 16.7        | 2.8       | 24.2      | 0             | 6.6         | 50.3          | 510\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:20:00       | 17.1        | 8.8       | 18.1      | 0             | 5.9         | 49.9          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:21:00       | 17.1        | 7.8       | 18.1      | 0             | 5.9         | 48.9          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:22:00       | 22.6        | 2.3       | 15.7      | 0             | 12.1        | 52.7          | 613            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:23:00       | 22.6        | 1.4       | 15.7      | 0             | 12.1        | 51.8          | 613            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:24:00       | 17.1        | 5.1       | 16.5      | 0             | 12.1        | 50.8          | 494\|613       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:25:00       | 17.1        | 4.1       | 16.5      | 0             | 12.1        | 49.8          | 494\|613       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:26:00       | 22.9        | 1.1       | 17.5      | 0             | 15.8        | 57.3          | 611            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:27:00       | 22.4        | 5.6       | 13        | 0             | 15.8        | 56.8          | 633            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:28:00       | 22.4        | 4.6       | 13        | 0             | 15.8        | 55.8          | 633            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:29:00       | 22.4        | 3.6       | 13        | 0             | 15.8        | 54.8          | 633            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:30:00       | 22.4        | 2.6       | 13        | 0             | 15.8        | 53.8          | 633            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:31:00       | 22.4        | 1.6       | 13        | 0             | 15.8        | 52.8          | 633            | 1       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:32:00       | 17.5        | 3.7       | 22.1      | 2.4           | 6.6         | 52.3          | 495\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:33:00       | 17.5        | 2.7       | 22.1      | 2.4           | 6.6         | 51.3          | 495\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:34:00       | 17.6        | 4.6       | 21.5      | 0             | 6.6         | 50.3          | D72\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:35:00       | 17.6        | 3.6       | 21.5      | 0             | 6.6         | 49.3          | D72\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:36:00       | 17.6        | 2.6       | 21.5      | 0             | 6.6         | 48.3          | D72\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:37:00       | 22.6        | 4.1       | 16.3      | 0             | 5.9         | 48.9          | 613\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:38:00       | 17.1        | 9.4       | 15.4      | 0             | 5.9         | 47.8          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:39:00       | 17.1        | 8.4       | 15.4      | 0             | 5.9         | 46.8          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:40:00       | 17.1        | 7.4       | 15.4      | 0             | 5.9         | 45.8          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:41:00       | 17.1        | 6.4       | 15.4      | 0             | 5.9         | 44.8          | 731\|TR62\|T12 | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:42:00       | 8.4         | 6.9       | 27.7      | 5.6           | 6.3         | 54.9          | C1\|510\|T12   | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:43:00       | 8.4         | 5.9       | 27.7      | 5.6           | 6.3         | 53.9          | C1\|510\|T12   | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:44:00       | 8.4         | 4.9       | 27.7      | 5.6           | 6.3         | 52.9          | C1\|510\|T12   | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:45:00       | 8.4         | 3.9       | 27.7      | 5.6           | 6.3         | 51.9          | C1\|510\|T12   | 3       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:46:00       | 17.4        | 2.9       | 21.9      | 4.5           | 6.6         | 53.3          | D73\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:47:00       | 17.5        | 4.8       | 22.1      | 1.2           | 6.6         | 52.2          | 495\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:48:00       | 17.5        | 3.8       | 22.1      | 1.2           | 6.6         | 51.2          | 495\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:49:00       | 17.5        | 2.8       | 22.1      | 1.2           | 6.6         | 50.2          | 495\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:50:00       | 17.1        | 3.2       | 22.3      | 0             | 6.6         | 49.2          | 494\|617       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:51:00       | 22.4        | 2.9       | 14        | 0             | 12.1        | 51.4          | 633\|B56       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:52:00       | 17.8        | 4.6       | 16.4      | 0             | 12.1        | 50.9          | 493\|613       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:53:00       | 17.8        | 3.6       | 16.4      | 0             | 12.1        | 49.9          | 493\|613       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:54:00       | 16.9        | 9.5       | 23.6      | 1.6           | 6.3         | 57.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:55:00       | 16.9        | 8.5       | 23.6      | 1.6           | 6.3         | 56.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:56:00       | 16.9        | 7.5       | 23.6      | 1.6           | 6.3         | 55.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:57:00       | 16.9        | 6.5       | 23.6      | 1.6           | 6.3         | 54.9          | R41\|T12       | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:58:00       | 17.1        | 6.6       | 15.7      | 0             | 15.8        | 55.2          | 731\|TR60      | 2       |
| 89a901288c3ffff | 89a90129953ffff | 49               | 51               | 53               | 12:59:00       | 17.1        | 5.6       | 15.7      | 0             | 15.8        | 54.2          | 731\|TR60      | 2       |

Also, this can solve the whole issue of _"accessibility at the median travel time"_ vs _"median accessibility"_, discussed in issue #218.

So, I suggest we:
- use this new extended version;
- when `breakdown = T`, we don't output the percentiles columns, because users can easily calculate them from the `combined_time` column;
- users can choose `breakdown=T` or fill the `percentiles`, but not both;
- we don't need the `breakdown_stat` parameter anymore, because we output all `wait_times` instead of just the average or minimum values;

The csv of the table above is [here](https://github.com/ipeaGIT/r5r/files/8645348/ttm_breakdown_full.csv), for reference.

**Comment by rafapereirabr** [comment]
I guess this is more related to the expected behavior of the package when the user sets a `time_window` parameter, right? 

My quick 2 cents. That's a really tricky one.  This minute-by-minute output format can make the size of the output really massive for large OD matrices and large windows. This can put a major burden on local memory. Besides, getting these `percentiles` is much faster in Java. Postprocessing the travel time matriz to calculate the `percentiles` can also be quite intensive in memory use and take a lot of time for large outputs (keeping in mind here most R users do not know `data.table`).

I would suggest that we stick with the current output format showing percentiles when users set a `time_window`. In theory we could allow users to set `time_window = "minute_by_minute" `, though.

**Comment by mvpsaraiva** [comment]
> This minute-by-minute output format can make the size of the output really massive for large OD matrices and large windows.

Well... "with great power comes great hardware requirements" :)
Indeed, this is much heavier than the original travel time matrix, but not that much more expensive than the 'extended broken down' matrix we're discussing in this issue. Also, users who need all that output must be prepared to deal with it. 

I can't think of a reason for someone to need both the percentiles and the minute by minute output, but I also do not strongly oppose keeping both results in the output.

We have an alternative to deal with very large outputs. Some time ago I've implemented a feature to save outputs to .csv files instead of loading them all to memory. This is a 'hidden' undocumented feature, but it's currently working and all users have access to it. If we call 

```R
r5r_core$setCsvOutput("path-to-folder")
```

the outputs of all functions will be saved to .csv files inside the specified folder, one file for each origin point, and the functions will return empty data.tables. I use this all the time in my local machine when doing tests on large study areas. We could add a `output_folder` parameter to `travel_time_matrix()`, `accessibility()`, `pareto_frontier()` and even `detailed_itineraries()` for users who want to save memory and deal with the outputs later.

**Comment by mvpsaraiva** [comment]
> How does the `draws_per_minute` parameter influence the results? Because we'd have `draws_per_minute` estimates "inside" each departure time in the time window, right?

Yep... when using frequency-based GTFS, we'll get many more rows in the results. If `time_window = 60` and `draws_per_minute = 5`, each OD pair will generate up to 300 estimates!

**Comment by rafapereirabr** [comment]
> > How does the `draws_per_minute` parameter influence the results? Because we'd have `draws_per_minute` estimates "inside" each departure time in the time window, right?
> 
> Yep... when using frequency-based GTFS, we'll get many more rows in the results. If `time_window = 60` and `draws_per_minute = 5`, each OD pair will generate up to 300 estimates!

omg. One more reason to be very cautious about this. I'd suggest we allow users to set `percentiles` as either:

- a vector of percentile cutoff points (current beahvior) such as `c(20, 50, 80)`
- a string `"minute_by_minute"`

**Comment by dhersz** [comment]
But then `breakdown = TRUE` would work differently based on the `percentiles` parameter?

**Comment by rafapereirabr** [comment]
> But then `breakdown = TRUE` would work differently based on the `percentiles` parameter?

This is up for debate. The **`percentile` parameter** should affect how the output is **disaggregated by departure time** (either by percentile or minute by minute). Meanwhile, the **`breakdown`** parameter should affect how the output is **disaggregated by trip segment**. There are multiple possible combinations between these parameters so it could get quite confusing if the output structures are totally different.

**Comment by mvpsaraiva** [comment]
But currently, there's no way of obtaining the minute by minute matrix without `breakdown = TRUE`...

We have 2 types of output of `travel_time_matrix`, at the moment: 

1. The first one is the original matrix, with one row per OD pair, and travel times disaggregated by percentile;
2. The second one is the extended / broken down version.

What we need now is to decide on the format of the 2nd matrix (extended/broken down):
1. Full matrix, with minute by minute output - [this one](https://github.com/ipeaGIT/r5r/issues/247#issuecomment-1120219138)
2. Slightly shorter one, with rows aggregated by the **routes** column according to the `breakdown_stat` parameter - [this one](https://github.com/ipeaGIT/r5r/issues/247#issue-1225688538)
