### ISSUE TITLE
Add bicycle 'level of traffic stress' to output of `street_network_to_sf()`

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#251]
R5 automatically assigns a 'level of traffic stress' (LTS) to each street segment of the road network, based on a [set of heuristics](https://docs.conveyal.com/learn-more/traffic-stress). 

Now, the function `street_network_to_sf()` outputs those LTS levels in the column `bicycle_lts`:

<img width="1680" alt="Screenshot 2022-05-09 at 21 00 24" src="https://user-images.githubusercontent.com/7387691/167704161-0eb6b5ca-1f89-440d-96f8-22029368fedc.png">

**Comment by rafapereirabr** [comment]
This is great ! Thanks @mvpsaraiva

**Comment by mvpsaraiva** [comment]
This one is already implemented in the master branch, so I'm closing this issue.
