### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Planetizan** [ipeaGIT/r5r#254]
Have been encountering this issue.

> r5r_core <- setup_r5(data_path , verbose = FALSE)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [www.ipea.gov.br] Resolving timed out after 10000 milliseconds

Could you please help how to solve it?

Thanks!

**Comment by rafapereirabr** [comment]
Please update your local installation of r5r and let us us if the problem persists

**Comment by mvpsaraiva** [comment]
Hi @Planetizan 

Indeed, this is a recent modification made upstream in `R5`, I think it's in place since version 6.5. I suggest you try cropping your osm files to fit your study area better. You can follow the instructions [here](https://docs.conveyal.com/prepare-inputs#cropping).

**Comment by Planetizan** [comment]
Hi @mvpsaraiva, thank you for your prompt response.  After reducing the osm files, I did not face the issue. But my concern is, now the area of access calculation is smaller, the number of opportunities that one can access will be restricted to that area only. What if I have to calculate access beyond that area, like for increased travel time. Before, I did not have this error since it used to calculate based on USA sub region. Now after cropping the osm.pbf file, I am doubtful about the output. 

Thanks!

**Comment by rafapereirabr** [comment]
As @mvpsaraiva said, this restriction is hardcoded upstream on R5 so there is nothing really we can do here, unfortunately. As a sanity check, though, you could probably compare your accessibility estimates calculated (1) using the current dev version of r5r and cropped `osm.pbf` and (2) using previous version of r5r and USA sub region `osm.pbf`.

**Comment by Planetizan** [comment]
Thank you very much @rafapereirabr and @mvpsaraiva for your response. I will definitely check on that. Thanks once again.

**Comment by rafapereirabr** [comment]
Thanks. Closing this issue for now.
