### ISSUE TITLE
Vary max_walk_dist by transit type

### ISSUE THREAD

**Issue by cliffmv** [ipeaGIT/r5r#259]
Feature request: it would be great if you could set a different max_walk_dist for different types of transit. For example, people tend to be willing to walk slightly farther for rail than for a bus, so it would be useful to distinguish between the two.

Thanks!

**Comment by rafapereirabr** [comment]
Unfortunately, this could only be done upstream in R5. If you like the feature, we'd recommend opening a request on R5 github repo.
