### ISSUE TITLE
Translate tidyverse code to data.table code

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/r5r#26]
- https://github.com/ipeaGIT/r5r/blob/master/r-package/R/detailed_itineraries.R#L98

**Comment by dhersz** [comment]
I had a go at using data.table when selecting the shortest routes in [itineraries_details](https://github.com/ipeaGIT/r5r/blob/master/r-package/R/detailed_itineraries.R#L246), but it's most certainly not well written. I'll be happy if you decide to optimize it :)

**Comment by kauebraga** [comment]
It looks fine to me! The code is already in data.table style. In which commit did you make the changes?

**Comment by kauebraga** [comment]
I believe it was https://github.com/ipeaGIT/r5r/commit/f042d2f334a136cc962be8389c86e0257a227b35#diff-28397b2fc8308b76d7ce34393236734cR241

**Comment by kauebraga** [comment]
The dplyr code was deleted at https://github.com/ipeaGIT/r5r/commit/8152e0dc7bba66df875ecdc096e4c8a78bd2bc01 and it was reintroduced at https://github.com/ipeaGIT/r5r/commit/f042d2f334a136cc962be8389c86e0257a227b35 as data.table code, right?

**Comment by dhersz** [comment]
Yes, that's it. I mindlessly deleted it and reintroduced later hehe

**Comment by rafapereirabr** [comment]
Can we close this issue then?
