### ISSUE TITLE
Unable to use tobler_hiking/apply_elevation functions

### ISSUE THREAD

**Issue by randl068** [ipeaGIT/r5r#260]
Hi all, apologies if I'm missing something, but whether I use the prod and dev versions of r5r, there does not seem to be any option of using the tobler_hiking nor apply_elevation features as described in rdrr and other pages. Is this not yet in production or am I missing something in my installation process? Thanks!

**Comment by mvpsaraiva** [comment]
I've just pushed a commit to the master branch that includes this feature as natively introduced in R5. You can set the parameter `elevation = "TOBLER"` in `setup_r5()`, if you have a `tiff` file in your data folder. Then you should be able to obtain results like those described in issue #243

**Comment by rafapereirabr** [comment]
This has been implemented in the dev version.
