### ISSUE TITLE
Detect if any of the GTFS feeds used is a frequency-based feed

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#267]
- [x] Detect if any of the GTFS feeds used is a frequency-based feed and return `TRUE ` or `FALSE`.

- [x] This will be used inside the `detailed_itineraries()` to return an error with an informative message.

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/r5r/commit/13207d78aa952e3fde069a173a04c3d5f37dee9f.
