### ISSUE TITLE
Compatibility between parameters in detailed_itineraries()

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#270]
- [x] The user cannot set a `fare_structure` parameter and `suboptimal_minutes != 0`. This should throw and error with informative message 
- [x] The user cannot set `shortest_path = TRUE` and `suboptimal_minutes != 0`. This should throw and error with informative message

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/r5r/commit/8791b5b0fa03866b0ede905f5169f2170beda5a3
