### ISSUE TITLE
r5r can't find java

### ISSUE THREAD

**Issue by ACalleros** [ipeaGIT/r5r#278]
I'm running R on arch linux and I'm trying to run r5r. Every time I've tried to run `setup_r5` it seems like it can't find java, even though I have installed it. Do you know how can I make it work? Here's the console output:

`
> library(r5r)
> path <- system.file("extdata/poa", package = "r5r")
> r5r_core <- setup_r5(data_path = path, verbose = T)
Error in setup_r5(data_path = path, verbose = T) : 
  This package requires the Java SE Development Kit 11.
Please update your Java installation. The jdk 11 can be downloaded from either:
  - openjdk: https://jdk.java.net/java-se-ri/11
  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
> rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")
[1] "18.0.1.1"
`

**Comment by dhersz** [comment]
Hi @ACalleros. I haven't used javareconf in a while, but I'm pretty sure it shouldn't take that long.

If you want to switch the java version you're currently using before running r5r you can use `sudo update-alternatives --config java`. I'm pretty sure this works on all Debian-based distros, but not sure if it works on Arch. If it doesn't, maybe Arch includes a similar tool to switch the Java version?

**Comment by ACalleros** [comment]
Thank you both @dhersz @rafapereirabr!  I ran `archlinux-java set java-11-openjdk` and then `sudo R CMD javareconf` and it's all working now.
