### ISSUE TITLE
Car access mode / CAR_PARK mode

### ISSUE THREAD

**Issue by randl068** [ipeaGIT/r5r#283]
Hi there, I'm just curious if functionality to specify CAR as an access_mode or otherwise use CAR_PARK a mode in a vector with TRANSIT is no longer supported, or if there's a parameter I'm missing. Ideally this would be used in the pareto_frontier function.

**Comment by dhersz** [comment]
Hi @randl068. We have made some significant changes to the mode selection internal function in the dev version of the package.

First, we decided to make `CAR_PARK` and `BICYCLE_RENT` unavailable. We were never able to test any of them in our use cases, and we were not confident on keep exporting something we were never able to test. If this is a behaviour you depended upon please let us know, so we can review our decision.

Also, we decided to limit the modes combination in `mode` to avoid ambiguities. Particularly, we had some cases where mode was `c("CAR", "WALK", "TRANSIT")` where we couldn't confidently say if the car was to be used as access to transit or in direct trips. If the former, the access walk leg would almost always be "overpowered" by the car "leg", and if the latter the walk+transit combination would almost always be "overpowered" by a car direct trip. You should still be able to specify `mode = c("CAR", "TRANSIT")`, in which the internal function interprets the car as the access mode to transit.

**Comment by randl068** [comment]
Great! This works wonderfully for my purposes. Thank you all for your adaptability.
