### ISSUE TITLE
r5r no longer installable via CRAN

### ISSUE THREAD

**Issue by tpfau** [ipeaGIT/r5r#286]
### Brief description of the problem:
It seems r5r has been removed from CRAN as it seems to have been archived. (have a look: https://cran.r-project.org/package=r5r)

I saw that there is a plan to release a new CRAN package, is there any estimate on how long this will take?
### Reproducible example here
```r
install.packages('r5r')
```

**Comment by rafapereirabr** [comment]
We're back on CRAN
