### ISSUE TITLE
Can I build the r5r_core with 2 gtfs zips and 1 osm.pbf in the data path?

### ISSUE THREAD

**Issue by lianalan1999** [ipeaGIT/r5r#288]
Hello!
I'm trying to use r5r package to study the transit data of Pennsylvania. I have its osm.pbf right now, and also 2 gtfs zips -- one for bus and the other for the rail. I want to study the bus and rail both at the same time. Is it possible to build a r5r-core with multiple gtfs zips in one try? If not, how can I combine these 2 gtfs?
Thank you very much!

**Comment by rafapereirabr** [comment]
Hi @lianalan1999 . just put osm and gtfs feeds in the same folder and r5r will automatically combine the files to build a single multimodal transport network,  as explained in the package documentation.

**Comment by lianalan1999** [comment]
Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
