### ISSUE TITLE
Add street class and car speed information to output of street_network_to_sf()

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/r5r#290]
I've added a few columns to the `edges` table from `street_network_to_sf()`:

- edge_index: unique index of each vertex in R5's network.
- osm_id: id from OpenStreetMap. It can be repeated because a single OSM feature can be broken down into multiple street segments with different characteristics.
- street_class: "MOTORWAY", "PRIMARY", "SECONDARY", "TERTIARY", or "OTHER"
- car_speed: maximum car speed in km/h

----

Now, we can map street classes and car speeds:

![image](https://user-images.githubusercontent.com/7387691/185989302-2116c32f-5dc8-4238-9d34-ee41ee5791fe.png)

![image](https://user-images.githubusercontent.com/7387691/185989233-5f6074c1-25b0-4c01-b9eb-e7cd6df21a33.png)

----

### Next steps

But the real usefulness of this feature will be to allow users to change driving speeds in order to account for traffic congestion, simulate traffic calming strategies, etc (as in issue #289). For example, real driving speeds for select cities can be downloaded from [Uber Movement](https://movement.uber.com/), and those speeds can be linked to the output of `street_network_to_sf()` through the `osm_id` column.

So, to complete this feature, we need to:

- allow users to modify the `edges` data.frame in any way they want, such as changing driving speeds, street classes, LTS, or if streets allow walking, driving and cycling (they can already do that, we just need to document it so it's done safely)
- create a new function to read the modified `edges` data.frame and apply the changes back to R5's network (we need to decide if those changes will only be stored in memory during the R session or if we'll allow them to be 'permanently baked' into the network.dat)

Perhaps we can work on this feature after we release version 1.0.

**Comment by rafapereirabr** [comment]
This looks really great! I agree the next steps could be included in a future version, perhaps v1.1.0. In any case, this would be a super nice feature indeed.

**Comment by rafapereirabr** [comment]
Closing this issue in favor of @289
