### ISSUE TITLE
No internet connection on attempting to run setup_r5

### ISSUE THREAD

**Issue by jamiedtor** [ipeaGIT/r5r#294]
I'm encountering an error "no internet connection" when I run setup_r5(). 

I have verified that I have an Internet connection. 

> r5r_core <- setup_r5(data_path = data_path, verbose = FALSE) 
No internet connection.

I'm using:
R version 4.1.1 (2021-08-10) -- "Kick Things"

**Comment by rafapereirabr** [comment]
Hi @jamiedtor . Which version of r5r are you using?

**Comment by jamiedtor** [comment]
Hi, Rafa. Using the latest: 0.7.90000. I've discovered it's something that also affects the package osmdata. Both rely on curl.  Seems to be something related to machine configuration perhaps.  (Others in my work group encounter a similar problem with their PCs). We've run it down with corporate cyber security and IT and confirmed that it's not related to permissions or antivirus.   It does work fine on my Mac, so I'm thinking it could be Windows related.

**Comment by jamiedtor** [comment]
We've identified the issue. Posting here for posterity ... turns out when a proxy is being used (as is the case on our company machines) we need to account for that. Running this line of code before the setup_r5() call worked:

assign("has_internet_via_proxy", TRUE, environment(curl::has_internet))

**Comment by rafapereirabr** [comment]
thank you for letting us know, @jamiedtor .
