### ISSUE TITLE
Create a very small sample data to save inside the project

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#3]
Get very small sample data sets that we will be using to test, develop and demonstrate the package.

- [x] A 1 Km by 1 Km .pbf of a city
- [x] A small GTFS.zip, perhaps only three or 4 routes
- [x] A few points that will be used as origin and destination
- [x] Save these files in the `inst/extdata` directory.

**Comment by rafapereirabr** [comment]
I've added a GTFS sample of Porto Alegre (99Kb)

**Comment by mvpsaraiva** [comment]
Perhaps it's better to use an entire town as sample? My hometown street network's pbf file is 706kb, and it's GTFS is 2.7mb. With a bit of work, we can reduce the GTFS size a lot by changing it's long identifiers of trips, stops, and routes (such as f3f3d69e-827e-4776-a70d-3f47c43285a0) to shorter numbers.

**Comment by rafapereirabr** [comment]
The limitation is that CRAN packages cannot exceed 5MB. So addding the entire street network should be ok. But I guess we would need to consider only a few public transport routes anyway

**Comment by dhersz** [comment]
Thinking about it now, isn't it better to create a `download_sample_data` function? In the same lines of `download_r5`.
Then we could provide a more meaningful sample data set while still not having to worry about the file size limit.

**Comment by rafapereirabr** [comment]
It's best to have a small and simple data set within the pacakge. This makes things much easier to create examples, tests and vignettes.

**Comment by rafapereirabr** [comment]
Thanks, @dhersz !

**Comment by rafapereirabr** [comment]
Now one easily access these files offline. This will also be very handy for us to build our examples and initial tests using these files.

```
# files
file_points <- system.file("extdata/poa_hexgrid.csv", package = "r5r")
file_gtfs <- system.file("extdata/poa.zip", package = "r5r")
file_osm <- system.file("extdata/poa_osm.pbf", package = "r5r")


# read origin/destination points
df <- read.csv(file_points)
head(df)

# read gtfs
gtfs <- gtfs2gps::read_gtfs(file_gtfs)

# read osm.pbf
osm <- rgdal::readOGR( file_osm, 'lines')
osm_sf <- st_as_sf(osm)
head(osm_sf)
```
