### ISSUE TITLE
Transit/walk/bike returns empty itinerary 

### ISSUE THREAD

**Issue by elmiraberjisian** [ipeaGIT/r5r#300]
Hi!
Thanks for your useful package! I encounter this problem and I cannot seem to understand the root! Ive downloaded OSM pbf and GFTS for Vancouver, Canada (the URL for GFTS.zip: https://transitfeeds.com/p/translink-vancouver/29/latest/download and 
OSM from https://extract.bbbike.org/?lang=en;sw_lng=-123.423063;sw_lat=49.004383;ne_lng=-122.30486;ne_lat=49.474111;format=osm.pbf). When I run the following line, the detailed_itineraries returns empty!
I have changed my departure time/date and it matches the calendar_dates within GTFS files. 
I've also tried a previous version of GFTS data (2019- https://abacus.library.ubc.ca/dataset.xhtml?persistentId=hdl:11272.1/AB2/QQLSCJ). 
Ive also tried different modes and only mode that returns nonempty is CAR whereas bus, walk, bicycle all return empty.
I am confident that ODs are within the city and I have tried random ODs.
I appreciate your help with this:

```
odf<-data.frame(matrix(NA,nrow=2,ncol=3))
colnames(odf)<-c('id','lat','lon')
odf[1,]<-c(1,49.248517,-123.167771)
odf[2,]<-c(2,	49.268224,-123.153127)

time<-as.POSIXct("06-09-2022 14:30:00", format = "%d-%m-%Y %H:%M:%S")
det <- detailed_itineraries(r5r_core,
                            origins = odf[1,],
                            destinations =odf[2,],
                            mode = "BUS",
                            departure_datetime = time,
                            max_rides=3,
                            max_walk_dist=Inf,
                            max_trip_duration = Inf,
                            drop_geometry = FALSE)
```

**Comment by rafapereirabr** [comment]
Dear @elmiraberjisian ,

The error occurs because you've set `max_trip_duration = Inf`. This parameter only accepts finite value. If you remove this line from your code, the function should work fine. In the dev version of `r5r`, the function throws and error if you set `max_trip_duration = Inf`. I'd recommend installing the dev version

```{r}
# # or use the development version with latest features
# utils::remove.packages('r5r')
# devtools::install_github("ipeaGIT/r5r", subdir = "r-package")
# library(r5r)
# 

# allocate RAM memory to Java
options(java.parameters = "-Xmx4G")

library(r5r)
library(ggplot2)

# build transport network
path <- 'C:/Users/user/Downloads/Vancouver'
r5r_core <- setup_r5(path)

odf <- data.frame(matrix(NA,nrow=2,ncol=3))
colnames(odf) <- c('id','lat','lon')
odf[1,] <- c(1, 49.248517, -123.167771)
odf[2,] <- c(2,	49.268224, -123.153127)

time <- as.POSIXct("06-09-2022 14:30:00", format = "%d-%m-%Y %H:%M:%S")

det <- detailed_itineraries(r5r_core,
                            origins = odf[1,],
                            destinations =odf[2,],
                            mode = "transit",
                            departure_datetime = time,
                            # max_rides=3,
                            # max_walk_dist=Inf,
                             max_trip_duration = Inf,
                            drop_geometry = FALSE)

det

# get geometries
transit_sf <- r5r::transit_network_to_sf(r5r_core)
street_sf <- r5r::street_network_to_sf(r5r_core)

# plot
ggplot() +
  geom_sf(data = street_sf$edges, color='gray') +
  geom_sf(data = transit_sf$routes, color='green') +
  geom_sf(data = det, aes(color=mode))



```
![Rplot](https://user-images.githubusercontent.com/7448421/198749463-ae26c220-1606-4b12-a80b-0474ccc905fd.png)

**Comment by elmiraberjisian** [comment]
Thank you @rafapereirabr
