### ISSUE TITLE
R5r not reading routes

### ISSUE THREAD

**Issue by ACalleros** [ipeaGIT/r5r#301]
Hi. I am trying to use my gtfs to make detailed itineraries. It seems that R5R can't read the routes but it can read the stops. What can I do?

**Comment by rafapereirabr** [comment]
Hi @ACalleros . 

- what version of r5r are you using?
- Could you please share a reproducible example?
- perhaps post in a comment below to link to the GTFS file you're using?

**Comment by rafapereirabr** [comment]
Closing for now due to inactivity
