### ISSUE TITLE
Allow cycling on footways

### ISSUE THREAD

**Issue by Robinlovelace** [ipeaGIT/r5r#302]
In some cases, e.g. when researching safe routes to school, it is useful to allow cycling on footways. This is especially the case in places where tagging is not complete. For example, this footpath in Leeds is definitely cyclable and a nice place to go by bike, with good surface quality and plenty of width for walking and cycling and more, in fact it's a place where many people first learn to ride a bike: https://www.openstreetmap.org/way/306849934#map=17/53.81989/-1.52460

But {r5r} prevents calculation of trips on it currently, as shown below. Any way to change that?

![](https://user-images.githubusercontent.com/1825120/200095738-74cd1634-2b7c-4e88-a543-60a6171ba44f.png)

**Comment by Robinlovelace** [comment]
Even less realistic, I notice that this way is a no go for cycling according to R5, this does not make sense: https://www.openstreetmap.org/way/615612433

**Comment by rafapereirabr** [comment]
Hi @Robinlovelace , thanks for carefully looking into this. It looks like an important improvement , but I'm afraid this cannot not be done from the r5r side. I think this should perhaps be an issue upstream in R5.

**Comment by Robinlovelace** [comment]
No problem @rafapereirabr thanks to you+team for the development and continued work on the great package. I'll open an issue upstream. FYI I did make changes to the OSM data, adding `bicycle=yes` that should make it routable. No idea re. the one way driving route though, will ask the R5 people.

**Comment by Robinlovelace** [comment]
Superseded by https://github.com/conveyal/r5/issues/836
