### ISSUE TITLE
street_network_to_sf causing crash

### ISSUE THREAD

**Issue by Robinlovelace** [ipeaGIT/r5r#303]
Hard to provide a reprex because I cannot share the data but heads-up that this happened. Any ideas on how to debug this/prevent it from happening?

Here's what I tried:

```r
    remotes::install_github("ipeaGIT/r5r", subdir = "r-package")
    options(java.parameters = "-Xmx40G")
    library(r5r)
    rJava::.jinit()
    wyca_match = osmextract::oe_match(place = "West Yorkshire")
    osmextract::oe_download(file_url = wyca_match$url, download_directory = "data_r5")
    r5r_core = r5r::setup_r5(data_path = "data_r5")
    mode = c("WALK")
    max_distance = 10
    max_trip_duration_hrs = max_distance / 3.6
    max_trip_duration_min = max_trip_duration_hrs * 60
    r5_network = r5r::street_network_to_sf(r5r_core = r5r_core)
```

Error message that killed the session:

![image](https://user-images.githubusercontent.com/1825120/201493832-5a145ad9-8afd-495b-b4cd-8152ea69ea6d.png)

**Comment by Robinlovelace** [comment]
Seems to have fixed itself so closing but heads-up in case. Crashed if I ran the command after calculating routes so could that be the cause?

**Comment by rafapereirabr** [comment]
Hi Robin. Thanks for reporting this. We haven't come across this kind o crash before. We'll keep this in mind for our next round of tests
