### ISSUE TITLE
car_speed in travel_time_matrix() and detailed_itineraries()

### ISSUE THREAD

**Issue by temospena** [ipeaGIT/r5r#305]
Hi,

I found it useful to have a parameter of `car_speed` to use in the `travel_time_matrix()` and `detailed_itineraries()` functions, along the existing walk and bike speed.
The reason is to better set it up when considering the limit of `max_car_time`, once we can define the time, but have no clue about the speed, of if we want to consider other `car_speed `values than the osm_tags (for instance a constant value, for emergency vehicles)

Thanks!

**Comment by rafapereirabr** [comment]
Hi Rosa. By default, `R5` considers the legal speed limit of each road. There is no way to set a fixed `car_speed` from within R but it looks like we could do this from the Java side. This is an issue being discussed at #289, so I'm closing this issue here to keep the conversation over there.
