### ISSUE TITLE
bug: Documentation refers to dev version

### ISSUE THREAD

**Issue by JoaoCarabetta** [ipeaGIT/r5r#309]
The documentation already has the development version updates. 

Since the dev version has breaking changes in the API, a.k.a, `max_walk_dist -> max_walk_time`, it breaks basic examples. 

The ckan stable version is currently the `0.7.1`.

For instance, running the accessibility code gives me this:

```
Error in accessibility(r5r_core, origins = points, destinations = points,  : 
  unused arguments (opportunities_colnames = c("quantidade_estabelecimentos_ensino", "quantidade_estabelecimentos_saude"), max_walk_time = max_walk_time)
```

**Comment by rafapereirabr** [comment]
Hi Carabeta. This issue has been fixed with the new release of r5r v1.0.0
