### ISSUE TITLE
possible bug: detailed_itineraries() not generating routes for some coordinates

### ISSUE THREAD

**Issue by ny1526** [ipeaGIT/r5r#314]
Hi,

I am running into an issue where detailed_itineraries() fails to generate any routes that originate/terminate at certain coordinates. I have reproduced an example below. When I run the code, no error is generated, but the resulting data.table is empty. In this example, the particular issue is with the origin coordinate; detailed_itineraries() does not generate any routes from this origin coordinate to any destination in my sample.

I am not sure if this is a bug or if it has to do with the OSM network extract that I downloaded (http://download.geofabrik.de/europe/great-britain/england/greater-london.html) If the issue is with the OSM network, do I simply need to download a different extract? This coordinate does not appear to be particularly remote, and it is surrounded by roads in the OSM extract that I downloaded.

I would appreciate any help, thank you.

```r
r5r_core <- setup_r5(data_path = folder, verbose = FALSE)

origins <- data.frame(id = 1,
                      lat = 51.52204,
                      lon = -0.2376724)
destinations <- data.frame(id = 2,
                           lat = 51.37093,
                           lon = -0.0858554)
mode <- c("CAR")
max_walk_dist <- 5000
max_trip_duration <- 120
departure_datetime <- as.POSIXct("01-01-2001 08:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

# calculate a travel time matrix -- output is an empty data.table
ttm <- travel_time_matrix(r5r_core = r5r_core,
                          origins = origins,
                          destinations = destinations,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_dist = max_walk_dist,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)
ttm

# calculate detailed itineraries -- output is an empty data.table
dit <- detailed_itineraries(r5r_core = r5r_core,
                            origins = origins,
                            destinations = destinations,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            shortest_path = TRUE,
                            verbose = FALSE)
dit


```

**Comment by rafapereirabr** [comment]
Hi @ny1526 .

If you set a larger trip duration (e.g. `max_trip_duration <- 400`), the `travel_time_matrix()` function returns the following result:

> #>    from_id to_id travel_time_p50
> #> 1:       1     2             365


If you read carefully, the `detailed_itineraries()` is throwing the following error message:

> 2023-01-23 11:10:10,753 [main] ERROR c.c.r.t.TransportNetwork - TransportNetwork transit layer is loaded but timezone is unknown; API request times will be interpreted as GMT.

This occurs because R5 did not find any GTFS feed in the folder. Unfortunately, it will throw this error even if you use other transport mode rather than transit. This issue has been raised before on #170. As a **quick fix**, you can put any gtfs file inside the folder with the pbf, even if it's from another city, and that message will disappear.

**Comment by mvpsaraiva** [comment]
Hi @ny1526

The problem is in the origin point, that's set inside a park. R5 snaps the coordinates to an inner road that has no way out of the park, so no route is found.

If you change the origin coordinates to one of the roads nearby, it works:

```R
origins <- data.frame(id = "1",
                      lat = 51.518641682673845,
                      lon = -0.24421954023541498)
```

**Comment by ny1526** [comment]
Got it, thank you both very much for your help.
