### ISSUE TITLE
[QUESTION] Routing algorithm for non transit mode (ex : car, bike)

### ISSUE THREAD

**Issue by ichsan2895** [ipeaGIT/r5r#317]
1. Why `detailed_itineraries()` give different route in two ways trip? Its also has different trip duration with `travel_time_matrix()` too.

```
library(r5r)
library(mapview)
library(sf)
library(tidygeocoder)
library(dplyr)
library(tidyverse)

options(java.parameters = "-Xmx2G")

library(r5r)
path <- "r5rv1-highway-riau"
r5r_core <- setup_r5(data_path = path, verbose = FALSE)

some_addresses <- tibble::tribble(
~name,                  ~addr,
"Rokan Hulu",      "Pasir Pengaraian, Kecamatan Rambah, Rokan Hulu Regency, Riau, Indonesia",
"Rokan Hilir",      "Bagan siapi-api",
)

points <- some_addresses %>%
  tidygeocoder::geocode(addr, method = 'osm', lat = "lat" , long = "lon")

points <- points %>% mutate(id = row_number())
points_XY <- points
points <- st_as_sf(points, coords=c("lon","lat")) %>% 
  sf::st_set_crs("EPSG:4326")
points <- inner_join(x=points, y=points_XY[c("lat","lon", "id")], by="id", all.x=TRUE)

# set inputs
mode <- "CAR"
max_walk_time <- 5 # in minutes
max_trip_duration <- 9999 # in minutes
departure_datetime <- as.POSIXct("13-05-2019 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

# TTM has same trip duration from "Rokan Hulu" to "Rokan Hilir" regency (vice versa)
ttm <- expanded_travel_time_matrix(r5r_core = r5r_core,
                          origins = points,
                          destinations = points,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_trip_duration = max_trip_duration,
                          verbose = FALSE)

ttm
```
![image](https://user-images.githubusercontent.com/60387342/217533756-f1c8f2f5-f381-4dc5-b172-98711fc2cbeb.png)
```
# First, I will route it from Rokan Hulu to Rokan Hilir regency
# But detailed itineraries has different result and different trip duration with travel_time_matrix()
DIT <- detailed_itineraries(r5r_core = r5r_core,
                            origins = points[1,],
                            destinations = points[2,],
                            mode = mode,
                            max_walk_time = max_walk_time,
                            departure_datetime = departure_datetime,
                             shortest_path = FALSE,
                            max_trip_duration = 9999,
                           verbose = FALSE)

DIT$fromPlace <- as.character(st_drop_geometry(points[1,"name"]))
DIT$toPlace <- as.character(st_drop_geometry(points[2,"name"]))

# Second, I will reverse that O-D
DIT_2nd <- detailed_itineraries(r5r_core = r5r_core,
                            origins = points[2,],
                            destinations = points[1,],
                            mode = mode,
                            max_walk_time = max_walk_time,
                            departure_datetime = departure_datetime,
                             shortest_path = FALSE,
                            max_trip_duration = 9999,
                           verbose = FALSE)

DIT_2nd$fromPlace <- as.character(st_drop_geometry(points[2,"name"]))
DIT_2nd$toPlace <- as.character(st_drop_geometry(points[1,"name"]))
DIT <- rbind(DIT, DIT_2nd)
DIT
```
![image](https://user-images.githubusercontent.com/60387342/217534093-a3df277a-f8a8-4f70-8da3-8b64f2a53d1f.png)

```
st_write(DIT, "r5rv1-result.geojson", crs="WGS84", driver="Geojson", delete_dsn = TRUE)
mapview(DIT, zcol = 'from_id')
```
![image](https://user-images.githubusercontent.com/60387342/217534286-a907bbf6-c8f4-493a-8d58-a39bdf6d36be.png)

2. Why `detailed_itineraries()` is not choose the road that has higher highways tags such as "trunk" or "primary"? 
In this case, 
yellow = "Rokan Hilir" to "Rokan Hulu"
purple = "Rokan Hulu" to "Rokan Hilir"
green = "Rokan Hulu" to Rokan Hilir" with Graphhopper (mostly choose the ways in the primary and secondary road)

![image](https://user-images.githubusercontent.com/60387342/217531784-384fab5f-df90-4ad3-a4f1-7e90bc03d3af.png)

3. How much the default speed for each road type (trunk, primary, secondary, etc)?

5.  Is there are any factor that affecting vehicle speed such as road smoothness, road density, and slope? It would be nice if it can be customize too. Unfortunately, in my country, the primary road still has broken road in some segment (of course that affect the vehicle speed too). Some inter cities road are unpaved too.

I appreciate this idea https://github.com/ipeaGIT/r5r/issues/290 and https://github.com/ipeaGIT/r5r/issues/289

**network_settings.json**
```
{"r5_version":"6.7", "r5_network_version":"nv2", "r5r_version":"1.0.0", "creation_date":"2023-02-05T21:08:02.213288", "pbf_file_name":"r5rv1-highway-riau/Highway_Riau_20230123.osm.pbf", "gtfs_1":"r5rv1-highway-riau/angkots-v4-gtfs.zip", "use_elevation":"false", "elevation_cost_function":"NONE", "tiff_file_name":""}
```

BTW, Thank you for a great package in R

**Comment by ichsan2895** [comment]
Here is it the file for reproducity
[Routing-example-r5rv1.zip](https://github.com/ipeaGIT/r5r/files/10685837/Routing-example-r5rv1.zip)

**Comment by rafapereirabr** [comment]
Dear @ichsan2895 ,

1. Both functions return the route option with earliest arrival ("fastest route"), but the route can differ if you're going from A -> B , or from B -> A. Furthermore, the `detailed_itineraries()` and the `travel_time_matrix()` functions can return different results because they use different routing algorithms, as explained in the documentation of the functions.

2. As far as I know, R5 chooses the faste route based on the distance and road speed limits. Because speed limits are usually higher in roads with high hierarchy, the hierarchy is implicitly considered.

4. R5 considers that cars will drive at the max speed limit registered for the road segment in OSM data

5. As far as I know, car speed is solely determined by the max speed limit but it would indeed be good if the speed could be slightly slower for unpaved roads.

**Comment by ichsan2895** [comment]
Thanks again for fast reply

>     1. Both functions return the route option with earliest arrival ("fastest route"), but the route can differ if you're going from A -> B , or from B -> A. Furthermore, the `detailed_itineraries()` and the `travel_time_matrix()` functions can return different results because they use different routing algorithms, as explained in the documentation of the functions.

I see.. I will see it later

>     2. As far as I know, R5 chooses the faste route based on the distance and road speed limits. Because speed limits are usually higher in roads with high hierarchy, the hierarchy is implicitly considered.

In my case, the `r5r` doesn't choose the route which has higher road hierarchy. Sometimes it choose lower hierarchy that implied it has lower speed limit => slower trip duration


>     3. R5 considers that cars will drive at the max speed limit registered for the road segment in OSM data

What happen if the road doesn't have any max_speed limit in OSM data? It will be infinity? or maybe capped to 100 km/hour?

> 4. As far as I know, car speed is solely determined by the max speed limit but it would indeed be good if the speed could be slightly slower for unpaved roads.

Yes, off course. It would be cool if it can mimic the vehicle speed based on road condition and situation

**Comment by rafapereirabr** [comment]
2. R5, and hence `r5r`, will choose the route with shortest travel time regardless of road hierarchy.

3. What happen if the road doesn't have any max_speed limit in OSM data? Good question. Perhaps @mvpsaraiva could have a quick look into the Java code to find this info.

**Comment by ichsan2895** [comment]
Hello, I'm back

I want to clarify
```
street_net <- street_network_to_sf(r5r_core)
```
The I change some value in `speed` column, then, can I put back the updated value to `r5r_core`?

**Comment by rafapereirabr** [comment]
> Hello, I'm back
> 
> I want to clarify
> 
> ```
> street_net <- street_network_to_sf(r5r_core)
> ```
> 
> The I change some value in `speed` column, then, can I put back the updated value to `r5r_core`?

No. Right now, the only way to change the speed of road segments for cars in r5r is to change the speed information in the OpenStreetMap `.pbf` file, which can be done for example with [JOSM (https://wiki.openstreetmap.org/wiki/JOSM)](https://wiki.openstreetmap.org/wiki/JOSM).

**Comment by abyrd** [comment]
Hi everyone, StreetLayer uses `com.conveyal.r5.labeling.SpeedLabeler#getSpeedMS` to determine the speeds on roads, looking first at tags like `maxspeed:motorcar` or `maxspeed:forward` and falling back on `com.conveyal.r5.point_to_point.builder.SpeedConfig#defaultConfig` as the defaults. 

https://github.com/conveyal/r5/blob/995635a1750696d1666a6ac06fde827cf1944fd0/src/main/java/com/conveyal/r5/point_to_point/builder/SpeedConfig.java#L62-L78

**Comment by rafapereirabr** [comment]
Thank you @abyrd for the info. @ichsan2895 , could you please provide the OSM .pbf file you are using and paste below the output of `r5r::r5r_sitrep()` ?

**Comment by ichsan2895** [comment]
Sorry for slow response..

Here is the PBF that downloaded from QuickOSM QGIS plugin. Why I don't download from Geofabrik? 

AFAIK, QuickOSM data is same as geofabrik but I didn't download from Geofabrik since it was to big for my computer (250 GB for entire Sumatera island), even for processing for crop it to a province.

Please route from B to A using `r5r::detailed_itineraries`
B = 0.4994880 N, 101.4547 E
A = 0.3610082 N, 101.9085 E

Here is it the pbf data:
[Highway_Riau_20230123.osm.pbf.zip](https://github.com/ipeaGIT/r5r/files/11054176/Highway_Riau_20230123.osm.pbf.zip)
