### ISSUE TITLE
Limit on no of destination points

### ISSUE THREAD

**Issue by Kaushal333** [ipeaGIT/r5r#319]
I am very new in using R5R so i apologise if I am asking stupid questions and am making some mistakes
```
_**# allocate RAM memory to Java
options(java.parameters = "-Xmx4G")

# 1) build transport network, pointing to the path where OSM and GTFS data are stored
library(r5r)
path <- "C:/Users/LENOVO/OneDrive/Desktop/TutorialDocuments"
r5r_core <- setup_r5(data_path = path, verbose = FALSE)

# 2) load origin/destination points and set arguments
o_points <- read.csv("C:/Users/LENOVO/OneDrive/Desktop/TutorialDocuments/O_points.csv")
d_points <- read.csv("C:/Users/LENOVO/OneDrive/Desktop/TutorialDocuments/d_points.csv")
mode <- c("WALK", "TRANSIT")
max_walk_dist <- 1000  # meters
max_trip_duration <- 60 # minutes

{
  departure_datetime= "12-12-2022 09:00:00"
 
  departure_datetime <- as.POSIXct(departure_datetime,
                                   format = "%d-%m-%Y %H:%M:%S")
  

  
  
  # 3.1) calculate a travel time matrix
  ttm <- travel_time_matrix(r5r_core = r5r_core,
                            origins = o_points,
                            destinations = d_points,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            max_trip_duration = max_trip_duration)
  
  # Writes CSV to specified location.
  location <- paste("C:/Users/LENOVO/OneDrive/Desktop/TutorialDocuments/ttm.csv")
  write.csv(ttm, location)
  
}**_
```
Problem:
I am using this in railway network in Berlin. There are in total of 315 stations. At first analysed for Origin of 315 stations to destinations of 315 stations, it produced results.

Because I had population grid data, I wanted to use population grid points as destinations to know sort of how many grid points can be reached by individual stations to answer how many people can be reached by which stations.

so now
Origin= 315
Destinations: 90514 (as population grid data is 100*100m and area of Berlin is close to 900 sq km)

THe code runs but does not store results in csv as before.

I think maybe it is due to size of file as possible OD pairs is 315*90514.
When I try this for 10000 destination points , it produces results.

The last error I got when trying for 90514 destination points is

" Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  :
  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
Calls: travel_time_matrix -> <Anonymous> -> .jrcall -> .jcall -> .jcheck
Execution halted "

I hope you could look into it

**Comment by rafapereirabr** [comment]
If you read the error message carefully, it says `OutOfMemoryError: Java heap space`. Your output is too large for 4GB of RAM. Try increasing the memory to `options(java.parameters = "-Xmx16G")`.

Alternatively, you can set a directory path to the `output_dir` parameter. In this case, `r5r` will save all the outputs to the specified directory (one file per origin). This is usually much faster and more memory efficient

**Comment by Kaushal333** [comment]
First of all , thank you very much for the swift reply.

1. I understood the instruction and apply it right away.
"
Try increasing the memory to options(java.parameters = "-Xmx16G") "

Is there any effect of using this on the speed of operations as well?

2.
"Alternatively, you can set a directory path to the output_dir parameter. "

How do I use this alternative. Could you elaborate on this one? 
if it is code line, could you kindly write a sample line and als where i need to place this on the code?

**Comment by rafapereirabr** [comment]
1. Allocating more RAM can improve computing speed but only to a certain point.
2. Here is an example of how to use the `output_dir` parameter. In this example, the output will be saved at the indicated `output_path` . Please read the documentation of the function.

```
output_path <-  "C:/Users/LENOVO/OneDrive/Desktop/TutorialDocuments"

  ttm <- travel_time_matrix(r5r_core = r5r_core,
                            origins = o_points,
                            destinations = d_points,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            max_trip_duration = max_trip_duration,
                            output_dir = output_path 
                            )
```
