### ISSUE TITLE
time window () if GTFS does not contain frequency .txt

### ISSUE THREAD

**Issue by Kaushal333** [ipeaGIT/r5r#321]
I want to use time window() and monte carlo draws to have multiple results over a time window  but my GTFS data does not contain frequency.txt. While reading some documentation:
I read:
"ps. Please keep in mind that the time_window only affects the results when the GTFS feeds contain a frequencies.txt table."

Is there any alternative for GTFS data with no frequency.txt

P.S. My code is running fine with the default setting of single departure time.

**Comment by rafapereirabr** [comment]
You could create a function that creates a `frequency.txt` file based on `stop_times.txt`.

**Comment by rafapereirabr** [comment]
it is possible to circumvent this problem by modifying the GTFS data structure. However, this is something that needs to be done by the user, as we do not intent to incorporate this capability into r5r, at least for moment
