### ISSUE TITLE
General question on calculating travel times with multiple departure times

### ISSUE THREAD

**Issue by Ramon-88** [ipeaGIT/r5r#323]
Hello and thanks for the amazing work you did with this package.

This is not an issue, but a general question. I was wondering if there is any possibility to calculate travel time distance with transit mode using different `departure_datetime` modes. I know that the `travel_time_matrix` function allows setting a time_window and the percentiles to obtain a summary value from multiple travel times. In my case, I would just calculate the travel time at specific departure times (say, 8 am, 12 am and 4 pm for example) and then obtain the median time using `percentiles =`. I know I could obtain this result by performing separate travel time for each time departure and then calculating the median value, but of course, it would be great if there was a more efficient way to do it.

**Comment by rafapereirabr** [comment]
Hi @Ramon-88 . We're glad to hear you find the `r5r` package useful. Currently, there is no way to calculate trip distance by public transport in `r5r`. Does this answer your question?

**Comment by Ramon-88** [comment]
Hi @rafapereirabr, thanks for your answer.

I think I didn't clearly explain my question. In r5r we can calculate a travel distance matrix with transit mode as below:

mode <- "TRANSIT"
departure_datetime <- as.POSIXct("01-03-2023 10:00:00", format = "%d-%m-%Y %H:%M:%S")
`ttm <- travel_time_matrix(r5r_core = r5r_network,
                                  origins = points,
                                  destinations = points,
                                  mode = mode,
                                  departure_datetime = departure_datetime)

In this case, I just used a specific departure date time. To account for the variation of travel times with transit we can compute "several travel time matrices with multiple departure times within a 60-minute window and retrieve the median travel time within that window" [](https://www.urbandemographics.org/post/r5r-fast-multimodal-transport-routing-in-r/?fbclid=IwAR3IjOJnIzBxf_nY4eOhyxN3Dt-_KUfS136dqnLztqcFCm-1DwwEtoXZ4ZQ)

That is to say:

 `departure_datetime <- as.POSIXct("01-03-2023 10:00:00", format = "%d-%m-%Y %H:%M:%S")
 time_window <- 120 # minutes
 percentiles <- 50`
``ttm <- travel_time_matrix(r5r_core = r5r_network,
                                  origins = points,
                                  destinations = points,
                                  mode = mode,
                                  time_window = time_window,
                                  percentiles = percentiles,
                                  departure_datetime = departure_datetime)`

I was wondering if there is the possibility to specify multiple departure times (let's say for each hour of the day) and then get the median travel time, or if it is possible to set the time_window differently so that it won't calculate a travel time matrix for each minute, but let's say one every 20 minutes.

**Comment by mvpsaraiva** [comment]
Hi @Ramon-88. Currently, the only way to do what you need is manually, as you already answered in your question: "performing separate travel time for each time departure and then calculating the median value".

The way `time_window` works internally allows for some optimization by reducing the number of necessary steps to calculate all travel times over the specified period (R5 reuses some of the calculations to do that). But that only works on a minute by minute basis, so there are no gains to be obtained for larger time steps.
