### ISSUE TITLE
GTFS feed and Java error

### ISSUE THREAD

**Issue by manneolfv** [ipeaGIT/r5r#324]
Hello,

I'm learning the r5r package at the moment and this time I'm interested in calculating travel times between multiple points, This is the first time I'm working with GTFS feeds.

I've managed calculating travel times with car as transport mode. But It doesn't work for me when I set the mode as walk and transit.

I've downloaded a pbf file through geofabrik, and I also downloaded some gtfs feeds relevant for the region. 

When running the code with walk and transit as mode I get following error:

"Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Taxi service not supported1501"

I've googled some about this issue but could find a solution that worked for me. 

Anyone encountered the same issue or might have a possible solution to this problem?

Thanks

**Comment by rafapereirabr** [comment]
It looks like your GTFS feed has routes with Taxi transport mode, which is nor supported by R5. Can you please check this?

**Comment by manneolfv** [comment]
Thanks for the quick response.

Yes, it includes some routes that is classified as taxi. Is it possible to code these as bus instead? The routes with taxi is for smaller bus routes which needs a booking in advance for some more rural areas.

**Comment by rafapereirabr** [comment]
yes, you could probably recode those routes types, by assigning a different code to `route_type`. The code for buses is `3` ([reference](https://developers.google.com/transit/gtfs/reference#routestxt)).
