### ISSUE TITLE
Is it possible to get isochrones from R5?

### ISSUE THREAD

**Issue by EvandroStk9** [ipeaGIT/r5r#328]
Hello everyone,

I'm trying to get isochrones from r5r outputs. I've seen this [tutorial here](https://cran.r-project.org/web/packages/r5r/vignettes/calculating_isochrones.html) on the Porto Alegre Data. However, I have some doubts on how could I get an isochrone of an specific trip duration from an specific point of interest.

Is it possible to get isochrones directly from a R5 call? Or is it mandatory to get a result from a grid settled up by the user in a travel time matrix and then operate an interpolation procedure? Or, at least, is it possible to retrieve the smooth polygon created by the geom_contour_filled as an sf or an dataframe object?

Thanks!

**Comment by rafapereirabr** [comment]
Hi @EvandroStk9 . This issue is related to #123 . We have developed this [`isochrone()`](https://github.com/ipeaGIT/r5r/blob/master/r-package/tests/tests_rafa/isochrone.R) function. You can use it as a separate function, but it has not been implemented in `r5r` yet. Please let us know if you find any issues in this function or if yuo have any suggestions on how to improve it.

**Comment by EvandroStk9** [comment]
Thank you for the quick and kind answer @rafapereirabr. I tried on using the function and worked beautifully.

I will use it more and I'll let you know of any other doubts or possible improvements. Congratulations for this amazing r5r project!

**Comment by rafapereirabr** [comment]
Hi Hi @ichsan2895 . Please read this answer.

> Hi @EvandroStk9 . This issue is related to #123 . We have developed this [`isochrone()`](https://github.com/ipeaGIT/r5r/blob/master/r-package/tests/tests_rafa/isochrone.R) function. You can use it as a separate function, but it has not been implemented in `r5r` yet. Please let us know if you find any issues in this function or if yuo have any suggestions on how to improve it.

**Comment by rafapereirabr** [comment]
Ah, sure. Yes, we can add a `sample` parameter so that the user can set the sample size with the number of nodes/destinations to query.

**Comment by rafapereirabr** [comment]
New isochrone function added in #[7f50df1](https://github.com/ipeaGIT/r5r/commit/7f50df1b9ee8de17bfe4ebf8d9c4d6dba0250d73).

**Comment by rafapereirabr** [comment]
We'll continue the discussion of an isochrone function in issue https://github.com/ipeaGIT/r5r/issues/123.
