### ISSUE TITLE
Itineraries calculated between two identical points

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#33]
If you send the same dataset to `origins` and `destinations` in `detailed_itineraries` you still get itineraries, even though origins and destinations are literally the same points.

In OTP, at least using the API, if you try to calculate a route between two identical points it returns an error "origin and destination is within trivial distance". Apparently R5 doesn't do so. Should we account for that within the jar?

Reproducible code:

```r
# build transport network
data_path <- system.file("extdata", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)

# load and set origin/destination points
points <- read.csv(file.path(data_path, "poa_hexgrid.csv"))

origins <- head(points, 5)
destinations <- origins 

# input
mode = c('WALK', 'TRANSIT')
departure_time <- "14:00:00"
trip_date <- "2019-03-15"
max_street_time <- 30L

df <- detailed_itineraries(r5r_core,
                           origins,
                           destinations,
                           mode,
                           trip_date,
                           departure_time,
                           max_street_time)
```
```
> df
Simple feature collection with 5 features and 6 fields
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: -51.21271 ymin: -30.1031 xmax: -51.15632 ymax: -30.0542
geographic CRS: WGS 84
                          request option segment mode duration route                       geometry
1 89a901291abffff_89a901291abffff      1       1 WALK      258       LINESTRING (-51.15632 -30.0...
2 89a9012a3cfffff_89a9012a3cfffff      1       1 WALK      696       LINESTRING (-51.20871 -30.0...
3 89a901295b7ffff_89a901295b7ffff      1       1 WALK       50       LINESTRING (-51.16491 -30.0...
4 89a901284a3ffff_89a901284a3ffff      1       1 WALK       64       LINESTRING (-51.20779 -30.0...
5 89a9012809bffff_89a9012809bffff      1       1 WALK       80       LINESTRING (-51.19664 -30.0...
```

**Comment by dhersz** [comment]
This is not something related to the recent changes in the jar. Yesterday, before updating my local repo, I accidentally calculated the routes between all the points in the sample csv and their own selfs, and there were trips as long as a 20 minutes car ride. Pic below shows that there are some fairly long trips.

![image](https://user-images.githubusercontent.com/1557047/90650179-eefb7600-e211-11ea-9a66-eb8309062220.png)

**Comment by mattwigway** [comment]
What version of r5 are you using? This looks suspiciously like conveyal/r5#287 . For car mode, this could conceivably be due to linking to one-way streets as well; if the two edges are linked to a one-way street, results might be forced to drive around the block to get back to where they started. In any case, results will require traveling to the nearest street and back - and I doubt that will change in R5.

**Comment by rafapereirabr** [comment]
We are using update versions of both `r5r` and `R5`. @dhersz , does this problem still persist ?

**Comment by dhersz** [comment]
Apparently, yes. Check the example below for walking trips. It is less pronounced with walking trips than with car trips, probably because one-way streets that require driving around the block don't affect walking trips. If I understood @mattwigway's comment correctly, this is snapping-to-grid related, right?

```r
library(r5r)
library(ggplot2)

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path, verbose = FALSE)

points <- read.csv(system.file("extdata/poa/poa_hexgrid.csv", package = "r5r"))
origins <- destinations <- points
mode <- "WALK"
max_walk_dist <- 10000
max_trip_duration <- 600
departure_datetime <- as.POSIXct("13-05-2019 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

det <- detailed_itineraries(r5r_core = r5r_core,
                            origins = origins,
                            destinations = destinations,
                            mode = mode,
                            departure_datetime = departure_datetime,
                            max_walk_dist = max_walk_dist,
                            max_trip_duration = max_trip_duration,
                            shortest_path = FALSE)

ggplot(det) + geom_sf()
```

![image](https://user-images.githubusercontent.com/1557047/108558493-bcbdf480-72d8-11eb-803c-5d24f0d83b12.png)

**Comment by rafapereirabr** [comment]
It seems this is indeed related to the point snap. If this is the case, this is a feature (or bug?) upstream in R5 really, and there is not much we can do about it in the `r5r` package

**Comment by rafapereirabr** [comment]
This is a feature upstream in R5 really, so I suggest we close this issue here.

**Comment by mvpsaraiva** [comment]
I was looking into this, and I think the only thing we could do is add a test to check if both coordinates are the same, in R, before calling `planSingleTrip()` from Java. But I don't know if it's worth it or even desirable. The way it is now, the user gets this 'nonsensical' result and can clearly see there's something wrong with the input. If, instead of that, we return an empty data.table, it can be harder to understand what went wrong.

I also vote to close this issue.

**Comment by rafapereirabr** [comment]
Closing this one for now.
