### ISSUE TITLE
Error: unused argument (suboptimal_minutes=)

### ISSUE THREAD

**Issue by elmiraberjisian** [ipeaGIT/r5r#330]
Thank you for your very useful package. I am trying to generate multiple transit route alternatives via detailed_itineraries (). Using the result, I then calculate new cost for each route by using customized penalty values for waiting, transfer, etc. I have no problem using the function when setting shortest_path=FALSE but when I want to increase the generated options returned by setting suboptimal_minutes=120 , the function throws the error: "Error in detailed_itineraries(r5r_core, origins = , destinations =   : 
  unused argument (suboptimal_minutes = 120)"

**OSM and GFTS**
the URL for GFTS.zip: https://transitfeeds.com/p/translink-vancouver/29/latest/download 
OSM from https://extract.bbbike.org/?lang=en;sw_lng=-123.423063;sw_lat=49.004383;ne_lng=-122.30486;ne_lat=49.474111;format=osm.pbf

**Example of my code**

 det <- detailed_itineraries(r5r_core,
                              origins = c(49.28746,-123.117),
                              destinations =c(49.27432, -122.8231),
                              mode = c("RAIL"),
                              departure_datetime = as.POSIXct("11-12-2017 16:00:00",format = "%d-%m-%Y %H:%M:%S"),
                              suboptimal_minutes=120L,
                              shortest_path = FALSE, #be careful  the max trip duration set as inf doesnt work and return empty 
                              drop_geometry = FALSE,
                              verbose=FALSE,
                              progress=FALSE,
                              max_walk_dist=Inf)

**Comment by rafapereirabr** [comment]
Hi @elmiraberjisian . Could you please run the `r5r::r5r_sitrep()` function to generate a situation report, and paste the output along with your issue? This will help us find eventual bugs.

**Comment by rafapereirabr** [comment]
On a side note, please note there's a subtle difference between  `detailed_itineraries()` and `expanded_travel_time_matrix()`:

- `detailed_itineraries()` 
When one uses the `detailed_itineraries()` function with the `suboptimal_minutes = x` parameter, the function returns the **optimal** and the **suboptimal** trip alternatives which arrive up to `x` minutes after the arrival of the optimal trip.

- `expanded_travel_time_matrix()`
Meanwhile, when one uses the`expanded_travel_time_matrix()` with the  `time_window = w`, the function returns the **optimal** trips departing every minute in the time window given by departur time + `w`.  

I'd like to stress these differences to make sure you get the output desired. In any case, the `expanded_travel_time_matrix()` function is much more efficient / faster than `detailed_itineraries()`.

**Comment by elmiraberjisian** [comment]
Hello @rafapereirabr Thank you for your input. I think detailed_itineraries() is actually what I am interested in to  create an alternative set with a fixed departure time. With regards to issue, when I updated the package sounds like it has resolved the issue as I didnt get the same error as mentioned. Thank you very much!
