### ISSUE TITLE
`TripPlanner.findDirectPaths()` does not support multiple direct modes

### ISSUE THREAD

**Issue by christophfink** [ipeaGIT/r5r#332]
### Brief description of the problem:
`FastDetailedItineraryPlanner` does not give multimodal results that combine different direct modes, e.g., cycling and car. 
Rather, [`TripPlanner.findDirectPaths()`](https://github.com/ipeaGIT/r5r/blob/7880b25bbda8b6c8eccb45bfd6f0518a5a7fdf32/java-r5rcore/src/org/ipea/r5r/Planner/TripPlanner.java#L128) loops over the modes, trying one at a time.

### Reproducible example
```r
library(r5r)
data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path)
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

departure_datetime <- as.POSIXct(
  "13-05-2019 14:00:00",
  format = "%d-%m-%Y %H:%M:%S"
)

det <- detailed_itineraries(
  r5r_core,
  origins = points[10,],
  destinations = points[12,],
  mode = c("CAR", "BIKE", "WALK"),
  departure_datetime = departure_datetime,
  max_trip_duration = 60
)
```

### Situation report
```r
> r5r::r5r_sitrep()
$r5r_package_version
[1] ‘1.0.1’

$r5_jar_version
[1] "6.9"

$java_version
[1] "11.0.18"

$set_memory
[1] "-Xmx512m"

$session_info
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.11.0
LAPACK: /usr/lib/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_GB.UTF-8           LC_COLLATE=en_GB.UTF-8       
 [5] LC_MONETARY=en_GB.UTF-8       LC_MESSAGES=en_GB.UTF-8      
 [7] LC_PAPER=en_GB.UTF-8          LC_NAME=en_GB.UTF-8          
 [9] LC_ADDRESS=en_GB.UTF-8        LC_TELEPHONE=en_GB.UTF-8     
[11] LC_MEASUREMENT=en_GB.UTF-8    LC_IDENTIFICATION=en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.3    r5r_1.0.1         data.table_1.14.8 rJava_1.0-6 

```

**Comment by mvpsaraiva** [comment]
Hi @christophfink. That's the default behaviour of R5, and I just replicated it in `FastDetailedItineraryPlanner`. Actually, I don't know what alternative behaviour we could implement. How can we combine multiple direct modes in a meaningful way?

**Comment by christophfink** [comment]
Hi @mvpsaraiva! Since creating this issue, I’ve come to learn myself that this is a limitation upstream, and R5’s `StreetRouter` does not support using multiple ‘direct’ transport modes in the same trip. Not sure whether we should ask Conveyal about this? Surely they would have an interest in supporting multimodal individual transport in their own product?

**Comment by rafapereirabr** [comment]
Hi Christoph!

My understanding is that R5 understand the **direct mode** as the main mode used in the trip, while  **indirect mode** are the modes used to access to / egress from the main mode. Following this understanding, it does not make sense to combine two "direct" modes. The moment one combines two or more modes, only one mode can be the main one.

Having said this, my understanding is that R5 already allows for multimodal trips in the sense that (1) it allows for combinations / transfers between different public transportation modes, and (2) it allows one to consider different combinations of modes such as:

- 🚶‍♀️ + 🚍 + 🚴
- 🚴 + 🚍 + 🚶‍♀️
- 🚴 + 🚍 + 🚴

**Comment by mvpsaraiva** [comment]
What would be the use case for this feature? If you're thinking on bike rental schemes or using a car park along the way, R5 has built in modes for that. However, we didn't implement those modes in r5r because we couldn't find an easy way to expose them to the user, since they require additional data. 

Or are you thinking on a different use case?

**Comment by christophfink** [comment]
Maybe the use case I am thinking about is too niche: rather than taking the shortest possible access route to the closest possible street segment accessible to `directMode`, the over-all route can be shorter and faster if, e.g., one walks or cycles to a car park on the other side of a pedestrianised city centre. This is especially relevant for commuter connections in western Europe, I would assume. 

If it’s not mainstream enough to consider, let’s close this issue

**Comment by rafapereirabr** [comment]
Ok, thanks for the clarification Christoph. Closing this issue for now
