### ISSUE TITLE
Controlling snapping distance and walking speed used for the covered snapping distance

### ISSUE THREAD

**Issue by Mponkane** [ipeaGIT/r5r#337]
Hi,

In the documentation it stated that:
"The snapping process in R5 is composed of two rounds. First, it tries to snap the points within a radius of 300 meters from themselves. If the first round is unsuccessful, then R5 expands the search radius to 1.6 km. If yet again it is unsuccessful, then the unsnapped points won’t be used during the routing process. The snapped location of each point depends on the transport mode set by the user, because some network edges are not available to specific modes (e.g. a pedestrian-only street cannot be used to snap car trips)."

My understanding is that R5 accounts for this by using walking speed for the ‘as the crow flies’ distance covered between the original location and the snapped location. This walking speed that is used to account for the crow flies distance is probably something hardcoded at the backend, to be the default walking speed? I.e., you can’t customize the speed used for covering the crow flies distance?  I am running some tests for cycling accessibility and they appear to be unaffected for the snapped locations, when I try to modify walking speed. This is particularly troublesome if I am to model walking distances where I want to apply even lower walking speed than the default, lets say to simulate mobility of elderly folk. 

Also I assume you can't control the snapping distance itself within r5r? Depending on the scenario and granularity of your origin points this can make quite a difference especially in small scale analysis. Of course one option is always to prepare O/D dataset manually to not include locations that a certain distance away from the network.

**Comment by rafapereirabr** [comment]
Hi @Mponkane .

Yes, this is how the snapping process operates [as we gather from R5 code](https://github.com/conveyal/r5/blob/dbcc567a8fea9b5ef07fcad588e8268f3a23f9d4/src/main/java/com/conveyal/r5/streets/StreetLayer.java#L113). Unfortunately, we can't control the snapping distance from within r5r. 

Regarding your question:
> "This walking speed that is used to account for the crow flies distance is probably something hardcoded at the backend, to be the default walking speed? I.e., you can’t customize the speed used for covering the crow flies distance? I am running some tests for cycling accessibility and they appear to be unaffected for the snapped locations, when I try to modify walking speed."

I assume the `walk_speed` parameter would affect the travel time during that crow fly strip of the trip created by in snap process. Would you have any reproducible example that we could use to test this?

**Comment by Mponkane** [comment]
Sorry for the late reply, for me in terms of the snap distance, this:

```
options(java.parameters = "-Xmx10G")
library(r5r)
library(sf)
library(dplyr)

setwd("path")

data_path <- system.file("extdata/oulu", package = "r5r")

r5r_core <- setup_r5(data_path = data_path)

origin <- st_read("origin.shp")
destination <- st_read("destination.shp")
destination$opportunities <- 1

# calculate accessibility
access <- accessibility(r5r_core = r5r_core,
                        origins = origin,
                        destinations = destination,
                        mode = c("BICYCLE"),
                        max_lts = 1,
                        walk_speed = 0.1, # Notice the walk_speed
                        bike_speed = 16,
                        decay_function = "step",
                        cutoffs = 15
)

```

Produces exactly the same result as this one:

```
options(java.parameters = "-Xmx10G")
library(r5r)
library(sf)
library(dplyr)

setwd("path")

data_path <- system.file("extdata/oulu", package = "r5r")

r5r_core <- setup_r5(data_path = data_path)

origin <- st_read("origin.shp")
destination <- st_read("destination.shp")
destination$opportunities <- 1

# calculate accessibility
access <- accessibility(r5r_core = r5r_core,
                        origins = origin,
                        destinations = destination,
                        mode = c("BICYCLE"),
                        max_lts = 1,
                        walk_speed = 3.6, # Notice the walk_speed
                        bike_speed = 16,
                        decay_function = "step",
                        cutoffs = 15
)
```
It produces exactly the same result. Below you can see picture for the lower walking speed (0.1 km/h) result, where at least one opportunity is reachable. The distance from a origin cell to closest network part is around 500 meters. 
The points that you can see in the picture are the central coordinates of each cell. I am running version 1.0.1
![image](https://github.com/ipeaGIT/r5r/assets/105248249/ce5ce97a-495a-4250-b650-a22544ec7401)
