### ISSUE TITLE
Definition of percentiles and travel time uncertainty in r5r

### ISSUE THREAD

**Issue by FatemehJanat** [ipeaGIT/r5r#339]
Hello everyone!
What does travel-time uncertainty used in r5r mean? What is the difference between the 5th percentile and the 95th percentile access to employment? It seems access calculated by the 5th percentile is higher than the 95th percentile. Why? What variables affect this difference (e.g., service frequency, number of transfers)?

**Comment by rafapereirabr** [comment]
Hi @FatemehJanat .

We would strongly encourage you to read the vignette on [Using the time_window parameter](https://ipeagit.github.io/r5r/articles/time_window.html). 

In summary, travel time uncertainty occurs when the travel time from A to B departing at time X is not deterministic (constant). This travel time can vary depending on variations in the dispatch time of vehicles for planned trips and service frequency, for example. The vignette points to two papers that provide a detailed explanation of travel time uncertainty and its implications for uncertainty in accessibility estimates.

- Conway, Matthew Wigginton, Andrew Byrd, and Michael van Eggermond. 2018. “Accounting for Uncertainty and Variation in Accessibility Metrics for Public Transport Sketch Planning.” Journal of Transport and Land Use 11 (1). https://doi.org/10.5198/jtlu.2018.1074.
- Stewart, Anson F, and Andrew M Byrd. 2022. “Half-(Head)way There: Comparing Two Methods to Account for Public Transport Waiting Time in Accessibility Indicators.” Environment and Planning B: Urban Analytics and City Science, November, 23998083221137077. https://doi.org/10.1177/23998083221137077


As explained on the vignette, when we calculate travel time using the `time_window` parameter, we simulate multiple trips departing at differement departure times within that time window. Some trips might be shorter (e.g. 15 minutes) while other trips might be longer (e.g. 30 minutes). The result is actually a distribution of trips and travel times. When we rank these trips from the fastest to the slowest, we can calculate percentiles and say for example that the 5th percentile is 18 minutes. This is equivalent to say that the 5% fastest trip can 18 minutes at the most.

I hope this is clearer. If you find that any particular sentence of paragraph of the vignette needs clarification, please let us know.

**Comment by rafapereirabr** [comment]
Closing this issue for now. Happy to reopen it if necessary
