### ISSUE TITLE
.pbf file to be used in r5r.

### ISSUE THREAD

**Issue by MarcelaBranco** [ipeaGIT/r5r#340]
Regarding r5r, the road network needs to be in .pbf format. In the vignette, an example using r5r was given with a .pbf file for the city of Porto Alegre. I obtained the dataset from Geofabrik with the file sudeste-latest.osm.pbf, but I want to obtain the road network for a specific city in Brazil. In this case, please, how can I extract only the road network for this city from the sudeste-latest.osm.pbf file? Thank you in advance for your attention.

**Comment by rafapereirabr** [comment]
Hi @MarcelaBranco . You need to get the bounding box of the city you are analyzing to crop the `sudeste-latest.osm.pbf` file. I believe you can do this [JOSM](https://wiki.openstreetmap.org/wiki/JOSM), and I am certain you can do this using [Osmosis](https://wiki.openstreetmap.org/wiki/Osmosis).

If you use osmosis, you can do this from within R. You need to donwload the `osmosis` to your computer. The latest releases can be downloaded from [here](https://github.com/openstreetmap/osmosis/releases). Next, you can use this step-by-step below:

```
# get the bounding box of your study area
study_area_polygon <- geobr::read_state(code_state = "ES")
area_bbox <- sf::st_bbox(study_area_polygon)

# input: the path to osmosis and the large pbf file in your local computer
osmosis_path <- "./osmosis_dir/bin/osmosis.bat"
large_pbf_path <- "./project_dir/large.pbf"

# path where you want to save the smaller .pbf file
smaller_pbf <-"./project_dir/smaller.pbf"

# prepare call to osmosis
osmosis_cmd <- sprintf("%s --read-pbf %s --bounding-box left=%s bottom=%s right=%s top=%s --write-pbf %s",
                       osmosis_path, large_pbf_path, 
                       area_bbox@xmin, area_bbox@ymin, area_bbox@xmax, area_bbox@ymax,
                       smaller_pbf)

# call to osmosis
shell(osmosis_cmd, translate = TRUE)
```

**Comment by MarcelaBranco** [comment]
Thank you.
