### ISSUE TITLE
Distinguish between waiting time and transfer time

### ISSUE THREAD

**Issue by Torskelgen** [ipeaGIT/r5r#341]
Hi! Perhaps not the most substantial request but could I suggest that you specify in the documentation of particularly expanded_travel_time_matrix() the distinction between waiting time and transfer time? It is not obvious that transfer time does not include the waiting time during transfers. I assumed the other day that waiting time only applied to the first stop/station. Then I remembered how waiting time can be distributed among the trip legs in detailed_itineraries().

My initial suggestion/hope was to single out the waiting time at the first stop/station in the results from expanded_travel_time_matrix() – on trips with multiple in-vehicle trip legs – but that does not look feasible based on my brief look at Conveyal's documentation.

**Comment by rafapereirabr** [comment]
Hi @Torskelgen . Thanks for opening this issue. Could you please point us to the exact part of R5 code indicating that transfer time does not include the waiting time during transfers?

ps. mind you that the routing algorithm behind `expanded_travel_time_matrix()` and `detailed_itineraries()` are different, so they could be treating waiting time / transfer times differently.

**Comment by rafapereirabr** [comment]
closing due to lack of response. Happy to reopen the issue if necessary
