### ISSUE TITLE
Modifying max bike speeds

### ISSUE THREAD

**Issue by AGardelli** [ipeaGIT/r5r#344]
Hi, I see that there are some open issues on the possibility to modify max car speed on specific routes but I was wondering if that possibility may be applied also to bike speeds. Assuming LTS = 3 for example, I imagine higher speeds on cycle lanes and/or residential streets than secondary roads let's say. Any idea on how to do that, maybe modifying/adding tags on the original .pbf file?

Many thanks

**Comment by rafapereirabr** [comment]
Hi @AGardelli . As far as I understand from [R5's documentation](https://docs.conveyal.com/), LTS affects routing choices but not cycling speeds, which are affected by terrain elevation though. 

Regarding your question on how to modifying/adding tags on the original .pbf file, please refer to question [#2 of our FAQ](https://ipeagit.github.io/r5r/articles/faq.html)
