### ISSUE TITLE
java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.

### ISSUE THREAD

**Issue by dias-bruno** [ipeaGIT/r5r#345]
I'm trying to calculate a travel time matrix for some points in Santarem, Brazil, but I'm having trouble connecting to r5r: _java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted._

**Input files:** 
PBF road network: Extracted the OSM road network in shapefile, clipped to my study area, and saved in .pbf using JOSM.
Points: santarem_grade.csv
Topography: a .tif raster file with the elevation of the study area 

**The code:**
options(java.parameters = "-Xmx10G")
library("r5r")
folder = "C:\\Users\\brdia\\Desktop\\course_accessibility\\santarem"
connection_r5r <- setup_r5(folder, verbose = FALSE, elevation = "TOBLER")
fs::dir_tree(folder)

**Output error:** 
> connection_r5r <- setup_r5(folder, verbose = FALSE, elevation = "TOBLER")
Using cached R5 version from C:/Users/brdia/AppData/Local/R/win-library/4.3/r5r/jar/r5-v6.9-all.jar
Error in setup_r5(folder, verbose = FALSE, elevation = "TOBLER") : 
  java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.

**The dataset I am using can be accessed at this drive link:** https://drive.google.com/drive/folders/1rn9jkDlCDzLAy1kQtoyZvfzoPJLoCVek?usp=sharing

**Comment by rafapereirabr** [comment]
Hi @dias-bruno. I assume you are able to run the some of the  reproducible examples provided in the package, right?

As far as I know, once you extract OSM data into shape file format, the tags / metadata are lost. I suspect this is what's causing the error. I would suggest you have a look at the [question 4 in our FAQ](https://ipeagit.github.io/r5r/articles/faq.html), which shows how to crop a OSM.pbf data file to smaller areas.

**Comment by dias-bruno** [comment]
Hi @rafapereirabr, you're right. I tested again using a .pbf file provided by OSM, and it worked. Thank you for your quick response.
