### ISSUE TITLE
Send trip_date and departure_time as the same argument trip_departure_time?

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#35]
Right now both detailed itineraries and travel time matrix functions have two separate arguments `trip_date` and `departure_time`, strings with specific formatting options.

We could maybe unify these two string arguments into a single POSIX one, and make any necessary conversions to suit R5 usage inside the functions. What do you think?
I think it would lower the chances of the users passing invalid arguments to the functions and would simplify validity checks as well.

**Comment by dhersz** [comment]
Created function `posix_to_string` which creates a list with the relevant strings (date and time) from a POSIXct. I'm using it in `detailed_itineraries`. Here's a example:

```r
# build transport network
data_path <- system.file("extdata", package = "r5r")
r5r_core <- setup_r5(data_path = data_path)

# load and set origin/destination points
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

origins <- points[10,]
destinations <- points[12,]

# inputs
mode = c("WALK", "BUS")
max_walk_dist <- 1
departure_datetime <- as.POSIXct("13-03-2019 14:00:00",
                                 format = "%d-%m-%Y %H:%M:%S")

df <- detailed_itineraries(r5r_core,
                           origins,
                           destinations,
                           departure_datetime,
                           max_walk_dist,
                           mode)
```

**Comment by rafapereirabr** [comment]
Good! I've now implemented this in the `travel_time_matrix` function.
