### ISSUE TITLE
install Java SE Development Kit 21 

### ISSUE THREAD

**Issue by LinhLTP** [ipeaGIT/r5r#365]
Hi everyone, 

I begin using R5R for my work. Below is the message I received when installing the R5R package.

![image](https://github.com/ipeaGIT/r5r/assets/61450812/37f38aa2-a862-4d31-9f94-0d4f8426207b)

Next, I downloaded the Java (image attached) from https://jdk.java.net/java-se-ri/21 but to be honest I don't know how to install it. I checked every folders and they contain so many files. Could anyone give me some help which file I should use for installation? 

![image](https://github.com/ipeaGIT/r5r/assets/61450812/46061a02-f345-4b07-9a44-9a500330ff04)

Thank you so much!

Best!

**Comment by rafapereirabr** [comment]
how did you install `r5r`? Did you install it from CRAN?

Also, could you please run `r5r::r5r_sitrep()` and share the output in a comment below?

**Comment by rafapereirabr** [comment]
You see, `r5r::r5r_sitrep()` indicates that you have jdk 21 installed. The current version of r5r on CRAN only works with jdk 11. So you have two options:
1) either unistall jdk 21 and install jdk 11
2) install the dev version of r5r, which works with jdk 21

**Comment by LinhLTP** [comment]
> You see, `r5r::r5r_sitrep()` indicates that you have jdk 21 installed. The current version of r5r on CRAN only works with jdk 11. So you have two options:
> 
> 1. either unistall jdk 21 and install jdk 11
> 2. install the dev version of r5r, which works with jdk 21

Thank you so much! I have successfully downloaded r5r with option 2.

**Comment by rafapereirabr** [comment]
glad to hear it worked. Closing this issue for now
