### ISSUE TITLE
Simplify JDK download instructions

### ISSUE THREAD

**Issue by mattwigway** [ipeaGIT/r5r#366]
The download instructions on https://ipeagit.github.io/r5r/ for the JDK are currently somewhat confusing to someone not well versed in Java. We currently link to two pages for getting the JDK:

- https://jdk.java.net/java-se-ri/21 and
- https://docs.oracle.com/en/java/javase/21/install/index.html#Java-Platform%2C-Standard-Edition

neither of which actually provide a JDK download anymore. I think we should pick one of the three open source JDK implementations, and just link to that. Anyone who has a preference for what JDK to use is going to ignore these instructions anyways. The three I'm familiar with are:

- Eclipse Temurin: https://adoptium.net/
- Amazon Corretto: https://aws.amazon.com/corretto
- Oracle OpenJDK: https://jdk.java.net/21/

I am usually running either Temurin or Corretto on my machines, I haven't touched anything from Oracle in years. Conveyal uses Corretto to run the R5 test suite.

**Comment by mattwigway** [comment]
Adoptium/Temurin might be the best choice as it autodetects platform/architecture so people won't have difficulty if they don't know what CPU they have.

**Comment by rafapereirabr** [comment]
Hi Matt. These are great suggestions. I'm happy with recommending Temurin, but I wouldn't see a problem in simply mentioning other implementations and linking to them

**Comment by mattwigway** [comment]
I'm not sure why the auto builder rebuilt the jar for the pull request -
will investigate.
