### ISSUE TITLE
2024-02-16 15:47:03,836 [ForkJoinPool.commonPool-worker-3] ERROR c.c.r.s.IntHashGrid - Visiting too many spatial index cells.

### ISSUE THREAD

**Issue by 19929692** [ipeaGIT/r5r#370]
Trying to run an accessibility code on R and came across this error message "2024-02-16 15:47:03,836 [ForkJoinPool.commonPool-worker-3] ERROR c.c.r.s.IntHashGrid - Visiting too many spatial index cells" however, I have changed CRS to WGS84,4326 but still ecnountering same thing. Need help with this

**Comment by 19929692** [comment]
@rafapereirabr

**Comment by rafapereirabr** [comment]
could you please share the code you're using, ideally with a repreoducible example of the error?

**Comment by rafapereirabr** [comment]
Where exactly does the error occur in your code?

When you run `accessibility()`, do you get any results?

From your code above, it looks to me the error occurs when you try to save the plot with `ggsave()`

**Comment by 19929692** [comment]
access_walk_df <- accessibility(r5r_core,
                                origins = od_points_sf,
                                destinations = od_points_sf,
                                mode = c("WALK"),
                                opportunities_colname = "jobs",
                                departure_datetime = as.POSIXct("02-03-2022 09:00:00", format = "%d-%m-%Y %H:%M:%S"),
                                cutoffs = c(15, 30, 60, 90),
                                verbose = FALSE)
After running this part it gave an error on memory capacity. I never went pass this.  I just gave all the codes so you will get an idea of the structure of the code

**Comment by rafapereirabr** [comment]
the message says you don't have enough RAM. So here are a couple questions:
a. how much ram do you have?
b. how many origin and destinations points do you have?

If your data set is too big to your RAM, I would suggest trying the `output_dir` parameter. Check the [function documentation](https://ipeagit.github.io/r5r/reference/accessibility.html) to see how it works.

**Comment by 19929692** [comment]
Thanks for this really grateful. Sorry to bother you. I have the codes again. However, the network, base map and opportunities have been loaded in to R successfully but once I run the accessibility code it doesn't bring any result.  see image.
![image](https://github.com/ipeaGIT/r5r/assets/157746648/a7a0ce51-e1a0-4422-aa80-247660c61bb4)

**Comment by rafapereirabr** [comment]
can you please plot the origin/destination points on top of the network map you're showing above?

**Comment by 19929692** [comment]
You mean opportunity points ?

**Comment by 19929692** [comment]
Just to be  open sir.. I am a student running an accessibility check for a specific group of population in London. New to the approach and a big fan of the ideology here. But I am having challenges in getting this right. I feel there is something missing. SO I would like to know the following answers to these questions;
1. The destinations means the opportunities ?
2.  Will the GTF data be loaded in R or once I run the transit network code it automatically picks it up in the file via the path ?
3. how many file am i loading in R. At the moment I have loaded; London based map, points of opportunities, and also the transit network data
I will appreciate if your feedback can outline the step by step procedure on how to go with this.. I have just few days for the presentation. Thank you sir.

**Comment by rafapereirabr** [comment]
1. Yes, I mean the `od_points_sf`. It is important to plot them on the map to make sure they are correctly located in you area of study
2. yes, when you run `setup_r5(data_path)`, the package will automatically detect all gtfs feeds in your `data_path`.
3. No sure I understand you question here.

There are several step-by-step demonstrations on how to use the package documented on the vignettes of `r5r`. See the [package website](https://ipeagit.github.io/r5r/articles/accessibility.html).

**Comment by 19929692** [comment]
Thank you. I have plotted the accessibility.. Because the dataframe does not have a geometry property I would merge the id with the id of the MSOA

**Comment by rafapereirabr** [comment]
Glad to hear it worked. closing this issue for now.
