### ISSUE TITLE
Trouble Installing R5R in R: Fatal error

### ISSUE THREAD

**Issue by Erwinpuntnl** [ipeaGIT/r5r#377]
Hello everyone,

I am currently facing an issue while attempting to install R5R in R (on MacOS, ARM). Here's a brief overview of what I've been trying to accomplish: I aim trying to install R5R in R for my project. I've attempted two different forms of code to achieve this:

`options(java.parameters = "-Xmx8G")`
`library(r5r)`
`data_path <- "/my/data/path"`
`r5r_core <- setup_r5(data_path = data_path)`

Alternatively, I've also tried using the stored GTFS and OSM data within the package:

`data <- system.file("extdata/poa", package = "r5r")`
`r5r_core <- setup_r5(data_path = data)`

However, regardless of which method I use, I consistently encounter the following error message: "R Session Aborted, R encountered a fatal error, the session was terminated." Unfortunately, there are no further error messages provided, leaving me uncertain about the root cause of the issue.

The setup starts running and the console says:
"No raster.tif found. Using elevation = 'NONE'
Using cashed R5 version from /Library/Frameworks/etc."
R Studio then crashes

To provide some context, I have included the following files in my project directory:
- GTFS.zip
- netherlands.osm.pbf (around 1gb, but smaller files don't work either)
I have only installed jdk-11 and no other versions of java.

Thank you in advance for your time and assistance!

**Comment by Erwinpuntnl** [comment]
I guess I've already fixed it by installing the devtools version and java SE 21:
`devtools::install_github("ipeaGIT/r5r", subdir = "r-package")`

**Comment by rafapereirabr** [comment]
ah, I'm glad to hear you have worked it out. I was going to say, this is likely an incompatibility issue between java 11 and some MacOs processors. See #315. Using java 21 and the dev version of r5r is exactly what I would have recommended.
