### ISSUE TITLE
Update required JDK version in Getting Started vignette

### ISSUE THREAD

**Issue by malcalakovalski** [ipeaGIT/r5r#380]
Hello! First of all, I'm a huge fan of this package and have benefited greatly from it. Thank you for all your work!

I noticed a small inconsistency in the documentation on the package website. In particular, the home page says that Java SE Development Kit 21 is required whereas the "Getting Started" vignette still mentions requiring Java SE Development Kit 11. 

Very minor, but wanted to flag that it might be confusing for folks to see both.

Thank you!

**Comment by rafapereirabr** [comment]
thanks for the heads up ! This is because the stable version of r5r on CRAN v1.1.0 used  JDK v11, and the documentation on github refers to the dev version, which uses JDK v21. I realize inconsistency can lead to some confusion and I'll fix this asap.

**Comment by malcalakovalski** [comment]
Got it, that makes complete sense! Thanks for looking into it.

**Comment by STBrinkmann** [comment]
Is there an issue in using v21. with the CRAN version? I just installed r5r using `install.packages('r5r')` and noticed that the `setup_r5` function stops if JDK version != 11

    if (ver != 11) {
        stop("This package requires the Java SE Development Kit 11.\n", 
          "Please update your Java installation. ", "The jdk 11 can be downloaded from either:\n", 
          "  - openjdk: https://jdk.java.net/java-se-ri/11\n", 
          "  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html")
      }

Using the development version does solve it for me.

**Comment by rafapereirabr** [comment]
> Is there an issue in using v21. with the CRAN version? I just installed r5r using `install.packages('r5r')` and noticed that the `setup_r5` function stops if JDK version != 11
> 
> ```
> if (ver != 11) {
>     stop("This package requires the Java SE Development Kit 11.\n", 
>       "Please update your Java installation. ", "The jdk 11 can be downloaded from either:\n", 
>       "  - openjdk: https://jdk.java.net/java-se-ri/11\n", 
>       "  - oracle: https://www.oracle.com/java/technologies/javase-jdk11-downloads.html")
>   }
> ```
> 
> Using the development version does solve it for me.

 This is because the stable version of r5r on CRAN v1.1.0 uses JDK v11, and the documentation on github refers to the dev version, which uses JDK v21. I realize this inconsistency can lead to some confusion and I'll fix this asap.

**Comment by rafapereirabr** [comment]
This issue is now fixed and r5r v2.0 is on CRAN

**Comment by malcalakovalski** [comment]
Amazing, thank you for fixing and for all your work on this truly incredible package!
