### ISSUE TITLE
convinient function to check Java version

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#387]
### Brief description of the problem:

In the documentation of r5r (vignettes, README, etc), we inform users they check what version of Java they have installed on their computer by running this on R console:

```
rJava::.jinit()
rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")
```

This is not a big deal, but we could provide a simple and convinient function to do the same. This would look like this:

```r
check_java_version <- function(){
  rJava::.jinit()
  rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")
}

r5r::check_java_version()
#> "21.0.1"
```

Super simple really. I'm not sure the function name should be `check_java_version()` or simply `java_version()`. What do you all think?

**Comment by e-kotov** [comment]
There seems to be no [`java_version`](https://www.rdocumentation.org/search?q=java_version) in any of the existing CRAN packages, `java_version` does not sound like a function, but more like a property or state.   [`check_java_version`](https://www.rdocumentation.org/search?q=check_java_version) is in [`pathfindR`](https://cran.r-project.org/package=pathfindR) package, but it is highly unlikely that an `r5r` user will ever find out about this conflict. I would suggest using `check_java_version`.

**Comment by rafapereirabr** [comment]
Thanks for sharing your thoughts, @e-kotov !

**Comment by e-kotov** [comment]
@rafapereirabr by the way, `opentripplanner` has `otp_check_java()` function
https://github.com/ropensci/opentripplanner/blob/e3db5fd8982d4f22154ce4a3a94ed023f23f253b/R/otp-setup.R#L522

**Comment by e-kotov** [comment]
@rafapereirabr Would it not be even better to have a function that installs Java for the user? It is often a big hassle to go and install a specific version of Java and manage several Java versions side by side on the same system. I would suggest choosing a Java distribution (e.g., [Corretto](https://aws.amazon.com/corretto/) from Amazon, Azul, or Temurin; many options are overviewed [here](https://whichjdk.com/)), getting the zipped/gzipped distribution, unpacking it locally in the project directory, and setting the environment inside R to point to JAVA_HOME before initializing Java.

When I work with `r5r`, `opentripplanner` or `graphhopper`, this is what I used to do by hand. Now I am working on a small R package to do that for me. Apart from several helper functions, the idea is to create a single simple function that just gets the required Java version working for user within the current project with reasonable defaults. Would you be interested to test an alpha version of it and perhaps integrate it with `r5r` in the future?

**Comment by stupidpupil** [comment]
Interesting @e-kotov . I use r5r and OTP a lot in GitHub actions and turn to https://github.com/actions/setup-java .

**Comment by e-kotov** [comment]
@stupidpupil thank you for the link! This seems super sophisticated and a lot to learn from.

**Comment by rafapereirabr** [comment]
Hi @e-kotov . I haven't tested `{rJavaEnv}` yet, but it looks super convinient and a much better solution than what I had initially in mind ! I'll be travelling over the next few weeks but I'll try to take it for a spin when I have time. Once `{rJavaEnv}` is on CRAN, I would be happy to suggest it to  `{r5r}` users in our package documentation, vignette and our next book (currently in progress).

**Comment by e-kotov** [comment]
@rafapereirabr great! There's no rush. I still have tests to write and I want to submit to rOpenSci for review and feedback, and then to CRAN.  So the later you will try it, the better it should be)

**Comment by e-kotov** [comment]
@rafapereirabr done, it's on ~~the AppStore~~ [CRAN](https://cran.r-project.org/package=rJavaEnv)!

```r
install.packages("rJavaEnv")
```

Due to CRAN policies, on first run I ask the user for consent. This can be skipped with additional command before the Java install command:

```r
rje_consent(provided = TRUE)
java_quick_install(version = 21)
```

**Comment by rafapereirabr** [comment]
Thanks for the heads up @e-kotov ! I just updated the website of the workshop! I guess we can close this issue ?

**Comment by rafapereirabr** [comment]
I've updated the `README` and intro vignette now.
