### ISSUE TITLE
Max Walk Time

### ISSUE THREAD

**Issue by hasanglr** [ipeaGIT/r5r#396]
Hi,

I've been trying to use max_walk_time parameter running a catchment. However, I think I didn't quite understand how it works. When I set 15 minutes threshold for walking and 50 minutes travel cut-off like this: 

_mode <- c("WALK", "TRANSIT")

**max_walk_time <- 15**

**travel_time_cutoff <- 50**  

time_window <- 50 # in minutes

percentiles <- 50_

Does 50 minutes cut-off include walk time as well or is it just public transit trip journey? My understanding is that one can walk max 15 minutes to reach the transit station, have 20 max minutes PT journey and 15 minute walk to reach the destination after leaving the transit. Previously we set 50 minutes for max walk time and it didn't produce very sensible result because I guess all destinations within 50 minute walk-only trips or 45 minute walk and 5 minute PT trips are captured, which is not very realistic at all. I'd be glad if you can explain a bit more and help me with this?

Many thanks!
Hasan

**Comment by rafapereirabr** [comment]
Hi @hasanglr . The `travel_time_cutoff` parameter includes the whole trip, including all legs / modes of the journey. It works like a maximum trip duration. 

The `max_walk_time` only affects the walk time access and egress the transit network. So in you example above, assume the person walks for 10 minutes to get to the transit station and her transit trip takes 30 minutes. This consumes 40 minutes of her total travel time budget of 50 minutes. This would leave her with only 10 more minutes to walk from final transit stop to her destination. 

Is this clearer now?

**Comment by hasanglr** [comment]
It is much clearer! Thanks very much

**Comment by rafapereirabr** [comment]
Ok, great! closing this issue for now.
