### ISSUE TITLE
Catchments at different times

### ISSUE THREAD

**Issue by hasanglr** [ipeaGIT/r5r#397]
Hi,

I've been trying to run catchment for London at different times of the day, such as midnight, off-peak and weekend midday. However, the result remained the exact same for all three even though I changed the departure_datetime parameter. I am also attaching calendar.txt file. I'd be glad if you can help me with that.
[Uploading calendar.txt…]()

mode <- c("WALK", "TRANSIT")

max_walk_time <- 15 # in minutes

travel_time_cutoff <- 50 

departure_datetime_tr <- as.POSIXct("15-11-2023 02:30:00", format = "%d-%m-%Y %H:%M:%S")

time_window <- 50 # in minutes

percentiles <- 50

**Comment by rafapereirabr** [comment]
could you please the code you used in the analysi ?

**Comment by hasanglr** [comment]
Sure, here is the rest of the code:

access_jobs <- accessibility(r5r_core,
                        origins = origin,
                        destinations = job_dest,
                        mode = mode,
                        opportunities_colnames = c("jobs"),
                        decay_function = "step",
                        cutoffs = travel_time_cutoff,
                        departure_datetime = departure_datetime_tr,
                        max_walk_time = max_walk_time,
                        time_window = time_window,
                        percentiles = percentiles,
                        progress = TRUE)

**Comment by rafapereirabr** [comment]
I'm closing this issue due to no response. I'm happy to reopen it if the problem persists

**Comment by rafapereirabr** [comment]
ah, no problem. Thanks for the feedback @hasanglr !
