### ISSUE TITLE
travel time cutoff beyond 120 minutes

### ISSUE THREAD

**Issue by FatemehJanat** [ipeaGIT/r5r#404]
Hi r5r team! I am using the accessibility() function in r5r to measure transit access with a custom travel time cutoff. I set the travel time cutoffs to 360 minutes (6 hours), but I face the following error:

_Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: 
  java.lang.IllegalArgumentException: Cutoffs must be at most 120 minutes._

It seems like there is a hardcoded restriction on the maximum trip duration, but for my analysis, I need to extend this to a higher value. Is there a way to extend the maximum trip duration to more than 120 minutes?
Thank you for your help!

Reproducible code:

library(r5r)

data_path <- system.file("extdata/poa", package = "r5r")
r5r_core <- setup_r5(data_path = data_path, temp_dir = TRUE)

points <- read.csv(file.path(data_path, "poa_hexgrid.csv"))

points$total <- sample(1:100, size = nrow(points), replace = TRUE)

mode <- c("TRANSIT")
travel_time_cutoff <- 360 # 6 hours in minutes
departure_datetime <- as.POSIXct("12-07-2024 14:30:00", format = "%d-%m-%Y %H:%M:%S")
time_window <- 360 # minutes
percentiles <- 50

access <- accessibility(r5r_core,
                        origins = points,
                        destinations = points,
                        mode = mode,
                        opportunities_colname = "total",  # Ensure 'total' column exists
                        decay_function = "step",
                        cutoffs = travel_time_cutoff,
                        departure_datetime = departure_datetime,
                        time_window = time_window,
                        percentiles = percentiles,
                        verbose = FALSE)

**Comment by rafapereirabr** [comment]
Hi @FatemehJanat . Indeed, it seems the upper limit of 120 minutes is hard coded for the accessibility analysis. See [here](https://github.com/conveyal/r5/blob/e5a9a2653ce8ac561c7b182b87764f2c94e7d594/src/main/java/com/conveyal/r5/analyst/cluster/AnalysisWorkerTask.java#L319).

Nonetheless,  there is no upper limit for the `r5r::travel_time_matrix()` function. So the easiest way around this problem would be to calculate the travel time matrix first, and then using it to calculate accessibility, which can be done in a super simple a flexible manner using the [{accessibility}](https://ipeagit.github.io/accessibility/) package.

**Comment by FatemehJanat** [comment]
Thank you so much, @rafapereirabr ! This is helpful.
