### ISSUE TITLE
Is it possible to layer GTFS files upon an existing network to speed up r5_setup()?

### ISSUE THREAD

**Issue by p3nt0xide** [ipeaGIT/r5r#408]
As I would like to use r5 in production and let users actively change gtfs components, I seek to minimize the setup time required by r5_setup(). 

Hence, I was wondering whether there would be something in the likes of the "layering gtfs onto osm"-functionality from OTP (https://docs.opentripplanner.org/en/v2.6.0/Basic-Tutorial/#layering-gtfs-onto-osm)? Or maybe there is another alternative?

Cheers!

**Comment by rafapereirabr** [comment]
Hi @p3nt0xide . Building the network with R5 (and hence r5r) is usually much much faster than OTP. I know R5 has a powerful capability that allows users to dynamically edit the GTFS network through [Conveyal Analysis](https://docs.conveyal.com/edit-scenario). We don't have plans to implement that in r5r yet.

**Comment by stupidpupil** [comment]
To give some example figures [from this, creating R5 and OTP networks for Wales](https://github.com/stupidpupil/wales_ish_otp_graph/actions/runs/11548022192) using free GitHub Action runners:

Creating the OTP network took about 3 hours. Two hours of that was creating the street network (including using cached elevation lookups) and an hour was handling the GTFS data.

Creating the R5 network took about 10 minutes.

(A caveat is that I'm not including elevation in the R5 network, but I believe it's handled quite differently to OTP anyway?)

**Comment by p3nt0xide** [comment]
Hey. 

Many thanks, will consider that!

Cheers
