### ISSUE TITLE
What rules does r5r use to identify walkable roads in OSM data?

### ISSUE THREAD

**Issue by luyuliu** [ipeaGIT/r5r#411]
Not a bug or issue per se, but just me wondering which tags or mechanisms in OSM data does r5r use to identify walkable roads? I could not find any documentation about this.

Context: I am trying to add and modify some links in the OSM dataset to create a series of scenarios. I know some potential candidates, such as highway, foot, sidewalk, and access/pedestrian. However, does it follows a specific rule? Like any roads would be walkable as long as no tags specifically forbid walking/pedestrian access. Could you please point me to the corresponding code? 

Thanks,
Luyu

**Comment by stupidpupil** [comment]
I think it's this bit of R5 (which is what r5r is built on): https://github.com/conveyal/r5/blob/9ba72c3c26f54af66cebc42dfbb6fac8504cc162/src/main/java/com/conveyal/r5/labeling/TraversalPermissionLabeler.java#L47

**Comment by rafapereirabr** [comment]
Thanks @stupidpupil  !

**Comment by luyuliu** [comment]
Thank you! @stupidpupil , just want to confirm my understanding is correct:

`addPermissions("motorway", "access=yes;bicycle=no;foot=no");
addPermissions("trunk|primary|secondary|tertiary|unclassified|residential|living_street|road|service|track", "access=yes");
addPermissions("pedestrian", "access=no;foot=yes");
addPermissions("path", "access=no;foot=yes;bicycle=yes");
addPermissions("bridleway", "access=no"); //horse=yes but we don't support horse
addPermissions("cycleway", "access=no;bicycle=yes");
addPermissions("footway|steps|platform|public_transport=platform|railway=platform|corridor", "access=no;foot=yes");`

So is this the all the rule? if foot=yes, then the tag can be used by pedestrians?

But why there is a hashmap with boolean data for each tag? Do the true/false mean anything? 

`Map<String, Boolean> validHighwayTagsConst;
validHighwayTagsConst = new HashMap<>(16);
validHighwayTagsConst.put("motorway", true);
validHighwayTagsConst.put("trunk", true);
validHighwayTagsConst.put("primary", true);
validHighwayTagsConst.put("secondary", true);
validHighwayTagsConst.put("tertiary", true);
validHighwayTagsConst.put("unclassified", false);
validHighwayTagsConst.put("residential", false);
validHighwayTagsConst.put("living_street", false);
validHighwayTagsConst.put("road", false);
validHighwayTagsConst.put("service", false);
validHighwayTagsConst.put("track", false);
validHighwayTagsConst.put("pedestrian", false);
validHighwayTagsConst.put("path", false);
validHighwayTagsConst.put("bridleway", false);
validHighwayTagsConst.put("cycleway", false);
validHighwayTagsConst.put("footway", false);
validHighwayTagsConst.put("steps", false);
validHighwayTagsConst.put("platform", false);
validHighwayTagsConst.put("corridor", false);`

Thank you for the answer again!

Luyu
