### ISSUE TITLE
informing r5r users about rJavaEnv

### ISSUE THREAD

**Issue by e-kotov** [ipeaGIT/r5r#414]
Hi @rafapereirabr ,

This issue is about informing users of rJavaEnv to setup their environment.

1. I've noticed that the `{r5r}`'s [website](https://ipeagit.github.io/r5r/) a a bit out of date compared to the README in the repo. It still suggests to use `rJava::.jinit`. I am guessing it just wasn't rebuild recently with pkgdown.

2. For your consideration, I have recently stumbled upon another way to help users with Java issues by pointing towards rJavaEnv as a possible solution (by @JsLth):

https://github.com/JsLth/photon/blob/64dc9ce31a2d3cdcaf92cf7f6702198590a799f9/R/java.R#L42-L47

So this message should help those who do not read the docs before using your package. Though I have to say, it seems to me that the number of issues related to Java have gone down over the last half a year. I would attributed it more to the fact that the most recent Java is now ok to use and people are more likely to already have it installed.

Just a suggestion, no pressure.

**Comment by rafapereirabr** [comment]
Hi @e-kotov ! Thanks for opening this issue. I'll update the pkgdown website.

I'll also update our error message to look like this:

```
  if (ver != 21) {
    cli::cli_abort(c(
      "r5r requires the Java SE Development Kit {.strong 21}.",
      "x" = "Please update your Java installation.",
      ">" = "The JDK 21 can be downloaded from either of these links:",
      "  - {cli::style_hyperlink('OpenJDK', 'https://jdk.java.net/java-se-ri/21')}",
      "  - {cli::style_hyperlink('Adoptium/Eclipse Temurin', 'https://adoptium.net')}",
      "  - {cli::style_hyperlink('Amazon Corretto', 'https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html')}",
      "Alternatively, consider setting up a Java environment with the {cli::style_hyperlink('rJavaEnv', 'https://www.ekotov.pro/rJavaEnv')} package."
    ))
  }
```

**Comment by rafapereirabr** [comment]
the website has been update! the error message is now implemented in the dev branch

**Comment by e-kotov** [comment]
Great! I hope that will help further prevent any new issues with Java for `{r5r}` users!
