### ISSUE TITLE
Error detailed_itineraries

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#54]
@dhersz , I'm curently getting this error in the `detailed_itineraries`. Thia might be related to recent changes in the function/package. Could you please update the test script?

```
library(r5r)
library(covr)
library(testthat)

# test
test_file("tests/testthat/test-detailed_itineraries.R")

# code coverage
covr::function_coverage(fun=r5r::detailed_itineraries, 
                        test_file("tests/testthat/test-detailed_itineraries.R"))

```
> test-detailed_itineraries.R:47: error: detailed_itineraries adequately raises warnings and errors
Eror: 2019-03-13 14:00:00 is not a valid 'mode'.
                                        Please use one of the following: TRANSIT, TRAM, SUBWAY, RAIL, BUS, FERRY, CABLE_CAR, GONDOLA, FUNICULAR, WALK, BICYCLE, CAR, BICYCLE_RENT, CAR_PARK

**Comment by rafapereirabr** [comment]
I believe this is the last issue we have to solve before CRAN submission

**Comment by mvpsaraiva** [comment]
I'm checking this here, and I've found out that:
1. Waiting times really are in seconds. I'll convert them to minutes in the next jar version.
2. In that particular case, waiting time is longer than segment duration because it's a very short bus ride, just 1 stop.
3. Those really long walking legs add up to more than allowed by max_trip_duration. I'll check R5's code to find what's going on.

**Comment by dhersz** [comment]
So the total duration of a segment is `duration` + `wait`? I always thought `wait` was already included in `duration`.

**Comment by mvpsaraiva** [comment]
Ok, so apparently R5 doesn't do a very good job on filtering detailed itineraries by `max_trip_duration`. I've added this filter to R5RCore, so those very long itineraries will not be showing up in the results any longer.

**Comment by rafapereirabr** [comment]
Good! Can we close this now ?

**Comment by mvpsaraiva** [comment]
> Good! Can we close this now ?

Yes, we can!
