### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#57]
We're very close to CRAN submission but before that we need to make suer `r5r` passes all checks (no error, no wanings and if possible no notes)

```
### CMD Check ----------------
# Check package errors
Sys.setenv(NOT_CRAN = "false")
devtools::check(pkg = ".",  cran = TRUE)
```

**Comment by rafapereirabr** [comment]
Hi all. I suggest we prioritize tackling these issues for now. I believe we are ready fro CRAN submission after solving them.

- #6 
- #54 
- #67

**Comment by dhersz** [comment]
I suggest solving this one too: https://github.com/ipeaGIT/r5r/issues/33

**Comment by rafapereirabr** [comment]
> I suggest solving this one too: #33

This issue #33 is very much related to how R5 works internally. While it would be good to understand this a bit better and eventually come up with a ways to address this issue (either within R5 or in the R package), I think we can submit our package to CRAN and address this latter.

**Comment by dhersz** [comment]
Ok Rafa. https://github.com/ipeaGIT/r5r/issues/6 is closed now too.

I think after addressing https://github.com/ipeaGIT/r5r/issues/93 we're all set.

**Comment by rafapereirabr** [comment]
No so soon :)  Not until the package is accepted on CRAN. This might be a long road to get there (but let's hope it's not).

**Comment by rafapereirabr** [comment]
For the record, here is our 1st feedback from CRAN

> Thanks,
> 
> All your examples are wrapped in \donttest{} and therefore do not get
> tested.
> 
> Please unwrap the examples if that is feasible and if they can be
> executed in < 5 sec for each Rd file or create additionally small toy
> examples to allow automatic testing.
> 
> Please make sure that you do not change the user's options, par or
> working directory. If you really have to do so within functions, please
> ensure with an *immediate* call of on.exit() that the settings are reset
> when the function is exited. e.g.:
> ...
> old <- options()         # code line i
> on.exit(options(old))    # code line i+1
> ...
> options(digits = 3)
> ...
> e.g.: zzz.R
> If you're not familiar with the function, please check ?on.exit. This
> function makes it possible to restore options before exiting a function
> even if the function breaks. Therefore it needs to be called immediately
> after the option change within a function.
> 
> 
> Please fix and resubmit.
> 
> Best,
> Gregor Seyer

**Comment by dhersz** [comment]
The users options bit should be fixed in https://github.com/ipeaGIT/r5r/commit/c7f219a2dc5e108081122f68f306b5ae806f8ebd.

Now the original options and number of threads to be used by `data.table` are saved inside `detailed_itineraries` and `travel_time_matrix` and restored on exit. The number of threads to be used by `data.table` inside the functions is set according to the `n_threads` parameter, as with the case of the number of threads used by R5.

**Comment by rafapereirabr** [comment]
Thanks , @dhersz !

**Comment by rafapereirabr** [comment]
Package submitted. ps. The CRAN maintainer said it would be fine to keep the package examples wrapped in `\donttest{}` since we wouldn't be able to run them on CRAN due to Java dependency,

**Comment by rafapereirabr** [comment]
Latest news from CRAN. I don't have an emoji for this

> Thanks, please omit the redundant "in R" in your title.
> 
> Please write package names, software names and API names in single
> quotes in Title and Description.
> 
> 
> Please download R5 in your example to tempdir().
> 
> 
> Please fix and resubmit.
> 
> Best,
> Swetlana Herbrandt

**Comment by mvpsaraiva** [comment]
I think the `tempdir` argument in `download_r5` could work. But we need to make sure we know that the jar is in the `tempdir` folder and not inside the package's folder, so I think we may need a `tempdir` argument in setup_r5 as well. Or is there a way to store the jar path in a global option?

**Comment by rafapereirabr** [comment]
I've implemented it in a way that it detects whether the Jar files has already been downloaded to the `tempdir`

**Comment by rafapereirabr** [comment]
package resubmited

**Comment by rafapereirabr** [comment]
Good news. `r5r` is on its way to CRAN

**Comment by rafapereirabr** [comment]
[Congratulations all! We are officially on CRAN ! ](https://cran.r-project.org/web/packages/r5r/index.html)
