### ISSUE TITLE
Units of inputs and outputs

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#67]
Can we please confirm what units are used the inputs and outputs of the package functions?

### input:
 - max_walk_dist
 - max_trip_duration
 - walk_speed
 - bike_speed

### output:

- `travel_time_matrix`
   - travel_time

- `detailed_itineraries`
   - duration
   - distance

**Comment by dhersz** [comment]
Updated detailed_itineraries and travel_time matrix (and their documentation) to now receive max_walk_dist in meters.

**Comment by kauebraga** [comment]
Commit https://github.com/ipeaGIT/r5r/commit/b20adaadba31b075124700b254ba843b55b7dc84 converts `travel_time_matrix`'s ttime to minutes (including documentation)

**Comment by dhersz** [comment]
Even though the documentation said the output was in seconds, it was actually in minutes. I reverted the changed here https://github.com/ipeaGIT/r5r/commit/bdc9d5e2b401ca3bafcf2656bc494c123bc89e57. Thanks for the catch on the documentation anyway.

**Comment by kauebraga** [comment]
Thanks! Final commit https://github.com/ipeaGIT/r5r/commit/9b9c7182cef733139d34df7d27a8ca595e14b86f will do it
