### ISSUE TITLE
Run Travis with correct Java version

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#71]
The package is failling on `devtools::check_win_release(pkg = ".")` and on Travis due to the Java version. This is the error we get: 
>   java.lang.UnsupportedClassVersioncom/conveyal/r5/R5RCore has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I'm investigating whether we can force Travis and CRAN tests to run on an specific version of Java by adding and specification on the `.travis.yml` file. There are some [clues here](https://www.deps.co/guides/travis-ci-latest-java/) but this will involve a long trial and error process.

**Comment by dhersz** [comment]
Closed via https://github.com/ipeaGIT/r5r/pull/110
