### ISSUE TITLE
stop_r5 doesn't collect garbage properly

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#80]
Right now what `stop_r5()` basically does is to remove `r5r_core` objects and freeing up the memory previously allocated to it. However, not all free memory is actually reallocated when calling `rJava::.jgc` inside `stop_r5`. Check below (I'm using Rio's data and network, which is much more memory intensive than out sample data):

```r
> data_path <- "rio/data/path"
> r5r_obj <- setup_r5(data_path, verbose = FALSE)
Using cached version from C:/Users/Usuario/Documents/R/win-library/4.0/r5r/jar/r5r_v4.9.0_20200822.jar

Using cached network.dat from C:/Users/Usuario/Documents/Mestrado/Dissertação/otp2/graphs/rio/network.dat
```

Memory usage:
![mem1](https://user-images.githubusercontent.com/1557047/91062092-ac1b1300-e602-11ea-91ac-7518f8c4fd2c.JPG)

After manually removing and garbage collecting:
```
> rm(r5r_obj)
> rJava::.jgc(R.gc = TRUE)
```
![mem2](https://user-images.githubusercontent.com/1557047/91062121-b4734e00-e602-11ea-9041-5f49088dc412.JPG)

Setting up again:
![mem3](https://user-images.githubusercontent.com/1557047/91062151-ba692f00-e602-11ea-806f-65a2f405c728.JPG)

Removing and garbage collecting within `stop_r5()`:
`stop_r5(r5r_obj)`

![mem4](https://user-images.githubusercontent.com/1557047/91062154-bb01c580-e602-11ea-9e1e-f8cbd07312b5.JPG)

Doesn't free everything. After another garbage collecting, out of `stop_r5`:
```rJava::.jgc(R.gc = TRUE)```
![mem5](https://user-images.githubusercontent.com/1557047/91062157-bb9a5c00-e602-11ea-9602-16821ae17ca0.JPG)

So... Not sure why it behaves like this.

A temporary fix to this is to always use the code below after finishing with r5r, but ideally `stop_r5` alone should be enough.
```r
stop_r5(r5r_obj)
rJava::.jgc(R.gc = TRUE)
```

Any ideas?

**Comment by mvpsaraiva** [comment]
We can try calling garbage collector at the end of `detailed_itineraries()` and `travel_time_matrix()`. Those functions are very memory intensive, and probably leave some garbage behind. This should make the work of `stop_r5()` easier.

**Comment by dhersz** [comment]
This is probably a good call! But note that in the example above all I did was to setup r5, so that wouldn't fix this problem.

**Comment by mattwigway** [comment]
I would suggest not calling `gc` directly, just deleting the objects and letting Java handle gc behind the scenes. The reason for this behavior probably has something to do with whether objects are in [eden, young, or survivor space](https://medium.com/@recepinancc/til-12-garbage-collection-young-vs-old-generations-ab95b6a68653), and additionally whether the Java VM has decided to release memory or whether it is holding onto it because it thinks it will use it again (the Java VM is actually a virtual machine, so it hangs onto memory for later allocation, rather than requesting memory from the OS for every allocation).

**Comment by dhersz** [comment]
Hello @mattwigway, thanks for the comment and sorry for the big delay on my part. I have removed the `.jgc` from `stop_r5` in https://github.com/ipeaGIT/r5r/commit/909945d3b8f54cca6291dcbfef6dd505574f0be9 as per your suggestion. Thanks again!

**Comment by dhersz** [comment]
Hello @mattwigway, thanks for the comment and sorry for the big delay on my part. I have removed the `.jgc` from `stop_r5` in https://github.com/ipeaGIT/r5r/commit/909945d3b8f54cca6291dcbfef6dd505574f0be9 as per your suggestion. Thanks again!
