### ISSUE TITLE
Functions to export

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#88]
I glimpsed through NAMESPACE and we're exporting some functions (`assert_points_input`, `posix_to_string`, `select_mode` and `set_...`) which are used only internally. Should those be exported or kept for internal use only?

**Comment by mvpsaraiva** [comment]
I vote for hiding them.

**Comment by rafapereirabr** [comment]
I agree it's Ok to not export the functions in the `utils.R` script

**Comment by dhersz** [comment]
Done https://github.com/ipeaGIT/r5r/commit/9f32c393e42d90525af2386c525ee8f013b27b82.
