### ISSUE TITLE
total_duration sums up to 0 when an option is composed of only one segment

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/r5r#93]
Check the example below. Also note that total_duration is different than the sum of segment_duration + wait almost always by an integer.

You can see that the first two options, direct trips by car and walk, have `total_duration = 0`, even though `segment_duration` is there.

Also, check the second option (CAR-BUS-WALK). The sum fo `segment_duration` + `wait` is 29.22, while the `total_duration` is 30.22. Same with the following option, which sums to 37.18 when total returns 38.18.
Perhaps it's useful to include the fields `segment_start_time` and `segment_end_time`. We could use these to calculate the segment duration and to check whether the trip is actually starting at the time we are passing on `departure_datetime` or if there's some initial wait going on.

```r
data_path <- system.file("extdata", package = "r5r")
r5r_obj <- setup_r5(data_path = data_path)
points <- read.csv(file.path(data_path, "poa_points_of_interest.csv"))

origins      <- points[10,]
destinations <- points[12,]

df <- detailed_itineraries(
   r5r_obj,
   origins,
   destinations,
   mode = c("WALK", "CAR", "BUS"),
   departure_datetime = as.POSIXct("13-03-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S"),
   max_walk_dist = Inf,
   max_trip_duration = 120L,
   walk_speed = 3.6,
   bike_speed = 12,
   shortest_path = FALSE,
   n_threads = Inf,
   verbose = FALSE,
   drop_geometry = FALSE
 )

stop_r5(r5r_obj)
rJava::.jgc(R.gc = TRUE)
```
```
> df
Simple feature collection with 8 features and 14 fields
geometry type:  LINESTRING
dimension:      XY
bbox:           xmin: -51.22976 ymin: -30.05522 xmax: -51.19807 ymax: -29.99884
geographic CRS: WGS 84
            fromId   fromLat   fromLon                           toId     toLat     toLon option segment mode total_duration segment_duration wait
1 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875      1       1 WALK           0.00           119.40 0.00
2 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875      2       1  CAR           0.00            20.60 0.00
3 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     38       1  CAR          30.22            17.72 0.00
4 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     38       2  BUS          30.22             0.13 3.15
5 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     38       3 WALK          30.22             8.22 0.00
6 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     29       1  CAR          38.18            13.35 0.00
7 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     29       2  BUS          38.18             0.60 1.98
8 farrapos_station -29.99772 -51.19762 praia_de_belas_shopping_center -30.04995 -51.22875     29       3 WALK          38.18            21.25 0.00
  distance   route                       geometry
1     7002         LINESTRING (-51.19807 -29.9...
2     7779         LINESTRING (-51.19981 -29.9...
3     8803         LINESTRING (-51.20018 -30.0...
4       41  poa:T2 LINESTRING (-51.22853 -30.0...
5      483         LINESTRING (-51.22846 -30.0...
6     5791         LINESTRING (-51.20018 -30.0...
7      248 poa:R10 LINESTRING (-51.22822 -30.0...
8     1263         LINESTRING (-51.22972 -30.0...
```

**Comment by mvpsaraiva** [comment]
I believe `total_duration` taken straight from R5 rarely will be the exact sum of individual durations and waiting times. This is because of the way R5 handles this: that `total_duration` is just the average of many very similar path options (I could have taken the min and max values as well). So, I think that we need to calculate that in R if we want to give that result to the user.

I've also noticed the `total_duration = 0` in direct trips, but I didn't have the time to look for the source of that problem yet. But as I said, I think we need to calculate that value in R anyways.

**Comment by mvpsaraiva** [comment]
> Perhaps it's useful to include the fields `segment_start_time` and `segment_end_time`. We could use these to calculate the segment duration and to check whether the trip is actually starting at the time we are passing on `departure_datetime` or if there's some initial wait going on.

It's a good idea, I'll add those extra outputs.

**Comment by dhersz** [comment]
Cool, so I suggest removing `total_duration` and `segment_duration`, since `segment_start_time - segment_end_time` would provide us the total duration, and segment duration in this case is `total_duration - wait`. Is that right?

**Comment by dhersz** [comment]
The problem persists with the new jar.

**Comment by mvpsaraiva** [comment]
> The problem persists with the new jar.

Indeed, it does persist. I'm just passing along R5's outputs, in this case, so we can debug and use it as a reference. I suggest we calculate `total_duration` and `number_of_transfers` in R, which is much easier.

**Comment by dhersz** [comment]
Seems good to me.
